//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class MISSING_TYPE;

@interface _TtC10CoreAuthUI27PasscodeSheetViewController
{
    MISSING_TYPE *context;	// 8 = 0x8
    MISSING_TYPE *viewModel;	// 16 = 0x10
    MISSING_TYPE *failures;	// 24 = 0x18
    MISSING_TYPE *expectsDismiss;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x0040000000024130
- (id)initWithInternalInfo:(id)arg1 parent:(id)arg2;	// IMP=0x0010000000024070
- (id)initWithCoder:(id)arg1;	// IMP=0x0010000000023e90
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x0010000000023d70
- (id)initWithInternalInfo:(id)arg1 mechanism:(id)arg2 backoffCounter:(id)arg3 remoteUIHost:(id)arg4 allowsLandscape:(_Bool)arg5;	// IMP=0x0010000000023be0
- (void)dismissChildWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x0010000000023a10
- (_Bool)isFullScreenController;	// IMP=0x00100000000237a0
- (void)didReceiveAuthenticationData;	// IMP=0x0010000000023770
- (void)loadView;	// IMP=0x0010000000021c10
@property(nonatomic, readonly) long long preferredStatusBarStyle;
@property(nonatomic) long long modalPresentationStyle;

@end

