//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface SDAirDropHandlerMixedTypes
{
}

- (void)openLinks;	// IMP=0x00400000001e95d5
- (void)updatePossibleActions;	// IMP=0x00100000001e9323
- (id)suitableContentsDescription;	// IMP=0x00100000001e9195
- (long long)transferTypes;	// IMP=0x00100000001e9160
- (_Bool)canHandleTransfer;	// IMP=0x00100000001e9158
- (id)initWithTransfer:(id)arg1;	// IMP=0x00100000001e9129

@end

