//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "SFAirDropTransferObserverDelegate-Protocol.h"

@class SFAirDropTransfer;

@protocol SFAirDropTransferObserverProtocol <SFAirDropTransferObserverDelegate>
- (void)removedTransfer:(SFAirDropTransfer *)arg1;
@end

