//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIResponder.h>

@class NSString, UIWindow;

@interface AppDelegate : UIResponder
{
    UIWindow *_window;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0020000000005013
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
- (void)_presentInheritanceInvitationWithBeneficiaryID:(id)arg1 fallBackURL:(id)arg2;	// IMP=0x0010000000004d56
- (void)_presentCustodianInvitationWithUUID:(id)arg1 fallBackURL:(id)arg2;	// IMP=0x0010000000004ac8
- (void)_openCustomDomainURL:(id)arg1 domainState:(id)arg2;	// IMP=0x001000000000480c
- (void)_openCustomDomainManageURL;	// IMP=0x001000000000478b
- (void)_openPrivateEmailManageURL;	// IMP=0x001000000000470a
- (_Bool)application:(id)arg1 continueUserActivity:(id)arg2 restorationHandler:(CDUnknownBlockType)arg3;	// IMP=0x00100000000046f5
- (_Bool)handleUniversalLinkInUserActivity:(id)arg1;	// IMP=0x001000000000431c
- (void)applicationWillTerminate:(id)arg1;	// IMP=0x0010000000004316
- (void)applicationDidBecomeActive:(id)arg1;	// IMP=0x0010000000004310
- (void)applicationWillEnterForeground:(id)arg1;	// IMP=0x001000000000430a
- (void)applicationDidEnterBackground:(id)arg1;	// IMP=0x0010000000004304
- (void)applicationWillResignActive:(id)arg1;	// IMP=0x00100000000042fe
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;	// IMP=0x00100000000042f6

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

