//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ClassKit/CLSBlob.h>

@class NSObject, NSString;
@protocol PDDatabaseValue;

@interface CLSBlob (PDSyncableItem)
+ (id)recordType;	// IMP=0x00200000000567c5
+ (long long)migrationOrder;	// IMP=0x0010000000170d22
+ (_Bool)migrateFromVersion:(unsigned long long)arg1 finalVersion:(out unsigned long long *)arg2 inDatabase:(id)arg3;	// IMP=0x0010000000170c8a
+ (id)entityName;	// IMP=0x00100000001709d3
@property(readonly, nonatomic) NSString *parentReferenceName;
@property(readonly, nonatomic) long long syncableItemType;
- (long long);	// IMP=0x0010000000056a15
- (void)populate:(id)arg1;	// IMP=0x0010000000056915
- (id)initWithCKRecord:(id)arg1;	// IMP=0x00100000000567d2
- (void)bindTo:(id)arg1;	// IMP=0x0010000000170b00
- (id)initWithDatabaseRow:(id)arg1;	// IMP=0x00100000001709e0

// Remaining properties
@property(readonly, nonatomic) unsigned long long changeHash;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, nonatomic, getter=isDeleteTracked) _Bool deleteTracked;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, nonatomic) NSObject<PDDatabaseValue> *identityValue;
@property(readonly) Class superclass;
@end

