//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSMapTable;

@interface PDCKPushLocalChanges
{
    NSMapTable *_processedSynItemsByRecordID;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x00200000000e423c
- (void)populateRecordsToSave:(id)arg1 idsToDelete:(id)arg2 withSyncItem:(id)arg3;	// IMP=0x00100000000e3d68
- (void)resolvePartialErrors:(id)arg1;	// IMP=0x00100000000e32ff
- (void)scheduleRecordsToSave:(id)arg1 recordIDsToDelete:(id)arg2 savePolicy:(long long)arg3;	// IMP=0x00100000000e2c69
- (void)deleteProcessedSyncAssociatedWithRecordID:(id)arg1;	// IMP=0x00100000000e29d4
- (void)deleteSyncStateForRecordIDs:(id)arg1;	// IMP=0x00100000000e2782
- (void)recordUpdated:(id)arg1;	// IMP=0x00100000000e265b
- (id)recordForSyncItem:(id)arg1;	// IMP=0x00100000000e2475
- (void)execute;	// IMP=0x00100000000e1de0

@end

