//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@class NSMutableArray, NSString, PDDPActivityReport, PDDPDate;

@interface PDDPHandoutReportItem : PBCodable
{
    NSMutableArray *_additionalReports;	// 8 = 0x8
    NSString *_attachmentId;	// 16 = 0x10
    NSString *_classId;	// 24 = 0x18
    PDDPDate *_endDate;	// 32 = 0x20
    int _granularity;	// 40 = 0x28
    NSString *_handoutId;	// 48 = 0x30
    PDDPActivityReport *_report;	// 56 = 0x38
    NSString *_reportItemId;	// 64 = 0x40
    PDDPDate *_startDate;	// 72 = 0x48
    NSString *_studentId;	// 80 = 0x50
    int _type;	// 88 = 0x58
    _Bool _isCompleted;	// 92 = 0x5c
    struct {
        unsigned int granularity:1;
        unsigned int type:1;
        unsigned int isCompleted:1;
    } _has;	// 96 = 0x60
}

+ (Class)additionalReportsType;	// IMP=0x002000000019314f
- (void).cxx_destruct;	// IMP=0x0020000000194d4e
@property(retain, nonatomic) NSString *reportItemId; // @synthesize reportItemId=_reportItemId;
@property(retain, nonatomic) NSMutableArray *additionalReports; // @synthesize additionalReports=_additionalReports;
@property(retain, nonatomic) PDDPActivityReport *report; // @synthesize report=_report;
@property(nonatomic) _Bool isCompleted; // @synthesize isCompleted=_isCompleted;
@property(retain, nonatomic) NSString *attachmentId; // @synthesize attachmentId=_attachmentId;
@property(retain, nonatomic) PDDPDate *endDate; // @synthesize endDate=_endDate;
@property(retain, nonatomic) PDDPDate *startDate; // @synthesize startDate=_startDate;
@property(retain, nonatomic) NSString *classId; // @synthesize classId=_classId;
@property(retain, nonatomic) NSString *studentId; // @synthesize studentId=_studentId;
@property(retain, nonatomic) NSString *handoutId; // @synthesize handoutId=_handoutId;
- (void)mergeFrom:(id)arg1;	// IMP=0x00100000001948f1
- (unsigned long long)hash;	// IMP=0x001000000019476c
- (_Bool)isEqual:(id)arg1;	// IMP=0x001000000019449b
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x001000000019411f
- (void)copyTo:(id)arg1;	// IMP=0x0010000000193efb
- (void)writeTo:(id)arg1;	// IMP=0x0010000000193c6d
- (_Bool)readFrom:(id)arg1;	// IMP=0x0010000000193c60
- (id)dictionaryRepresentation;	// IMP=0x0010000000193224
- (id)description;	// IMP=0x0010000000193175
@property(readonly, nonatomic) _Bool hasReportItemId;
- (id)additionalReportsAtIndex:(unsigned long long)arg1;	// IMP=0x0010000000193132
- (unsigned long long)additionalReportsCount;	// IMP=0x0010000000193115
- (void)addAdditionalReports:(id)arg1;	// IMP=0x00100000001930ab
- (void)clearAdditionalReports;	// IMP=0x001000000019308e
@property(readonly, nonatomic) _Bool hasReport;
@property(nonatomic) _Bool hasIsCompleted;
@property(readonly, nonatomic) _Bool hasAttachmentId;
@property(readonly, nonatomic) _Bool hasEndDate;
@property(readonly, nonatomic) _Bool hasStartDate;
@property(readonly, nonatomic) _Bool hasClassId;
@property(readonly, nonatomic) _Bool hasStudentId;
@property(readonly, nonatomic) _Bool hasHandoutId;
- (int)StringAsGranularity:(id)arg1;	// IMP=0x0010000000192ee5
- (id)granularityAsString:(int)arg1;	// IMP=0x0010000000192e9c
@property(nonatomic) _Bool hasGranularity;
@property(nonatomic) int granularity; // @synthesize granularity=_granularity;
- (int)StringAsType:(id)arg1;	// IMP=0x0010000000192d6d
- (id)typeAsString:(int)arg1;	// IMP=0x0010000000192d24
@property(nonatomic) _Bool hasType;
@property(nonatomic) int type; // @synthesize type=_type;

@end

