//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;
@protocol PDDatabaseValue;

@interface PDPendingIngestItem : NSObject
{
    _Bool _wasDeleted;	// 8 = 0x8
    Class _entity;	// 16 = 0x10
    id <PDDatabaseValue> _entityIdentity;	// 24 = 0x18
}

+ (id)identityColumnName;	// IMP=0x002000000016af4f
+ (_Bool)migrateFromVersion:(unsigned long long)arg1 finalVersion:(out unsigned long long *)arg2 inDatabase:(id)arg3;	// IMP=0x001000000016aeb7
+ (id)entityName;	// IMP=0x001000000016ac5c
- (void).cxx_destruct;	// IMP=0x002000000016afb6
@property(retain, nonatomic) id <PDDatabaseValue> entityIdentity; // @synthesize entityIdentity=_entityIdentity;
@property(nonatomic) _Bool wasDeleted; // @synthesize wasDeleted=_wasDeleted;
@property(retain, nonatomic) Class entity; // @synthesize entity=_entity;
@property(readonly, nonatomic) NSObject<PDDatabaseValue> *identityValue;
- (void)bindTo:(id)arg1;	// IMP=0x001000000016adb8
- (id)initWithDatabaseRow:(id)arg1;	// IMP=0x001000000016ac69

// Remaining properties
@property(readonly, nonatomic) unsigned long long changeHash;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, nonatomic, getter=isDeleteTracked) _Bool deleteTracked;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

