//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableArray;
@protocol OS_dispatch_queue;

@interface TCCDAlertManager : NSObject
{
    NSMutableArray *_alerts;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_displayQueue;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0020000000053fb0
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *displayQueue; // @synthesize displayQueue=_displayQueue;
@property(retain, nonatomic) NSMutableArray *alerts; // @synthesize alerts=_alerts;
- (void)displayAlertForCondition:(long long)arg1;	// IMP=0x0010000000053d63
- (id)initWithAlerts:(id)arg1;	// IMP=0x0010000000053ccf

@end

