//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface (null) : NSObject
{
}

+ (id)audioRecorderWithQueue:(id)arg1 error:(id *)arg2;	// IMP=0x00400000000b51b0

@end

