//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface CSBatteryMonitor
{
}

+ (id)sharedInstance;	// IMP=0x00400000000e38d2
- (unsigned char)batteryState;	// IMP=0x00400000000e3914
- (id)init;	// IMP=0x00100000000e38da

@end

