//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface IDSClientDataGenerator : NSObject
{
}

+ (void)_fetchPresenceCapabilityForServiceTypes:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x0040000000179eb0
+ (_Bool)_shouldAddECKeysForServiceType:(id)arg1;	// IMP=0x0010000000179e60
+ (id)clientDatasForRegistrations:(id)arg1 keyStore:(id)arg2 keyTransparencyVerifier:(id)arg3;	// IMP=0x0010000000172960
+ (id)serviceTypesFromRegistrations:(id)arg1;	// IMP=0x0010000000172690

@end

