//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSData, NSString;

@interface IDSCloudKitKeyTransparencyDeviceRecord : NSObject
{
    NSData *_deviceData;	// 8 = 0x8
    NSData *_deviceMetadata;	// 16 = 0x10
    NSString *_recordID;	// 24 = 0x18
}

+ (id)recordWithDeviceData:(id)arg1 deviceMetadata:(id)arg2 recordID:(id)arg3;	// IMP=0x00400000001a87b0
- (void).cxx_destruct;	// IMP=0x00200000001a91a0
@property(readonly, nonatomic) NSString *recordID; // @synthesize recordID=_recordID;
@property(readonly, nonatomic) NSData *deviceMetadata; // @synthesize deviceMetadata=_deviceMetadata;
@property(readonly, nonatomic) NSData *deviceData; // @synthesize deviceData=_deviceData;
- (unsigned long long)hash;	// IMP=0x00100000001a9060
- (_Bool)isEqualToCloudKitKeyTransparencyDeviceRecord:(id)arg1;	// IMP=0x00100000001a8bc0
- (_Bool)isEqual:(id)arg1;	// IMP=0x00100000001a8b00
- (id)description;	// IMP=0x00100000001a89f0
- (id)initWithDeviceData:(id)arg1 deviceMetadata:(id)arg2 recordID:(id)arg3;	// IMP=0x00100000001a8880

@end

