//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class IDSMPFullLegacyIdentity, IDSMPPublicLegacyIdentity, IMTimer, NSArray, NSData, NSDate, NSDictionary, NSError, NSNumber, NSSet, NSString, NSUUID, _IDSSessionConnection;
@protocol IDSDSession;

@interface IDSDSessionSharedState : NSObject
{
    _Atomic _Bool _connectionTimerCleared;	// 8 = 0x8
    _Bool _disableEncryption;	// 9 = 0x9
    _Bool _disableRemoteDeviceEncryption;	// 10 = 0xa
    _Bool _enableQuickRelay;	// 11 = 0xb
    _Bool _enableSingleChannelDirectMode;	// 12 = 0xc
    _Bool _enableSKE;	// 13 = 0xd
    _Bool _encryptionInitialized;	// 14 = 0xe
    _Atomic _Bool _endSessionTimerCleared;	// 15 = 0xf
    _Bool _forceInternetInvitation;	// 16 = 0x10
    _Bool _isInitiator;	// 17 = 0x11
    _Bool _isInUPlusOneMode;	// 18 = 0x12
    _Bool _isScreenSharingSession;	// 19 = 0x13
    _Atomic _Bool _inviteTimerCleared;	// 20 = 0x14
    _Bool _sharedSession;	// 21 = 0x15
    _Bool _useBTDatagramPipe;	// 22 = 0x16
    _Bool _useSecureQRControlMessage;	// 23 = 0x17
    _Bool _useQRDirectly;	// 24 = 0x18
    unsigned int _invitationRetryCount;	// 28 = 0x1c
    unsigned int _peerProtocolVersion;	// 32 = 0x20
    unsigned int _seqSend;	// 36 = 0x24
    unsigned int _state;	// 40 = 0x28
    NSString *_accountID;	// 48 = 0x30
    long long _clientType;	// 56 = 0x38
    NSUUID *_clientUUID;	// 64 = 0x40
    _IDSSessionConnection *_connection;	// 72 = 0x48
    unsigned long long _connectionCountHint;	// 80 = 0x50
    double _connectionTimeout;	// 88 = 0x58
    IMTimer *_connectionTimer;	// 96 = 0x60
    NSSet *_destinations;	// 104 = 0x68
    NSDictionary *_destinationsLightweightStatus;	// 112 = 0x70
    double _endSessionTimeout;	// 120 = 0x78
    IMTimer *_endSessionTimer;	// 128 = 0x80
    NSError *_error;	// 136 = 0x88
    NSString *_fromID;	// 144 = 0x90
    NSString *_groupID;	// 152 = 0x98
    double _inviteSentTime;	// 160 = 0xa0
    double _inviteTimeout;	// 168 = 0xa8
    IMTimer *_inviteTimer;	// 176 = 0xb0
    double _lastPacketTime;	// 184 = 0xb8
    NSData *_localBlob;	// 192 = 0xc0
    IMTimer *_packetLossTimer;	// 200 = 0xc8
    NSString *_participantID;	// 208 = 0xd0
    NSNumber *_remoteUseCloudPairedControlChannel;	// 216 = 0xd8
    NSNumber *_remoteUsePhoneContinuityLocalMessage;	// 224 = 0xe0
    NSString *_serviceName;	// 232 = 0xe8
    NSDate *_startConnectingDate;	// 240 = 0xf0
    long long _transportType;	// 248 = 0xf8
    NSString *_uniqueID;	// 256 = 0x100
    NSArray *_requiredLackOfCapabilities;	// 264 = 0x108
    NSArray *_requiredCapabilities;	// 272 = 0x110
    IDSMPFullLegacyIdentity *_localUnauthenticatedFullIdentity;	// 280 = 0x118
    IDSMPPublicLegacyIdentity *_remoteUnauthenticatedPublicIdentity;	// 288 = 0x120
    id <IDSDSession> _delegate;	// 296 = 0x128
    CDStruct_eff2b79e _encryptionStateStruct;	// 304 = 0x130
}

- (void).cxx_destruct;	// IMP=0x0020000000575bb0
@property(nonatomic) CDStruct_eff2b79e encryptionStateStruct; // @synthesize encryptionStateStruct=_encryptionStateStruct;
@property(nonatomic) __weak id <IDSDSession> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) IDSMPPublicLegacyIdentity *remoteUnauthenticatedPublicIdentity; // @synthesize remoteUnauthenticatedPublicIdentity=_remoteUnauthenticatedPublicIdentity;
@property(retain, nonatomic) IDSMPFullLegacyIdentity *localUnauthenticatedFullIdentity; // @synthesize localUnauthenticatedFullIdentity=_localUnauthenticatedFullIdentity;
@property(retain, nonatomic) NSArray *requiredCapabilities; // @synthesize requiredCapabilities=_requiredCapabilities;
@property(retain, nonatomic) NSArray *requiredLackOfCapabilities; // @synthesize requiredLackOfCapabilities=_requiredLackOfCapabilities;
@property(nonatomic) _Bool useQRDirectly; // @synthesize useQRDirectly=_useQRDirectly;
@property(nonatomic) _Bool useSecureQRControlMessage; // @synthesize useSecureQRControlMessage=_useSecureQRControlMessage;
@property(nonatomic) _Bool useBTDatagramPipe; // @synthesize useBTDatagramPipe=_useBTDatagramPipe;
@property(retain, nonatomic) NSString *uniqueID; // @synthesize uniqueID=_uniqueID;
@property(nonatomic) long long transportType; // @synthesize transportType=_transportType;
@property(nonatomic) unsigned int state; // @synthesize state=_state;
@property(retain, nonatomic) NSDate *startConnectingDate; // @synthesize startConnectingDate=_startConnectingDate;
@property(nonatomic) _Bool sharedSession; // @synthesize sharedSession=_sharedSession;
@property(nonatomic) unsigned int seqSend; // @synthesize seqSend=_seqSend;
@property(retain, nonatomic) NSString *serviceName; // @synthesize serviceName=_serviceName;
@property(retain, nonatomic) NSNumber *remoteUsePhoneContinuityLocalMessage; // @synthesize remoteUsePhoneContinuityLocalMessage=_remoteUsePhoneContinuityLocalMessage;
@property(retain, nonatomic) NSNumber *remoteUseCloudPairedControlChannel; // @synthesize remoteUseCloudPairedControlChannel=_remoteUseCloudPairedControlChannel;
@property(nonatomic) unsigned int peerProtocolVersion; // @synthesize peerProtocolVersion=_peerProtocolVersion;
@property(retain, nonatomic) NSString *participantID; // @synthesize participantID=_participantID;
@property(retain, nonatomic) IMTimer *packetLossTimer; // @synthesize packetLossTimer=_packetLossTimer;
@property(retain, nonatomic) NSData *localBlob; // @synthesize localBlob=_localBlob;
@property(nonatomic) double lastPacketTime; // @synthesize lastPacketTime=_lastPacketTime;
@property(nonatomic) _Atomic _Bool inviteTimerCleared; // @synthesize inviteTimerCleared=_inviteTimerCleared;
@property(retain, nonatomic) IMTimer *inviteTimer; // @synthesize inviteTimer=_inviteTimer;
@property(nonatomic) double inviteTimeout; // @synthesize inviteTimeout=_inviteTimeout;
@property(nonatomic) unsigned int invitationRetryCount; // @synthesize invitationRetryCount=_invitationRetryCount;
@property(nonatomic) _Bool isScreenSharingSession; // @synthesize isScreenSharingSession=_isScreenSharingSession;
@property(nonatomic) _Bool isInUPlusOneMode; // @synthesize isInUPlusOneMode=_isInUPlusOneMode;
@property(nonatomic) _Bool isInitiator; // @synthesize isInitiator=_isInitiator;
@property(nonatomic) double inviteSentTime; // @synthesize inviteSentTime=_inviteSentTime;
@property(retain, nonatomic) NSString *groupID; // @synthesize groupID=_groupID;
@property(retain, nonatomic) NSString *fromID; // @synthesize fromID=_fromID;
@property(nonatomic) _Bool forceInternetInvitation; // @synthesize forceInternetInvitation=_forceInternetInvitation;
@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
@property(nonatomic) _Atomic _Bool endSessionTimerCleared; // @synthesize endSessionTimerCleared=_endSessionTimerCleared;
@property(retain, nonatomic) IMTimer *endSessionTimer; // @synthesize endSessionTimer=_endSessionTimer;
@property(nonatomic) double endSessionTimeout; // @synthesize endSessionTimeout=_endSessionTimeout;
@property(nonatomic) _Bool encryptionInitialized; // @synthesize encryptionInitialized=_encryptionInitialized;
@property(nonatomic) _Bool enableSKE; // @synthesize enableSKE=_enableSKE;
@property(nonatomic) _Bool enableSingleChannelDirectMode; // @synthesize enableSingleChannelDirectMode=_enableSingleChannelDirectMode;
@property(nonatomic) _Bool enableQuickRelay; // @synthesize enableQuickRelay=_enableQuickRelay;
@property(nonatomic) _Bool disableRemoteDeviceEncryption; // @synthesize disableRemoteDeviceEncryption=_disableRemoteDeviceEncryption;
@property(nonatomic) _Bool disableEncryption; // @synthesize disableEncryption=_disableEncryption;
@property(retain, nonatomic) NSDictionary *destinationsLightweightStatus; // @synthesize destinationsLightweightStatus=_destinationsLightweightStatus;
@property(retain, nonatomic) NSSet *destinations; // @synthesize destinations=_destinations;
@property(nonatomic) _Atomic _Bool connectionTimerCleared; // @synthesize connectionTimerCleared=_connectionTimerCleared;
@property(retain, nonatomic) IMTimer *connectionTimer; // @synthesize connectionTimer=_connectionTimer;
@property(nonatomic) double connectionTimeout; // @synthesize connectionTimeout=_connectionTimeout;
@property(nonatomic) unsigned long long connectionCountHint; // @synthesize connectionCountHint=_connectionCountHint;
@property(retain, nonatomic) _IDSSessionConnection *connection; // @synthesize connection=_connection;
@property(retain, nonatomic) NSUUID *clientUUID; // @synthesize clientUUID=_clientUUID;
@property(nonatomic) long long clientType; // @synthesize clientType=_clientType;
@property(retain, nonatomic) NSString *accountID; // @synthesize accountID=_accountID;
@property(readonly, nonatomic) NSString *pushTopic;
- (id)publicIdentityFromData:(id)arg1;	// IMP=0x0010000000574540
- (_Bool)destinationIsDefaultPairedDevice:(id)arg1;	// IMP=0x0010000000574470
- (_Bool)destinationIsGuestDevice:(id)arg1;	// IMP=0x0010000000574400
- (id)getQuickRelayAllocateOptions:(id)arg1;	// IMP=0x0010000000574020
- (_Bool)supportsReinitiate;	// IMP=0x0010000000573f20
- (void)_endSessionTimedOut;	// IMP=0x0010000000573dc0
- (void)_endSessionTimerFiredOnMain;	// IMP=0x0010000000573cf0
- (void)setEndSessionTimeoutTimer;	// IMP=0x0010000000573a70
- (void)_clearEndSessionTimeoutTimer;	// IMP=0x0010000000573880
- (void)_clearPacketLossTimer;	// IMP=0x0010000000573700
- (void)_connectionTimedOut;	// IMP=0x00100000005735b0
- (void)_connectionTimerFiredOnMain;	// IMP=0x00100000005734e0
- (void)setConnectionTimer;	// IMP=0x0010000000573070
- (void)_clearConnectionTimer;	// IMP=0x0010000000572e80
- (void)_clearInvitationTimer;	// IMP=0x0010000000572c90
- (void)_inviteTimedOut;	// IMP=0x0010000000572ad0
- (void)_inviteTimerFiredOnMain;	// IMP=0x0010000000572a00
- (void)setInvitationTimer;	// IMP=0x0010000000572770
- (void)clearAllTimers;	// IMP=0x0010000000572710
@property(readonly, nonatomic) CDStruct_eff2b79e *encryptionState;
- (id)initWithDictionary:(id)arg1 serviceName:(id)arg2 isInitiator:(_Bool)arg3 uniqueID:(id)arg4 accountID:(id)arg5 destinations:(id)arg6;	// IMP=0x001000000056fe40

@end

