//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class CUTUnsafePromise, IDSMPPublicDeviceIdentityContainer, NSData, NSDictionary, NSString;

@protocol IDSMPFullDeviceIdentityContainerEncrypter <NSObject>
- (CUTUnsafePromise *)decryptData:(NSData *)arg1 withPublicDeviceIdentityContainer:(IDSMPPublicDeviceIdentityContainer *)arg2 usingIdentifier:(NSString *)arg3 isRetry:(_Bool)arg4;
- (NSData *)decryptData:(NSData *)arg1 withPublicDeviceIdentityContainer:(IDSMPPublicDeviceIdentityContainer *)arg2 error:(id *)arg3 usingIdentifier:(NSString *)arg4 isRetry:(_Bool)arg5;
- (NSData *)encryptData:(NSData *)arg1 withEncryptedAttributes:(NSDictionary *)arg2 withPublicDeviceIdentityContainer:(IDSMPPublicDeviceIdentityContainer *)arg3 usedIdentifier:(id *)arg4 error:(id *)arg5;
- (NSData *)encryptData:(NSData *)arg1 withEncryptedAttributes:(NSDictionary *)arg2 withPublicDeviceIdentityContainer:(IDSMPPublicDeviceIdentityContainer *)arg3 usingIdentifier:(NSString *)arg4 error:(id *)arg5;
@end

