//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <FTServices/FTIDSMessage.h>

@class NSDictionary, NSString;

@interface IDSProvisionPseudonymMessage : FTIDSMessage
{
    unsigned long long _operation;	// 232 = 0xe8
    NSString *_pseudonymAlias;	// 240 = 0xf0
    NSString *_featureID;	// 248 = 0xf8
    NSString *_scopeID;	// 256 = 0x100
    NSDictionary *_subservicesByPrimaryService;	// 264 = 0x108
    double _expiryEpoch;	// 272 = 0x110
    NSString *_userVisibleName;	// 280 = 0x118
}

- (void).cxx_destruct;	// IMP=0x0020000000231220
@property(retain, nonatomic) NSString *userVisibleName; // @synthesize userVisibleName=_userVisibleName;
@property(nonatomic) double expiryEpoch; // @synthesize expiryEpoch=_expiryEpoch;
@property(retain, nonatomic) NSDictionary *subservicesByPrimaryService; // @synthesize subservicesByPrimaryService=_subservicesByPrimaryService;
@property(retain, nonatomic) NSString *scopeID; // @synthesize scopeID=_scopeID;
@property(retain, nonatomic) NSString *featureID; // @synthesize featureID=_featureID;
@property(retain, nonatomic) NSString *pseudonymAlias; // @synthesize pseudonymAlias=_pseudonymAlias;
@property(nonatomic) unsigned long long operation; // @synthesize operation=_operation;
- (double)anisetteHeadersTimeout;	// IMP=0x0010000000230f80
- (void)handleResponseDictionary:(id)arg1;	// IMP=0x0010000000230f40
- (void)handleResponseHeaders:(id)arg1;	// IMP=0x0010000000230f00
- (_Bool)requiresPushTokenKeys;	// IMP=0x0010000000230ee0
- (_Bool)hasRequiredKeys:(id *)arg1;	// IMP=0x0010000000230d90
- (id)messageBody;	// IMP=0x0010000000230940
- (id)requiredKeys;	// IMP=0x0010000000230910
- (id)bagKey;	// IMP=0x00100000002308f0
- (_Bool)wantsBodySignature;	// IMP=0x00100000002308d0
- (_Bool)allowDualDelivery;	// IMP=0x00100000002308b0
- (_Bool)wantsHTTPGet;	// IMP=0x0010000000230890
- (_Bool)wantsManagedRetries;	// IMP=0x0010000000230870
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0010000000230690

@end

