//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class CUTPromise, IDSDataMigrationTracker, IDSSystemAccountAdapter, IDSUserStore, NSString;
@protocol OS_dispatch_queue;

@interface IDSSystemAccountUserSynchronizer : NSObject
{
    IDSSystemAccountAdapter *_systemAccountAdapter;	// 8 = 0x8
    IDSUserStore *_userStore;	// 16 = 0x10
    IDSDataMigrationTracker *_migrationTracker;	// 24 = 0x18
    NSObject<OS_dispatch_queue> *_queue;	// 32 = 0x20
    CUTPromise *_migrationPromise;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x00200000006f0340
@property(retain, nonatomic) CUTPromise *migrationPromise; // @synthesize migrationPromise=_migrationPromise;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) IDSDataMigrationTracker *migrationTracker; // @synthesize migrationTracker=_migrationTracker;
@property(retain, nonatomic) IDSUserStore *userStore; // @synthesize userStore=_userStore;
@property(retain, nonatomic) IDSSystemAccountAdapter *systemAccountAdapter; // @synthesize systemAccountAdapter=_systemAccountAdapter;
- (id)updatedUserSetForRealm:(long long)arg1 currentUsers:(id)arg2;	// IMP=0x00100000006ef600
- (void)forceRemoveUser:(id)arg1 silently:(_Bool)arg2;	// IMP=0x00100000006ef4d0
- (id)initWithSystemAccountAdapter:(id)arg1 userStore:(id)arg2 migrationTracker:(id)arg3 queue:(id)arg4;	// IMP=0x00100000006ef370

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

