//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class IDSWPLinkManager;

@protocol IDSWPLinkManagerDelegate <NSObject>
- (void)manager:(IDSWPLinkManager *)arg1 linkDidDisconnect:(id)arg2;
- (void)manager:(IDSWPLinkManager *)arg1 linkDidConnect:(id)arg2;
- (void)manager:(IDSWPLinkManager *)arg1 didPowerStateChange:(_Bool)arg2;
@end

