//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class GEOSQLiteDB, NSString;

@interface GEOAnalyticsPipelinePersistence : NSObject
{
    GEOSQLiteDB *_db;	// 8 = 0x8
    _Bool _shadowEnabled;	// 16 = 0x10
    NSString *_dbFilePath;	// 24 = 0x18
    _Bool _firstAuthComplete;	// 32 = 0x20
}

+ (id)sharedInstance;	// IMP=0x0020000000025081
- (void).cxx_destruct;	// IMP=0x001000000002903e
- (void)processMapsAppDeletion;	// IMP=0x0010000000028f01
- (void)clearAllData;	// IMP=0x0010000000028e6b
- (void)clearPendingLogMsgElemsForBatchUploadWithBatchId:(unsigned long long)arg1;	// IMP=0x0010000000028cc0
- (void)clearExpiredLogMsgsWithResultBlock:(CDUnknownBlockType)arg1;	// IMP=0x00100000000286c6
- (void)selectDailySettingsWithVisitorBlock:(CDUnknownBlockType)arg1 completionBlock:(CDUnknownBlockType)arg2;	// IMP=0x001000000002824a
- (void)selectDailyCountsWithVisitorBlock:(CDUnknownBlockType)arg1 completionBlock:(CDUnknownBlockType)arg2;	// IMP=0x0010000000027cf6
- (void)selectCurCollViewsWithVisitorBlock:(CDUnknownBlockType)arg1 completionBlock:(CDUnknownBlockType)arg2;	// IMP=0x00100000000277ec
- (void)selectLogMsgsForBatchUploadWithBatchId:(unsigned long long)arg1 visitorBlock:(CDUnknownBlockType)arg2 completionBlock:(CDUnknownBlockType)arg3;	// IMP=0x00100000000272a9
- (id)selectBatchIdsForBatchUpload;	// IMP=0x00100000000270a9
- (void);	// IMP=0x0010000000026ca6
- (void)_writeRRLogElem:(id)arg1;	// IMP=0x0010000000026b11
- (void)_writeDailySettingsElem:(id)arg1;	// IMP=0x0010000000026927
- (void)_writeCuratedCollectionElem:(id)arg1;	// IMP=0x00100000000264bb
- (void)_writeDailyCountElem:(id)arg1;	// IMP=0x0010000000026082
- (void)_writeLogMsgQueueElem:(id)arg1;	// IMP=0x0010000000025cda
- (long long)_analyticsCount;	// IMP=0x0010000000025bba
- (void)_tearDown;	// IMP=0x0010000000025b4d
- (void)dealloc;	// IMP=0x0010000000025b0f
- (void)_setupEvalStmtsOnDb:(id)arg1;	// IMP=0x00100000000259b1
- (void)_configureDatabase;	// IMP=0x001000000002530e
@property(readonly, nonatomic) _Bool evalModeEnabled;
- (void)protectedDataDidBecomeAvailable:(id)arg1;	// IMP=0x00100000000252f3
@property(nonatomic) _Bool firstAuthComplete;
- (id)initWithDBFilePath:(id)arg1;	// IMP=0x001000000002517e
- (id)init;	// IMP=0x00100000000250d6
- (void)showEvalDataWithVisitorBlock:(CDUnknownBlockType)arg1;	// IMP=0x001000000002a4f7
- (void)flushEvalData;	// IMP=0x001000000002a453
- (void)setEvalMode:(_Bool)arg1;	// IMP=0x001000000002a3b6

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

