//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface AccountUserInfoUpdate
{
}

+ (id)_propertySettersForUserInfoUpdate;	// IMP=0x00400000003ce38e
+ (id)databaseTable;	// IMP=0x00100000003ce381
+ (void)deleteUserInfoUpdatePID:(long long)arg1 inDatabase:(id)arg2;	// IMP=0x00100000003ce2e8
+ (id)_predicateForEventPID:(long long)arg1;	// IMP=0x00100000003ce275
+ (id)insertUserInfoUpdate:(id)arg1 forEventPID:(long long)arg2 inDatabase:(id)arg3;	// IMP=0x00100000003cdffd
+ (id)userInfoUpdatesWithEventPID:(long long)arg1 inDatabase:(id)arg2;	// IMP=0x00100000003cdde7
- (id)userInfoUpdate;	// IMP=0x00400000003ce13d

@end

