//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface PayLaterAccountProductDetails
{
}

+ (id)_commonDictionaryForProductDetails:(id)arg1;	// IMP=0x00400000001c7c25
+ (id)_propertySettersForPayLaterAccountProductDetails;	// IMP=0x00100000001c74f1
+ (id)_predicateForProductPID:(long long)arg1;	// IMP=0x00100000001c747e
+ (id)payLaterProductDetailsForProductPID:(long long)arg1 inDatabase:(id)arg2;	// IMP=0x00100000001c735a
+ (void)deletePayLaterProductDetailsForPayLaterProductPID:(long long)arg1 inDatabase:(id)arg2;	// IMP=0x00100000001c72c1
+ (id)insertOrUpdatePayLaterProductDetails:(id)arg1 forPayLaterAccountProductPID:(long long)arg2 inDatabase:(id)arg3;	// IMP=0x00100000001c71b7
+ (id)associationPropertyForEntityClass:(Class)arg1;	// IMP=0x00100000001c7097
+ (id)databaseTable;	// IMP=0x00100000001c708a
- (id)_amountPaid;	// IMP=0x00400000001c7b5e
- (id)_totalFinanced;	// IMP=0x00100000001c7a97
- (id)_currentBalance;	// IMP=0x00100000001c79d0
- (id)_maximumSinglePurchaseAmount;	// IMP=0x00100000001c7909
- (id)_minimumSinglePurchaseAmount;	// IMP=0x00100000001c7842
- (id)productDetails;	// IMP=0x00100000001c75e3
- (void)updateWitProductDetails:(id)arg1;	// IMP=0x00100000001c7404
- (id)initWithAccountProductDetails:(id)arg1 forPayLaterAccountProductPID:(long long)arg2 inDatabase:(id)arg3;	// IMP=0x00100000001c70c6

@end

