//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface PDAccountPromptForVirtualCardDetailNotification
{
    NSString *_accountIdentifier;	// 112 = 0x70
    NSString *_virtualCardIdentifier;	// 120 = 0x78
}

+ (_Bool)supportsSecureCoding;	// IMP=0x0020000000232f09
- (void).cxx_destruct;	// IMP=0x0020000000232fbd
@property(readonly, nonatomic) NSString *virtualCardIdentifier; // @synthesize virtualCardIdentifier=_virtualCardIdentifier;
@property(readonly, nonatomic) NSString *accountIdentifier; // @synthesize accountIdentifier=_accountIdentifier;
- (id)notificationContentWithDataSource:(id)arg1;	// IMP=0x0010000000232f1c
- (unsigned long long)notificationType;	// IMP=0x0010000000232f11
- (id)_notificationIdentifierForAccountIdentifier:(id)arg1 virtualCardIdentifier:(id)arg2;	// IMP=0x0010000000232e65
- (id)initWithAccountIdentifier:(id)arg1 virtualCardIdentifier:(id)arg2 forPassUniqueIdentifier:(id)arg3;	// IMP=0x0010000000232d32

@end

