//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray, NSString;

@interface PDCloudStoreShareInvitationRequest : NSObject
{
    NSMutableArray *_completionHandlers;	// 8 = 0x8
    unsigned long long _type;	// 16 = 0x10
    NSString *_groupName;	// 24 = 0x18
    NSString *_suffix;	// 32 = 0x20
    long long _qualityOfService;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x002000000017b618
@property(readonly, copy, nonatomic) NSArray *completionHandlers; // @synthesize completionHandlers=_completionHandlers;
@property(nonatomic) long long qualityOfService; // @synthesize qualityOfService=_qualityOfService;
@property(copy, nonatomic) NSString *suffix; // @synthesize suffix=_suffix;
@property(copy, nonatomic) NSString *groupName; // @synthesize groupName=_groupName;
@property(readonly, nonatomic) unsigned long long type; // @synthesize type=_type;
- (_Bool)canCoalesceRequest:(id)arg1;	// IMP=0x001000000017b597
- (void)callCompletionsWithResponse:(id)arg1;	// IMP=0x001000000017b44e
- (_Bool)coalesceWithRequest:(id)arg1;	// IMP=0x001000000017b38c
- (id)initWithType:(unsigned long long)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000017b2d6

@end

