//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class NSString, PKPaymentPass;

@protocol PDDatabaseManagerPaymentServicesDelegate <NSObject>
- (void)handleDeletionForPassTypeIdentifier:(NSString *)arg1 serialNumber:(NSString *)arg2;
- (void)handleInsertionForPaymentPass:(PKPaymentPass *)arg1;
@end

