//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class MISSING_TYPE, NSDateComponents, PKCurrencyAmount;

@interface PDPassPaymentDailyDailyCashUserNotification
{
    _Bool _hasRedemptions;	// 112 = 0x70
    NSDateComponents *_dateComponents;	// 120 = 0x78
    PKCurrencyAmount *_periodAmount;	// 128 = 0x80
}

+ (_Bool)supportsSecureCoding;	// IMP=0x0020000000231fa4
+ (id)notificationIdentifierForDate:(id)arg1;	// IMP=0x00100000002319ae
- (void).cxx_destruct;	// IMP=0x002000000023206c
@property(readonly, nonatomic) _Bool hasRedemptions; // @synthesize hasRedemptions=_hasRedemptions;
@property(readonly, nonatomic) PKCurrencyAmount *periodAmount; // @synthesize periodAmount=_periodAmount;
@property(readonly, nonatomic) NSDateComponents *dateComponents; // @synthesize dateComponents=_dateComponents;
- (id)notificationContentWithDataSource:(id)arg1;	// IMP=0x0010000000231fb7
- (unsigned long long)notificationType;	// IMP=0x0010000000231fac
- (MISSING_TYPE *)encodeWithCoder: /* Error: Ran out of types for this method. */;	// IMP=0x0010000000231ee5
- (id)initWithCoder:(id)arg1;	// IMP=0x0010000000231dd8
- (id)initWithPeriodAmount:(id)arg1 date:(id)arg2 hasRedemptions:(_Bool)arg3 forPassUniqueIdentifier:(id)arg4;	// IMP=0x0010000000231ace

@end

