//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray, PDPassShareBundle, PKSecureElementPassFieldCollection;

@interface PDPassDaemonData : NSObject
{
    NSArray *_descriptors;	// 8 = 0x8
    PKSecureElementPassFieldCollection *_secureElementPassFieldCollection;	// 16 = 0x10
    PDPassShareBundle *_shareBundle;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00200000002608ef
- (id)description;	// IMP=0x00100000002607b8
- (id)init;	// IMP=0x001000000026057b

@end

