//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class MISSING_TYPE, NSDate, NSSet, NSString, PKPass, PKPeerPaymentAccount, PKPeerPaymentPreferences;

@protocol PDPeerPaymentWebServiceCoordinatorDataSource
- (NSSet *)peerPaymentTransactionServiceIdentifiersForTransactionSourceIdentifiers:(NSSet *)arg1 withPeerPaymentSubtype:(long long)arg2 withTransactionSource:(unsigned long long)arg3 withBackingData:(unsigned long long)arg4 startDate:(NSDate *)arg5 endDate:(NSDate *)arg6;
- (MISSING_TYPE *)addPeerPaymentAccountIdentifierToDatabaseTransactions;
- (_Bool)passExistsWithUniqueID:(NSString *)arg1;
- (PKPass *)passWithUniqueIdentifier:(NSString *)arg1;
- (void)deleteRetryBackoffForAccountType:(unsigned long long)arg1 endpointType:(unsigned long long)arg2 accountIdentifier:(NSString *)arg3;
- (void)increaseRetryBackoffLevelForAccountType:(unsigned long long)arg1 endpointType:(unsigned long long)arg2 accountIdentifier:(NSString *)arg3;
- (NSDate *)nextPossibleFetchDateForAccountType:(unsigned long long)arg1 endpointType:(unsigned long long)arg2 accountIdentifier:(NSString *)arg3;
- (PKPeerPaymentPreferences *)removePeerPaymentPreferences;
- (PKPeerPaymentPreferences *)insertOrUpdatePeerPaymentPreferences:(PKPeerPaymentPreferences *)arg1;
- (PKPeerPaymentPreferences *)peerPaymentPreferences;
- (PKPeerPaymentAccount *)removePeerPaymentAccount;
- (PKPeerPaymentAccount *)insertOrUpdatePeerPaymentAccount:(PKPeerPaymentAccount *)arg1;
- (PKPeerPaymentAccount *)peerPaymentAccount;
@end

