//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class NSObject, NSString;
@protocol OS_xpc_object;

@protocol PDXPCEventStreamObserver <NSObject>
- (void)receivedXPCEvent:(NSObject<OS_xpc_object> *)arg1 forEventStream:(NSString *)arg2;
@end

