//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class NSArray, NSDate, NSNumber, PKPaymentPass;

@protocol PKSecureElementConsistencyCheckerDelegate <NSObject>
- (void)deviceStateWithCompletion:(void (^)(PKSecureElementConsistencyCheckDeviceState *))arg1;
- (NSArray *)paymentPasses;
- (void)didDownloadPaymentPass:(PKPaymentPass *)arg1;
- (_Bool)synchronizeWithTSM;

@optional
- (void)handleRequestedActions:(NSArray *)arg1 completion:(void (^)(_Bool))arg2;
- (_Bool)shouldStartConsistencyCheck;
- (void)scheduleConsistencyCheck:(NSDate *)arg1 pluggedIn:(_Bool)arg2 backoffLevel:(NSNumber *)arg3;
- (void)scheduleConsistencyCheck:(NSDate *)arg1 pluggedIn:(_Bool)arg2;
@end

