//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface ValueAddedMerchant
{
}

+ (id)_propertySettersForValueAddedMerchant;	// IMP=0x0040000000352ba3
+ (id)_predicateForIdentifier:(id)arg1;	// IMP=0x0010000000352a48
+ (id)_predicateForPersistentID:(id)arg1;	// IMP=0x0010000000352a25
+ (id)anyInDatabase:(id)arg1 withIdentifier:(id)arg2;	// IMP=0x0010000000352999
+ (id)anyInDatabase:(id)arg1 withPersistentID:(id)arg2;	// IMP=0x001000000035290d
+ (id)databaseTable;	// IMP=0x0010000000352900
+ (id)insertValueAddedMerchant:(id)arg1 inDatabase:(id)arg2;	// IMP=0x0010000000352781
- (id)valueAddedMerchant;	// IMP=0x0040000000352a6b
- (void)updateWithValueAddedMerchant:(id)arg1;	// IMP=0x00100000003527ed
- (id)initWithValueAddedMerchant:(id)arg1 inDatabase:(id)arg2;	// IMP=0x0010000000352652

@end

