//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC14Xcode_Previews21RemoteContentProvider : _TtCs12_SwiftObject
{
    MISSING_TYPE *invalidationHandle;	// 16 = 0x10
    MISSING_TYPE *previewAgent;	// 0 = 0x0
    MISSING_TYPE *previewAgentPid;	// 0 = 0x0
    MISSING_TYPE *shellScene;	// 0 = 0x0
    MISSING_TYPE *remoteViewController;	// 0 = 0x0
    MISSING_TYPE *entryPointType;	// 0 = 0x0
    MISSING_TYPE *currentUpdateDelegate;	// 0 = 0x0
    MISSING_TYPE *processState;	// 0 = 0x0
}

@end

