//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class NSString;
@protocol WBSBookmarkDBAccess;

@protocol CloudBookmarkDatabaseCoordinating <NSObject>
@property(nonatomic) long long localMigrationState;
@property(readonly, nonatomic) id <WBSBookmarkDBAccess> databaseAccessor;
@property(readonly, nonatomic, getter=isDatabaseOpen) _Bool databaseOpen;
@property(readonly, nonatomic) const void *databaseRef;
- (void)closeDatabaseAndSave:(_Bool)arg1;
- (_Bool)openDatabase;
- (void)unlockForClient:(NSString *)arg1;
- (_Bool)lockForClient:(NSString *)arg1;
@end

