//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface _MoreEventsLabel : NSObject
{
    NSString *_string;	// 8 = 0x8
    long long _renderedNumberOfEvents;	// 16 = 0x10
    long long _numberOfEvents;	// 24 = 0x18
    struct CGRect _frame;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x0020000000043a71
@property(nonatomic) struct CGRect frame; // @synthesize frame=_frame;
@property(nonatomic) long long numberOfEvents; // @synthesize numberOfEvents=_numberOfEvents;
- (void)draw;	// IMP=0x00100000000437c3
- (id)init;	// IMP=0x0010000000043784

@end

