//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class EKEvent, NSLayoutConstraint, UILabel;

@interface CarplayStaticEventDetailsTableViewCell
{
    _Bool _showDayName;	// 8 = 0x8
    EKEvent *_event;	// 16 = 0x10
    UILabel *_titleView;	// 24 = 0x18
    UILabel *_locationView;	// 32 = 0x20
    UILabel *_dateView;	// 40 = 0x28
    UILabel *_timeView;	// 48 = 0x30
    NSLayoutConstraint *_timeBaselineToDateBaselineConstraint;	// 56 = 0x38
    NSLayoutConstraint *_timeBaselineToTitleBaselineConstraint;	// 64 = 0x40
    NSLayoutConstraint *_locationBaselineToTitleBaselineConstraint;	// 72 = 0x48
    NSLayoutConstraint *_timeBaselineToLocationBaselineConstraint;	// 80 = 0x50
    NSLayoutConstraint *_dateBaselineToTitleBaselineConstraint;	// 88 = 0x58
    NSLayoutConstraint *_dateBaselineToLocationBaselineConstraint;	// 96 = 0x60
}

- (void).cxx_destruct;	// IMP=0x002000000014db4c
@property(retain, nonatomic) NSLayoutConstraint *dateBaselineToLocationBaselineConstraint; // @synthesize dateBaselineToLocationBaselineConstraint=_dateBaselineToLocationBaselineConstraint;
@property(retain, nonatomic) NSLayoutConstraint *dateBaselineToTitleBaselineConstraint; // @synthesize dateBaselineToTitleBaselineConstraint=_dateBaselineToTitleBaselineConstraint;
@property(retain, nonatomic) NSLayoutConstraint *timeBaselineToLocationBaselineConstraint; // @synthesize timeBaselineToLocationBaselineConstraint=_timeBaselineToLocationBaselineConstraint;
@property(retain, nonatomic) NSLayoutConstraint *locationBaselineToTitleBaselineConstraint; // @synthesize locationBaselineToTitleBaselineConstraint=_locationBaselineToTitleBaselineConstraint;
@property(retain, nonatomic) NSLayoutConstraint *timeBaselineToTitleBaselineConstraint; // @synthesize timeBaselineToTitleBaselineConstraint=_timeBaselineToTitleBaselineConstraint;
@property(retain, nonatomic) NSLayoutConstraint *timeBaselineToDateBaselineConstraint; // @synthesize timeBaselineToDateBaselineConstraint=_timeBaselineToDateBaselineConstraint;
@property(retain, nonatomic) UILabel *timeView; // @synthesize timeView=_timeView;
@property(retain, nonatomic) UILabel *dateView; // @synthesize dateView=_dateView;
@property(retain, nonatomic) UILabel *locationView; // @synthesize locationView=_locationView;
@property(retain, nonatomic) UILabel *titleView; // @synthesize titleView=_titleView;
@property(retain, nonatomic) EKEvent *event; // @synthesize event=_event;
@property(nonatomic) _Bool showDayName; // @synthesize showDayName=_showDayName;
- (void)cellWasTapped;	// IMP=0x001000000014d91b
- (_Bool)isSelectable;	// IMP=0x001000000014d913
- (void)updateWithEvent:(id)arg1;	// IMP=0x001000000014cd7b
- (id)_createSecondaryView;	// IMP=0x001000000014cc65
- (id)_titleFont;	// IMP=0x001000000014cba7
- (id)_createPrimaryView;	// IMP=0x001000000014ca8c
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;	// IMP=0x001000000014c045

@end

