//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <EventKitUI/EKUIYearMonthView.h>

@class NSString;

@interface CompactYearMonthView : EKUIYearMonthView
{
}

+ (double)heightForInterfaceOrientation:(long long)arg1 windowSize:(struct CGSize)arg2 heightSizeClass:(long long)arg3;	// IMP=0x00200000000ebd78
- (_Bool)shouldAddPreciseInteractivity;	// IMP=0x00200000000ece8d
- (double)circleFrameYAdjustment;	// IMP=0x00100000000ecda1
- (double)weekDayInitialsAdjustTop;	// IMP=0x00100000000ecd98
- (double)weekDayInitialsAdjustLeft;	// IMP=0x00100000000ecd8f
- (id)weekDayInitialsFont;	// IMP=0x00100000000ecd87
- (_Bool)showWeekDayInitials;	// IMP=0x00100000000ecd7f
- (double)todayNumberKerning;	// IMP=0x00100000000ecc88
- (double)dayNumberKerning;	// IMP=0x00100000000ecb91
- (double)ySpacing;	// IMP=0x00100000000ecaa5
- (double)xSpacing;	// IMP=0x00100000000ec9b9
- (double)daysYAdjustTop;	// IMP=0x00100000000ec8b0
- (double)daysXAdjustLeft;	// IMP=0x00100000000ec8a2
- (double)circleSizeForDoubleDigit;	// IMP=0x00100000000ec890
- (double)circleSize;	// IMP=0x00100000000ec7bd
- (double)todayTextSize;	// IMP=0x00100000000ec6d1
- (double)dayTextSize;	// IMP=0x00100000000ec5b3
- (id)todayNumberFont;	// IMP=0x00100000000ec4e3
- (id)dayNumberFont;	// IMP=0x00100000000ec408
- (double)headerFontKerning;	// IMP=0x00100000000ec3ff
- (id)headerFont;	// IMP=0x00100000000ec350
- (double)headerFontMinSize;	// IMP=0x00100000000ec342
- (double)headerFontMaxSize;	// IMP=0x00100000000ec324
- (double)headerXAdjust;	// IMP=0x00100000000ec316
- (double)yInset;	// IMP=0x00100000000ec30d
- (double)xInset;	// IMP=0x00100000000ec221
- (double)_gridOfDaysHeightAdjustment;	// IMP=0x00100000000ec14e
- (double)_gridOfDaysYAdjustment;	// IMP=0x00100000000ec085
- (struct CGRect)frameForGridOfDays:(_Bool)arg1;	// IMP=0x00100000000ebecd
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;	// IMP=0x00100000000ebbe7

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

