//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface PhonePlusRotateDayTest
{
}

- (id)rotationAnimationCompleteNotificationName;	// IMP=0x0040000000056989
- (id)rotationAnimationStartedNotificationName;	// IMP=0x0000000000056975
- (void)_setupViewToDate:(id)arg1;	// IMP=0x00100000000568c2

@end

