//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKitCore/UIViewController.h>

@class _UIOverlayWelcomeView;

@interface _UIOverlayWelcomeViewController : UIViewController
{
    _UIOverlayWelcomeView *_welcomeView;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0020000000002341
@property(retain, nonatomic) _UIOverlayWelcomeView *welcomeView; // @synthesize welcomeView=_welcomeView;
- (void)viewDidLoad;	// IMP=0x00100000000021f2
- (void)loadView;	// IMP=0x001000000000214d

@end

