//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <AppleMediaServices/AMSDialogAction.h>

@class NSString;

@interface AMSDialogAction (LibAppStoreDaemon)
- (void)_lib_setAnalyticsEventDictionary:(id)arg1;	// IMP=0x00200000000809e8
- (id)_lib_analyticsEventDictionary;	// IMP=0x0010000000080991
@property(copy, nonatomic, setter=lib_setAnalyticsActionName:) NSString *lib_analyticsActionName;
@end

