//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class AKAccountManager;

@interface AKAuthorizationListUpdateService : NSObject
{
    AKAccountManager *_accountManager;	// 8 = 0x8
}

+ (id)sharedService;	// IMP=0x004000000008d0bd
- (void).cxx_destruct;	// IMP=0x002000000008d703
- (void);	// IMP=0x001000000008d47d
- (void)start;	// IMP=0x001000000008d178
- (id)init;	// IMP=0x001000000008d112

@end

