//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface AKCATiburonInputUIReporter
{
}

- (void)_clearMutuallyExclusiveProperties:(_Bool)arg1;	// IMP=0x0040000000027eef
- (void)didComplete:(_Bool)arg1;	// IMP=0x0010000000027e8c
- (void)didModifyName:(_Bool)arg1;	// IMP=0x0010000000027e32
- (void)didSelectPasswordCredential:(_Bool)arg1;	// IMP=0x0010000000027dca
- (void)didSelectAppleID:(_Bool)arg1;	// IMP=0x0010000000027d62
- (void)didSelectAnonymousEmail:(_Bool)arg1;	// IMP=0x0010000000027d08
- (void)didShowAppleID:(_Bool)arg1;	// IMP=0x0010000000027cae
- (void)setPasswordCredentialCount:(unsigned long long)arg1;	// IMP=0x0010000000027c54
- (id)initWithRequestID:(id)arg1;	// IMP=0x0010000000027b2d

@end

