//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class AKClient;

@interface AKCustodianDaemonService : NSObject
{
    AKClient *_client;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0020000000079f64
@property(readonly, nonatomic) AKClient *client; // @synthesize client=_client;
- (id)_trustedContactOperationsByIDFromArray:(id)arg1;	// IMP=0x0010000000079b35
- (void)performTrustedContactsDataSync:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00100000000790c0
- (_Bool)verifyRecoveryTransactionWithContext:(id)arg1 verifySessionID:(_Bool)arg2 error:(id *)arg3;	// IMP=0x0010000000078d27
- (void)sendEmbargoEndNotificationFeedbackWithContext:(id)arg1 urlKey:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00100000000787b3
- (void)fetchCustodianDataRecoveryKeyWithContext:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000007822f
- (void)fetchCustodianRecoveryTokenWithContext:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000077a61
- (void)startCustodianRecoveryTransactionWithContext:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00100000000776bc
- (void)fetchCustodianRecoveryCodeConfigurationWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00100000000775aa
- (void)startCustodianRecoveryRequestWithContext:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00100000000770a3
- (void)updateCustodianRecoveryKeyWithContext:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000076bdd
- (void)revokeCustodianWithContext:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00100000000766eb
- (void)finalizeCustodianSetupWithContext:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00100000000761f9
- (void)initiateCustodianSetupWithContext:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000075c3d
- (void)dealloc;	// IMP=0x0010000000075bd1
- (id)initWithClient:(id)arg1;	// IMP=0x0010000000075b66
- (id);	// IMP=0x0010000000075b3b

@end

