//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;
@protocol AKSQLiteMigration;

@interface AKSQLiteExecutor : NSObject
{
    struct sqlite3 *_database;	// 8 = 0x8
    NSString *_databasePath;	// 16 = 0x10
    _Bool _shouldAutomaticallyMigrate;	// 24 = 0x18
    id <AKSQLiteMigration> _migrator;	// 32 = 0x20
}

+ (id)_databaseQueue;	// IMP=0x0040000000073bfe
+ (void)performBlockAndWait:(CDUnknownBlockType)arg1;	// IMP=0x0010000000073b14
+ (void)performBlock:(CDUnknownBlockType)arg1;	// IMP=0x0010000000073a2b
- (void).cxx_destruct;	// IMP=0x0020000000075120
@property(retain, nonatomic) id <AKSQLiteMigration> migrator; // @synthesize migrator=_migrator;
- (void)setShouldAutomaticallyMigrate:(_Bool)arg1;	// IMP=0x00100000000750fc
- (_Bool)shouldAutomaticallyMigrate;	// IMP=0x00100000000750f3
- (void)_unsafe_closeDatabase;	// IMP=0x0010000000075021
- (void)closeDatabase;	// IMP=0x0010000000074fb5
- (void)_unsafe_wipeDatabase:(id *)arg1;	// IMP=0x0010000000074ea7
- (void)wipeDatabase:(id *)arg1;	// IMP=0x0010000000074d2b
- (int)_unsafe_createDataBase;	// IMP=0x0010000000074b23
- (_Bool)_unsafe_openDatabase:(id *)arg1;	// IMP=0x0010000000074933
- (_Bool)openDatabase:(id *)arg1;	// IMP=0x0010000000074771
- (id)_currentDataBaseError;	// IMP=0x0010000000074609
- (_Bool)_handleDatabaseFailureError:(id *)arg1;	// IMP=0x0010000000074478
- (_Bool)_finalizeStatement:(struct sqlite3_stmt *)arg1 error:(id *)arg2;	// IMP=0x00100000000743f1
- (struct sqlite3_stmt *)_prepareStatementForQuery:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000074348
- (void)_stepThroughRowsWithQuery:(id)arg1 statement:(struct sqlite3_stmt *)arg2;	// IMP=0x0010000000074295
- (void)_printStatement:(struct sqlite3_stmt *)arg1;	// IMP=0x001000000007423a
- (long long)performInsertQuery:(id)arg1 error:(id *)arg2;	// IMP=0x00100000000740fa
- (_Bool)performQuery:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000073fa5
- (_Bool)performQuery:(id)arg1 rowHandler:(CDUnknownBlockType)arg2;	// IMP=0x0010000000073eb6
- (_Bool)performQuery:(id)arg1;	// IMP=0x0010000000073ea2
- (long long)performInsertQuery:(id)arg1;	// IMP=0x0010000000073e46
- (int)_executeQuery:(id)arg1;	// IMP=0x0010000000073d46
- (void)rollbackTransaction;	// IMP=0x0010000000073d2d
- (void)commitTransaction;	// IMP=0x0010000000073cef
- (void)openTransaction;	// IMP=0x0010000000073cd6
- (void)performTransactionBlockAndWait:(CDUnknownBlockType)arg1;	// IMP=0x0010000000073c7f
@property(readonly, nonatomic) NSString *databasePath;
@property(readonly, nonatomic) struct sqlite3 *database;
- (id)initWithDatabasePath:(id)arg1 migrationController:(id)arg2;	// IMP=0x0010000000073987

@end

