//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class AKAppleIDAuthenticationContext, NSString;

@interface AKSRPAuthenticationContextHelper
{
    NSString *_passwordResetBackupToken;	// 8 = 0x8
    _Bool __masterKeyAsSecondFactor;	// 16 = 0x10
    AKAppleIDAuthenticationContext *_authContext;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x002000000001c7dd
@property(nonatomic, setter=_setMasterKeyAsSecondFactor:) _Bool _masterKeyAsSecondFactor; // @synthesize _masterKeyAsSecondFactor=__masterKeyAsSecondFactor;
@property(retain, nonatomic) AKAppleIDAuthenticationContext *authContext; // @synthesize authContext=_authContext;
- (id)_identityAuthorizationPayload;	// IMP=0x001000000001c607
- (id)_passwordResetBackupToken;	// IMP=0x001000000001c53d
- (_Bool)canPresentRemoteUI;	// IMP=0x001000000001c4bd
- (void)clientProvidedDataHelper:(id)arg1;	// IMP=0x001000000001bd74
- (void)_authenticationParameters:(CDUnknownBlockType)arg1;	// IMP=0x001000000001a7f1
- (void)authenticationParametersWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x001000000001a31d
- (id)initWithContext:(id)arg1;	// IMP=0x001000000001a2ac

@end

