//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;
@protocol NTTodayContext, OS_dispatch_queue;

@interface NDTodayClientConnection : NSObject
{
    id <NTTodayContext> _todayContext;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_accessQueue;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x00200000000028eb
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *accessQueue; // @synthesize accessQueue=_accessQueue;
@property(readonly, nonatomic) id <NTTodayContext> todayContext; // @synthesize todayContext=_todayContext;
- (void)markAnalyticsElement:(id)arg1 asReadAtDate:(id)arg2 withCompletion:(CDUnknownBlockType)arg3;	// IMP=0x00100000000026b5
- (void)markAnalyticsElements:(id)arg1 asSeenAtDate:(id)arg2 withCompletion:(CDUnknownBlockType)arg3;	// IMP=0x0010000000002415
- (void)fetchPlaceholderResultsWithOperationInfo:(id)arg1 syncCompletion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000002329
- (void)fetchLatestResultsWithParameters:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000002140
- (void)fetchModuleDescriptorsWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0010000000002029
- (id)initWithClient:(id)arg1 contentContext:(id)arg2 fetchQueue:(id)arg3;	// IMP=0x0010000000001cb3
- (id)init;	// IMP=0x0010000000001b6e

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

