//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <IDS/IDSService.h>

@interface ADIDSSimulatorService : IDSService
{
}

- (id)accounts;	// IMP=0x00400000001e7fa9
- (id)devices;	// IMP=0x00100000001e7f28

@end

