//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSString;

@interface ADOTTRequestTransformer : NSObject
{
}

- (MISSING_TYPE *)getSiriRequestForClientBoundAceCommand:completionHandler: /* Error: Ran out of types for this method. */;	// IMP=0x002000000025fcb0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

