//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class ADPeerStreamConnection, IDSDeviceConnection, IDSService, MISSING_TYPE, NSDictionary, NSHashTable, NSMutableDictionary, NSMutableSet, NSString;
@protocol OS_dispatch_queue;

@interface ADSharedPeerStreamConnection : NSObject
{
    _Bool _listener;	// 8 = 0x8
    NSHashTable *_delegates;	// 16 = 0x10
    NSString *_identifier;	// 24 = 0x18
    NSObject<OS_dispatch_queue> *_queue;	// 32 = 0x20
    IDSService *_idsService;	// 40 = 0x28
    ADPeerStreamConnection *_currentPeerStreamConnection;	// 48 = 0x30
    NSMutableDictionary *_metricsResponses;	// 56 = 0x38
    NSString *_wakeupMessageIdentifier;	// 64 = 0x40
    NSString *_currentStreamIdentifier;	// 72 = 0x48
    _Bool _gettingDeviceSocket;	// 80 = 0x50
    _Bool _socketForConnectionHasBeenVended;	// 81 = 0x51
    IDSDeviceConnection *_deviceConnection;	// 88 = 0x58
    int _sockfd;	// 96 = 0x60
    CDUnknownBlockType _socketCompletion;	// 104 = 0x68
    _Bool _prefersBTClassic;	// 112 = 0x70
    NSString *_productType;	// 120 = 0x78
    NSString *_buildVersion;	// 128 = 0x80
    _Bool _peerSupportsNamedStreams;	// 136 = 0x88
    NSMutableSet *_nearbyDeviceIdentifiers;	// 144 = 0x90
    double _lastSharedDataUpdateTimestamp;	// 152 = 0x98
    _Bool _optimisticRetriesAreBlocked;	// 160 = 0xa0
    _Bool _peerSupportsExtendedHeader;	// 161 = 0xa1
    double _lastNearbyDevicesChangedTimestamp;	// 168 = 0xa8
    double _lastIDSMessageSentTimestamp;	// 176 = 0xb0
    double _lastIDSMessageStartSendTimestamp;	// 184 = 0xb8
    double _lastWakeUpMessageDuration;	// 192 = 0xc0
    double _lastStreamEstablishmentDuration;	// 200 = 0xc8
    unsigned long long _lastOpenErrorCode;	// 208 = 0xd0
    NSDictionary *_lastIDSMetricsContext;	// 216 = 0xd8
    _Bool _lastIDSMessageSuccess;	// 224 = 0xe0
}

+ (id)sharedPeerStreamConnectionWithServiceIdentifier:(id)arg1 listener:(_Bool)arg2;	// IMP=0x002000000008c556
+ (id)_streamPairInterruptedError;	// IMP=0x001000000008c0b7
+ (id)_deviceConnectionClosedErrorWithUnderlyingError:(id)arg1;	// IMP=0x001000000008c09d
+ (MISSING_TYPE *)_noDeviceError;	// IMP=0x001000000008c087
+ (id)_noNearbyPeerError;	// IMP=0x001000000008c06e
+ (id)_errorWithCode:(long long)arg1 underylingError:(id)arg2;	// IMP=0x001000000008bf8c
- (void).cxx_destruct;	// IMP=0x0020000000090bea
- (_Bool)deviceIsNearby;	// IMP=0x0010000000090ba6
- (void)preheat;	// IMP=0x0010000000090b45
- (void)_preheat;	// IMP=0x0010000000090ad9
- (_Bool)peerSupportsExtendedHeader;	// IMP=0x0010000000090acd
- (void)service:(id)arg1 devicesChanged:(id)arg2;	// IMP=0x00100000000909fe
- (void)service:(id)arg1 nearbyDevicesChanged:(id)arg2;	// IMP=0x00100000000904f1
- (void)_establishEagerStreamPair;	// IMP=0x001000000009042b
- (void)service:(id)arg1 account:(id)arg2 identifier:(id)arg3 didSendWithSuccess:(_Bool)arg4 error:(id)arg5 context:(id)arg6;	// IMP=0x001000000009018c
- (void)_handleResponseProtobuf:(id)arg1 forIdentifier:(id)arg2;	// IMP=0x001000000009002a
- (void)_handleReestablishMessage:(id)arg1 context:(id)arg2;	// IMP=0x001000000008fea6
- (void)_handleGetMetricsMessage:(id)arg1 context:(id)arg2;	// IMP=0x001000000008fa8f
- (void)_handleWakeUpMessage:(id)arg1 context:(id)arg2;	// IMP=0x001000000008f6e6
- (void)service:(id)arg1 account:(id)arg2 incomingUnhandledProtobuf:(id)arg3 fromID:(id)arg4 context:(id)arg5;	// IMP=0x001000000008f4df
- (void)_updatePairedDeviceInfo;	// IMP=0x001000000008f2b4
- (void)getMetricsContext:(CDUnknownBlockType)arg1;	// IMP=0x001000000008f1c4
- (id)_failureMetricsContextDictionary;	// IMP=0x001000000008ece4
- (void)_setPreferBTClassic:(_Bool)arg1;	// IMP=0x001000000008eb5f
- (void)setPreferBTClassic:(_Bool)arg1;	// IMP=0x001000000008eaf4
- (_Bool)hasNearbyPeer;	// IMP=0x001000000008ea0e
- (void)_requestStreamEstablishment;	// IMP=0x001000000008e717
- (void)_invokeMetricsCompletionWithMetrics:(id)arg1 forIdentifier:(id)arg2;	// IMP=0x001000000008e689
- (void)getAWDMetrics:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000008e584
- (void)getRemoteMetrics:(CDUnknownBlockType)arg1;	// IMP=0x001000000008e04a
- (void)_close;	// IMP=0x001000000008df78
- (void)closeForConnection:(id)arg1;	// IMP=0x001000000008dd49
- (void)_invokeSocketCompletionWithCurrentSocketOrError:(id)arg1;	// IMP=0x001000000008dc26
- (void)_getSocketFromDeviceForStreamIdentifier:(id)arg1;	// IMP=0x001000000008d3db
- (void)_getSocketFromDevice;	// IMP=0x001000000008d370
- (void)getSocketForConnection:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000008d0dd
- (void)_initiateOptimisticEagerStreamFetchRetry;	// IMP=0x001000000008cf56
- (void)_wakeUpMessageFailedWithError:(id)arg1;	// IMP=0x001000000008ccbb
- (_Bool)_wakeUpRemoteForStreamIdentifier:(id)arg1;	// IMP=0x001000000008c980
- (void)removeDelegate:(id)arg1;	// IMP=0x001000000008c8d7
- (void)addDelegate:(id)arg1;	// IMP=0x001000000008c7eb
- (id)_destination;	// IMP=0x001000000008c4ff
- (id)_account;	// IMP=0x001000000008c4ab
- (id)_pairedDevice;	// IMP=0x001000000008c32e
- (id)_service;	// IMP=0x001000000008c320
- (id)_initWithServiceIdentifier:(id)arg1 listener:(_Bool)arg2;	// IMP=0x001000000008c0d0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

