//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <SAObjects/SAResultSelected.h>

@interface SAResultSelected (ResultCallbacks)
- (long long)resultCallbackCode;	// IMP=0x00100000001ae64f
- (_Bool)ad_sendReplyEvenIfCallbacksExist;	// IMP=0x00100000001ae657
@end

