//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class BABlockQueue, NSObject, NSString, NSUUID;
@protocol OS_dispatch_queue;

@interface BAAgentClientConnection
{
    _Bool _isApplication;	// 8 = 0x8
    _Bool _isActive;	// 9 = 0x9
    _Bool _connectionIsValid;	// 10 = 0xa
    NSString *_clientIdentifier;	// 16 = 0x10
    NSObject<OS_dispatch_queue> *_clientHandlerQueue;	// 24 = 0x18
    NSObject<OS_dispatch_queue> *_clientWorkQueue;	// 32 = 0x20
    NSString *_signingIdentifier;	// 40 = 0x28
    BABlockQueue *_exclusiveAccessBlockQueue;	// 48 = 0x30
    NSUUID *_lastExclusiveAccessBlockToken;	// 56 = 0x38
}

- (void).cxx_destruct;	// IMP=0x00200000000268ac
@property(retain) NSUUID *lastExclusiveAccessBlockToken; // @synthesize lastExclusiveAccessBlockToken=_lastExclusiveAccessBlockToken;
@property(retain) BABlockQueue *exclusiveAccessBlockQueue; // @synthesize exclusiveAccessBlockQueue=_exclusiveAccessBlockQueue;
@property(retain) NSString *signingIdentifier; // @synthesize signingIdentifier=_signingIdentifier;
@property _Bool connectionIsValid; // @synthesize connectionIsValid=_connectionIsValid;
@property _Bool isActive; // @synthesize isActive=_isActive;
@property(retain) NSObject<OS_dispatch_queue> *clientWorkQueue; // @synthesize clientWorkQueue=_clientWorkQueue;
@property(retain) NSObject<OS_dispatch_queue> *clientHandlerQueue; // @synthesize clientHandlerQueue=_clientHandlerQueue;
@property(retain) NSString *clientIdentifier; // @synthesize clientIdentifier=_clientIdentifier;
@property _Bool isApplication; // @synthesize isApplication=_isApplication;
@property(readonly, copy) NSString *debugDescription;
- (id)extendClientSandboxForStagedURL:(id)arg1;	// IMP=0x00100000000265a1
- (void)downloadIdentifierDidFinish:(id)arg1 clientStagedURL:(id)arg2 sandboxExtensionToken:(id)arg3 wasHandled:(CDUnknownBlockType)arg4;	// IMP=0x0010000000026468
- (void)downloadIdentifier:(id)arg1 didFailWithError:(id)arg2 wasHandled:(CDUnknownBlockType)arg3;	// IMP=0x001000000002634e
- (void)downloadIdentifier:(id)arg1 didReceiveChallenge:(id)arg2 authChallengeHandler:(CDUnknownBlockType)arg3 withCompletion:(CDUnknownBlockType)arg4;	// IMP=0x0010000000026018
- (void)downloadIdentifier:(id)arg1 didWriteBytes:(long long)arg2 totalBytesWritten:(long long)arg3 totalBytesExpectedToWrite:(long long)arg4;	// IMP=0x0010000000025f6f
- (void)downloadIdentifierDidPause:(id)arg1;	// IMP=0x0010000000025edf
- (void)downloadIdentifierDidBegin:(id)arg1;	// IMP=0x0010000000025e4f
- (void)removeDownloadIdentifier:(id)arg1;	// IMP=0x0010000000025dbf
- (void)callBlockWhenConnectionReady:(CDUnknownBlockType)arg1 onQueue:(id)arg2;	// IMP=0x0010000000025c3c
- (void)syncDownloads:(id)arg1;	// IMP=0x0010000000025bac
- (void)applicationStateDidChange:(long long)arg1;	// IMP=0x0010000000025a57
- (void)cancelDownload:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x00100000000257f8
- (void)startForegroundDownload:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x00100000000255b2
- (_Bool)_entitledForCloudKitWithDownload:(id)arg1 outError:(id *)arg2;	// IMP=0x0010000000025055
- (void)_validateAndSetClientIdentifier;	// IMP=0x00100000000243bf
- (void)exclusiveControlExitedWithToken:(id)arg1;	// IMP=0x0010000000024260
- (void)performWithExclusiveControlBeforeDate:(id)arg1 handler:(CDUnknownBlockType)arg2;	// IMP=0x0010000000023faa
- (void)performWithExclusiveControlWithHandler:(CDUnknownBlockType)arg1;	// IMP=0x0010000000023cf6
- (void)scheduleDownload:(id)arg1 reply:(CDUnknownBlockType)arg2;	// IMP=0x001000000002399d
- (void)currentDownloads:(CDUnknownBlockType)arg1;	// IMP=0x00100000000237e5
- (void)dealloc;	// IMP=0x0010000000023740
- (void)connectionInvalidated;	// IMP=0x00100000000235f9
- (id)initWithNSXPCConnection:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000022683

// Remaining properties
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

