//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC9Reminders25TTRIRemindersListDragItem : NSObject
{
    MISSING_TYPE *reminder;	// 8 = 0x8
    MISSING_TYPE *$__lazy_storage_$_hasSubtasks;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x00400000003ec920
- (id)init;	// IMP=0x00100000003ec8c0

@end

