//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UISplitViewController.h>

@class UIViewController;

@interface TTRISplitViewController : UISplitViewController
{
}

- (void)setupColumnStyle_workaroundRdar58463688;	// IMP=0x0020000000008c70
@property(readonly, nonatomic) UIViewController *detailViewController;

@end

