//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSArray, NSString;
@protocol APExpressionNodeProtocol;

@protocol APExpressionNodeProtocol
@property(nonatomic) __weak id <APExpressionNodeProtocol> parent;
@property(readonly, nonatomic) NSArray *children;
@property(readonly, nonatomic) NSString *identifier;
@end

