//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class MISSING_TYPE, NSDictionary, NSNumber, NSString;

@interface APIDAccountsSettings
{
}

+ (MISSING_TYPE *)storageWithDefaultValues: /* Error: Ran out of types for this method. */;	// IMP=0x004000000002a32f
+ (id)defaultValues;	// IMP=0x0010000000029ee7

// Remaining properties
@property(readonly, nonatomic) NSDictionary *IDAccountsRecord; // @dynamic IDAccountsRecord;
@property(readonly, nonatomic) NSNumber *monthlyIDResetCount; // @dynamic monthlyIDResetCount;
@property(readonly, nonatomic) NSString *storefront; // @dynamic storefront;

@end

