//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/NSString.h>

@interface NSString (LeadingCase)
- (id)stringByUppercasingFirstLetter;	// IMP=0x00100000000cd853
- (id)stringByLowercasingFirstLetter;	// IMP=0x00100000000cd83c
- (id)_lowercaseFirstLetterOfString:(_Bool)arg1;	// IMP=0x00100000000cd741
- (id)lastNamespacedComponent;	// IMP=0x00100000000f6c71
@end

