//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class NSDictionary, VSRecognitionResult;

@protocol VSRecognitionResultValidator <NSObject>
- (VSRecognitionResult *)validRecognitionResultFromRecognitionResult:(VSRecognitionResult *)arg1;

@optional
- (VSRecognitionResult *)validRecognitionResultFromRecognitionResult:(VSRecognitionResult *)arg1 knownDisambiguationValues:(NSDictionary *)arg2;
@end

