//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC13callservicesd20CompanionLinkManager : _TtCs12_SwiftObject
{
    MISSING_TYPE *queue;	// 16 = 0x10
    MISSING_TYPE *client;	// 24 = 0x18
    MISSING_TYPE *authenticationController;	// 32 = 0x20
    MISSING_TYPE *activated;	// 40 = 0x28
    MISSING_TYPE *deviceUpdatedPublisher;	// 48 = 0x30
    MISSING_TYPE *deviceFoundPublisher;	// 56 = 0x38
    MISSING_TYPE *deviceLostPublisher;	// 64 = 0x40
    MISSING_TYPE *deviceChangedPublisher;	// 72 = 0x48
    MISSING_TYPE *cancellables;	// 80 = 0x50
    MISSING_TYPE *stateHandle;	// 88 = 0x58
    MISSING_TYPE *messagePublishers;	// 96 = 0x60
    MISSING_TYPE *eventPublishers;	// 104 = 0x68
}

@end

