//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <AVConference/AVCSessionParticipant.h>

@interface AVCSessionParticipant (CSD)
@property(readonly, nonatomic) long long captionsToken;
@end

