//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <CallHistory/CHHandle.h>

@class TUHandle;

@interface CHHandle (CSD)
+ (id)handleWithTUHandle:(id)arg1;	// IMP=0x00200000001a7845
+ (long long)handleTypeForTUHandle:(id)arg1;	// IMP=0x00100000001a77fa
@property(readonly, nonatomic) TUHandle *tuHandle;
@end

