//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class NSString;

@protocol CSDAVCMomentsRequest <NSObject>
- (_Bool)rejectWithError:(id *)arg1;
- (_Bool)endWithError:(id *)arg1;
- (_Bool)startWithError:(id *)arg1;
@property(nonatomic, readonly) NSString *requesteeID;
@property(nonatomic, readonly) NSString *requesterID;
@property(nonatomic, readonly) unsigned char mediaType;
@property(nonatomic, readonly) NSString *transactionID;
@end

