//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;
@protocol CSDCallCenterObserverDelegate, CSDCallContainer;

@interface CSDCallCenterObserver : NSObject
{
    MISSING_TYPE *callContainerClosure;	// 8 = 0x8
    MISSING_TYPE *notificationCenter;	// 24 = 0x18
    MISSING_TYPE *delegate;	// 32 = 0x20
    MISSING_TYPE *triggers;	// 40 = 0x28
    MISSING_TYPE *callChanged;	// 48 = 0x30
}

- (void).cxx_destruct;	// IMP=0x00400000001fb4c0
- (void)handleSharePlayTrigger:(id)arg1;	// IMP=0x00100000001fb3d0
- (void)handleTrigger:(id)arg1;	// IMP=0x00100000001fa9b0
- (id)init;	// IMP=0x00100000001fa1c0
@property(nonatomic, readonly) id <CSDCallContainer> callContainer;
@property(nonatomic, copy) CDUnknownBlockType callChanged;
@property(nonatomic) unsigned long long triggers; // @synthesize triggers;
@property(nonatomic) __weak id <CSDCallCenterObserverDelegate> delegate; // @synthesize delegate;
- (id)activeConversationForCall:(id)arg1;	// IMP=0x00100000001f9af0

@end

