//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class CSDSharedConversationServerBag, NSMutableDictionary;
@protocol TUFeatureFlags;

@interface CSDConversationProviderManager : NSObject
{
    struct os_unfair_lock_s _accessorLock;	// 8 = 0x8
    CDUnknownBlockType _beginListeningBlock;	// 16 = 0x10
    NSMutableDictionary *_providerIdentifierToProvider;	// 24 = 0x18
    NSMutableDictionary *_pidToProviderIdentifiers;	// 32 = 0x20
    NSMutableDictionary *_pidToProcessHandle;	// 40 = 0x28
    id <TUFeatureFlags> _featureFlags;	// 48 = 0x30
    CSDSharedConversationServerBag *_serverBag;	// 56 = 0x38
}

+ (id)errorForDisabledPseudonyms;	// IMP=0x002000000019f268
+ (id)errorForUnregisteredProviderIdentifier:(id)arg1;	// IMP=0x001000000019f17b
+ (id)sharedInstance;	// IMP=0x001000000019dd70
- (void).cxx_destruct;	// IMP=0x002000000019f681
@property(retain, nonatomic) CSDSharedConversationServerBag *serverBag; // @synthesize serverBag=_serverBag;
@property(retain, nonatomic) id <TUFeatureFlags> featureFlags; // @synthesize featureFlags=_featureFlags;
@property(readonly, nonatomic) struct os_unfair_lock_s accessorLock; // @synthesize accessorLock=_accessorLock;
@property(readonly, nonatomic) NSMutableDictionary *pidToProcessHandle; // @synthesize pidToProcessHandle=_pidToProcessHandle;
@property(readonly, nonatomic) NSMutableDictionary *pidToProviderIdentifiers; // @synthesize pidToProviderIdentifiers=_pidToProviderIdentifiers;
@property(readonly, nonatomic) NSMutableDictionary *providerIdentifierToProvider; // @synthesize providerIdentifierToProvider=_providerIdentifierToProvider;
@property(copy, nonatomic) CDUnknownBlockType beginListeningBlock; // @synthesize beginListeningBlock=_beginListeningBlock;
- (void)createProcessMonitorIfNecessary:(id)arg1 forClient:(id)arg2;	// IMP=0x001000000019f326
- (id)serviceForProvider:(id)arg1;	// IMP=0x001000000019eea7
- (void)doesHandle:(id)arg1 correspondToConversationProvider:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x001000000019ecb7
- (void)revokePseudonymHandle:(id)arg1 forConversationProvider:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x001000000019eb33
- (void)renewPseudonymHandle:(id)arg1 forConversationProvider:(id)arg2 expirationDate:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;	// IMP=0x001000000019e988
- (void)generatePseudonymHandleForConversationProvider:(id)arg1 expiryDuration:(double)arg2 URI:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;	// IMP=0x001000000019e721
- (id)tuConversationProviderForIdentifier:(id)arg1;	// IMP=0x001000000019e682
- (id)conversationProviderForIdentifier:(id)arg1;	// IMP=0x001000000019e5dc
- (void)registerConversationProvider:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;	// IMP=0x001000000019e24a
- (id)providerIdentifiersForClient:(id)arg1;	// IMP=0x001000000019e11c
- (_Bool)startTrackingClient:(id)arg1 forProviderIdentifier:(id)arg2;	// IMP=0x001000000019deba
- (id)init;	// IMP=0x001000000019ddf5

@end

