//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class CSDConversationManager, IDSMessageContext, NSData, NSDictionary, NSString, NSURL;
@protocol CSDGroupSessionParticipantUpdateProtocol;

@protocol CSDConduitIDSProxy <NSObject>
- (void)proxyGroupUpdate:(id <CSDGroupSessionParticipantUpdateProtocol>)arg1 forConversationManager:(CSDConversationManager *)arg2;
- (_Bool)shouldIgnoreIDSResource:(NSURL *)arg1 metadata:(NSDictionary *)arg2 fromID:(NSString *)arg3 context:(IDSMessageContext *)arg4;
- (_Bool)shouldIgnoreIDSMessage:(NSData *)arg1 fromID:(NSString *)arg2 context:(IDSMessageContext *)arg3;
@end

