//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface CSDParticipantUpdateSanitizerImpl : NSObject
{
    MISSING_TYPE *completionQueue;	// 8 = 0x8
    MISSING_TYPE *vouchingEnablement;	// 16 = 0x10
    MISSING_TYPE *voucherManager;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00400000002da950
- (id)init;	// IMP=0x00100000002da8f0
- (void)sanitize:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x00100000002da870
- (id)initWithVoucherManager:(id)arg1;	// IMP=0x00100000002d9bb0

@end

