//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString, NSXPCListener;

@interface TIKeyboardInputManagerServer : NSObject
{
    NSXPCListener *_listener;	// 8 = 0x8
}

+ (id)sharedKeyboardInputManagerServer;	// IMP=0x00200000000063ce
- (void).cxx_destruct;	// IMP=0x0020000000006da9
- (void)prepareForActivity;	// IMP=0x0010000000006d90
- (void)prepareForInactivity;	// IMP=0x0010000000006cf3
- (void)handleMemoryPressureLevel:(unsigned long long)arg1 excessMemoryInBytes:(unsigned long long)arg2;	// IMP=0x0010000000006cc9
- (void)keyboardActivityDidTransition:(id)arg1;	// IMP=0x0010000000006c5e
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;	// IMP=0x00100000000068d3
- (void)reduceCacheToSize:(unsigned long long)arg1;	// IMP=0x00100000000067e5
- (void)releaseAllInputManagers:(_Bool)arg1;	// IMP=0x0010000000006792
- (void)appleKeyboardsSettingsChanged:(id)arg1;	// IMP=0x00100000000066ed
- (id)init;	// IMP=0x0010000000006520
- (void)dealloc;	// IMP=0x0010000000006453

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

