//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class NSDate, NSString;

@protocol TILinguisticDataSourceMessage <NSObject>
@property(readonly, copy, nonatomic) NSString *body;
@property(readonly, copy, nonatomic) NSString *recipient;
@property(readonly, copy, nonatomic) NSDate *dateSent;

@optional
@property(readonly, nonatomic) _Bool fromMe;
@end

