//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface SPAppUsageTrack : NSObject
{
    unsigned int toGizmo[13];	// 8 = 0x8
    unsigned int toComp[13];	// 60 = 0x3c
}

- (unsigned int *)toCompArray;	// IMP=0x0020000000008ab3
- (unsigned int *)toGizmoArray;	// IMP=0x0010000000008aa9
- (void)incToComp:(int)arg1;	// IMP=0x0010000000008a9c
- (void)incToGizmo:(int)arg1;	// IMP=0x0010000000008a8f
- (id)init;	// IMP=0x0010000000008a38

@end

