//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtCC19appstorecomponentsd19JSMediaTokensObjectP33_E91800677D5458EF8C488C03D4ACDC6E8CacheKey : NSObject
{
    MISSING_TYPE *client;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0040000000080380
- (id)init;	// IMP=0x0010000000080320
- (_Bool)isEqual:(id)arg1;	// IMP=0x0010000000080290
@property(nonatomic, readonly) long long hash;

@end

