//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class NSNumber, NSString;

@protocol PBFComplicationLookupInfo <NSObject>
@property(nonatomic, readonly) NSString *complicationWidgetKind;
@property(nonatomic, readonly) NSString *complicationContainingBundleIdentifier;
@property(nonatomic, readonly) NSString *complicationExtensionBundleIdentifier;
@property(nonatomic, readonly) NSNumber *complicationWidgetFamily;
@end

