//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface MapsSuggestionsCurrentWeatherConditionsProvider
{
}

- (_Bool)requestWeatherAtLocation:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x004000000002fdfc
- (void)didUpdateWeatherConditions:(id)arg1;	// IMP=0x001000000002fcb2

@end

