//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class MapsSuggestionsMutableSignalPack, MapsSuggestionsWallet, NSString;
@protocol MapsSuggestionsFeelerDelegate;

@interface MapsSuggestionsWalletFeeler
{
    struct Queue _queue;	// 8 = 0x8
    MapsSuggestionsWallet *_wallet;	// 24 = 0x18
    MapsSuggestionsMutableSignalPack *_signalPack;	// 32 = 0x20
    double _pollingFrequency;	// 40 = 0x28
}

+ (_Bool)isEnabled;	// IMP=0x002000000000f4c8
- (id).cxx_construct;	// IMP=0x0020000000010207
- (void).cxx_destruct;	// IMP=0x00100000000101af
- (double)updateSignals;	// IMP=0x001000000000f4f9
- (_Bool)canProduceSignalType:(long long)arg1;	// IMP=0x001000000000f4df
- (id)initWithDelegate:(id)arg1 wallet:(id)arg2;	// IMP=0x001000000000f404
- (id)initWithDelegate:(id)arg1 wallet:(id)arg2 name:(id)arg3;	// IMP=0x001000000000f244

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(nonatomic) __weak id <MapsSuggestionsFeelerDelegate> delegate;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(readonly, nonatomic) NSString *uniqueName;

@end

