//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MapsSuggestionsMutableSignalPack, NSMutableArray, NSMutableDictionary, NSString;
@protocol MapsSuggestionsNetworkRequester, MapsSuggestionsSignalAlgorithm, OS_dispatch_source;

@interface MapsSuggestionsSignalPipeline : NSObject
{
    struct Queue _queue;	// 8 = 0x8
    MapsSuggestionsMutableSignalPack *_generalSignalPack;	// 24 = 0x18
    id <MapsSuggestionsSignalAlgorithm> _algorithm;	// 32 = 0x20
    NSMutableArray *_pollingFeelers;	// 40 = 0x28
    NSMutableArray *_streamingFeelers;	// 48 = 0x30
    NSObject<OS_dispatch_source> *_pollTimer;	// 56 = 0x38
    NSMutableDictionary *_nextPollingTimes;	// 64 = 0x40
    id <MapsSuggestionsNetworkRequester> _networkRequester;	// 72 = 0x48
}

- (id).cxx_construct;	// IMP=0x002000000000c739
- (void).cxx_destruct;	// IMP=0x001000000000c6c7
@property(retain, nonatomic) id <MapsSuggestionsNetworkRequester> networkRequester; // @synthesize networkRequester=_networkRequester;
- (_Bool)feeler:(id)arg1 sendsSignalPack:(id)arg2;	// IMP=0x001000000000b38a
- (void)userDidChooseTranportMode:(int)arg1 forMapItem:(id)arg2;	// IMP=0x001000000000b384
- (void)userDidChooseTranportMode:(int)arg1 forEntry:(id)arg2;	// IMP=0x001000000000b37e
- (BOOL)guessTransportModesForDestinationEntry:(id)arg1 originCoordinate:(struct CLLocationCoordinate2D)arg2 handler:(CDUnknownBlockType)arg3;	// IMP=0x001000000000abaa
- (BOOL)guessTransportModesForDestinationMapItem:(id)arg1 originCoordinate:(struct CLLocationCoordinate2D)arg2 handler:(CDUnknownBlockType)arg3;	// IMP=0x001000000000a2a0
- (id)mergedSignalPackForDestinationMapItem:(id)arg1 originCoordinate:(struct CLLocationCoordinate2D)arg2;	// IMP=0x001000000000a01f
- (id)mergedSignalPackForDestinationEntry:(id)arg1 originCoordinate:(struct CLLocationCoordinate2D)arg2;	// IMP=0x0010000000009d9e
- (id)mergedCommonSignalPack;	// IMP=0x0010000000009c2f
- (void)resetData;	// IMP=0x0010000000009a9f
- (_Bool)stop;	// IMP=0x0010000000009916
- (_Bool)start;	// IMP=0x0010000000009639
- (_Bool)setAlgorithm:(id)arg1;	// IMP=0x00100000000094be
- (_Bool)removeFeeler:(id)arg1;	// IMP=0x001000000000920f
- (_Bool)addFeeler:(id)arg1;	// IMP=0x0010000000008dd2
- (void)dealloc;	// IMP=0x0010000000008ba2
- (id)initWithNetworkRequester:(id)arg1;	// IMP=0x0010000000008a16
@property(readonly, nonatomic) NSString *uniqueName;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

