//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class NSError, NSString, PUPeer, PURemoteDeviceState;

@protocol PUPeerDelegate <NSObject>
- (void)peer:(PUPeer *)arg1 wantsNotificationOfNextUnlock:(_Bool)arg2;
- (void)peer:(PUPeer *)arg1 remoteDeviceRequestsRemoteAction:(long long)arg2 type:(long long)arg3 existingPasscode:(NSString *)arg4 showAsReprompt:(_Bool)arg5 completionHandler:(void (^)(PURemoteDeviceState *, NSError *))arg6;
- (void)peer:(PUPeer *)arg1 remoteDeviceRequestsRemoteAction:(long long)arg2 type:(long long)arg3 existingPasscode:(NSString *)arg4 completionHandler:(void (^)(PURemoteDeviceState *, NSError *))arg5;
- (void)peer:(PUPeer *)arg1 didNotifyRemoteState:(PURemoteDeviceState *)arg2 error:(NSError *)arg3;
- (void)peerRemoteDeviceDidUnlock:(PUPeer *)arg1;
- (void)peer:(PUPeer *)arg1 didPairForUnlock:(_Bool)arg2 error:(NSError *)arg3;
@end

