//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface AddShortcutsRowCellModel
{
}

- (_Bool)vibrantBackground;	// IMP=0x0040000000146c8a
- (_Bool)isEqual:(id)arg1;	// IMP=0x0010000000146c43
- (unsigned long long)hash;	// IMP=0x0010000000146bff
- (long long)contentMode;	// IMP=0x0010000000146bf4
- (id)image;	// IMP=0x0010000000146bd4
- (id)title;	// IMP=0x0010000000146b6c
- (id)_maps_diffableDataSourceIdentifier;	// IMP=0x0010000000146b5f

@end

