//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class LocalSearchView, VKVenueFeatureMarker;
@protocol LocalSearchBusinessControllerDelegate;

@interface BrowseVenueBusinessController : NSObject
{
    _Bool _updatingVenueAsync;	// 8 = 0x8
    LocalSearchView *_contentView;	// 16 = 0x10
    id <LocalSearchBusinessControllerDelegate> _delegate;	// 24 = 0x18
    VKVenueFeatureMarker *_venue;	// 32 = 0x20
    double _lastVenueUpdateTimestamp;	// 40 = 0x28
    unsigned long long _lastUpdatedMapType;	// 48 = 0x30
}

- (void).cxx_destruct;	// IMP=0x002000000032fb68
@property(nonatomic) unsigned long long lastUpdatedMapType; // @synthesize lastUpdatedMapType=_lastUpdatedMapType;
@property(nonatomic) _Bool updatingVenueAsync; // @synthesize updatingVenueAsync=_updatingVenueAsync;
@property(nonatomic) double lastVenueUpdateTimestamp; // @synthesize lastVenueUpdateTimestamp=_lastVenueUpdateTimestamp;
@property(retain, nonatomic) VKVenueFeatureMarker *venue; // @synthesize venue=_venue;
@property(readonly, nonatomic) __weak id <LocalSearchBusinessControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) LocalSearchView *contentView; // @synthesize contentView=_contentView;
- (void)captureUserAction:(int)arg1 onTarget:(int)arg2 eventValue:(id)arg3;	// IMP=0x001000000032fa0e
- (void)sendAnalyticsOnBecomeVisibleWithTarget:(int)arg1;	// IMP=0x001000000032f9f2
- (void)sendAnalyticsOnUserActionWithTarget:(int)arg1;	// IMP=0x001000000032f9d6
@property(readonly, nonatomic) _Bool showInCardFooterWhenCardHasExpandedLayout;
- (void)immediatelyHandleVenueWithFocusDidChange:(id)arg1;	// IMP=0x001000000032f875
- (void)handleMapTypeDidChange:(unsigned long long)arg1;	// IMP=0x001000000032f7f6
- (void)handleVenueWithFocusDidChange:(id)arg1;	// IMP=0x001000000032f593
@property(readonly, nonatomic) _Bool shouldBeVisible;
- (_Bool)updateContentViewForVenueAndReturnYESIfChanged;	// IMP=0x001000000032f33c
- (void)viewWillAppear;	// IMP=0x001000000032f32a
- (id)initWithDelegate:(id)arg1;	// IMP=0x000000000032f22d

@end

