//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class CarCompressionTestCardViewController;

@protocol CarCompressionTestCardDelegate
- (void)compressionTestCardRequestsDismiss:(CarCompressionTestCardViewController *)arg1;
- (void)compressionTestCard:(CarCompressionTestCardViewController *)arg1 reloadWithSpacerHeight:(double)arg2 priority:(float)arg3;
@end

