//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMapTable, NSMutableArray;

@interface ContainerStack : NSObject
{
    NSMutableArray *_array;	// 8 = 0x8
    NSMapTable *_content;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x002000000013a19b
- (id)description;	// IMP=0x001000000013a185
- (id)lastState;	// IMP=0x001000000013a11e
- (unsigned long long)count;	// IMP=0x001000000013a108
- (id)allObjects;	// IMP=0x001000000013a0ea
- (id)popFromIndex:(unsigned long long)arg1;	// IMP=0x0010000000139f27
- (id)popAll;	// IMP=0x0010000000139dc1
- (void)replaceLastOne:(id)arg1;	// IMP=0x0010000000139ce1
- (void)removeContaineeState:(id)arg1;	// IMP=0x0010000000139be2
- (void)pushContaineeState:(id)arg1;	// IMP=0x0010000000139b31
- (id)containeeStateForContainee:(id)arg1;	// IMP=0x0010000000139b1b
- (id)containeeStateAtIndex:(unsigned long long)arg1;	// IMP=0x0010000000139a7c
- (unsigned long long)indexOfContainee:(id)arg1;	// IMP=0x0010000000139a66
- (id)init;	// IMP=0x00100000001399cc

@end

