//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@protocol CuratedCollectionsListAnalyticsManager
- (void)curatedCollectionTappedWithMuid:(unsigned long long)arg1 verticalIndex:(unsigned long long)arg2 isCollectionSaved:(_Bool)arg3;
@end

