//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UITableViewController.h>

@class NSString, UITextField;

@interface CustomServiceURLDebugController : UITableViewController
{
    UITextField *_textField;	// 8 = 0x8
    CDStruct_8ce276cf _defaultsKey;	// 16 = 0x10
    NSString *_defaultURLString;	// 32 = 0x20
    CDUnknownBlockType _callback;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x00200000005ae2f3
@property(copy, nonatomic) NSString *defaultURLString; // @synthesize defaultURLString=_defaultURLString;
@property(copy, nonatomic) CDUnknownBlockType callback; // @synthesize callback=_callback;
@property(nonatomic) CDStruct_8ce276cf defaultsKey; // @synthesize defaultsKey=_defaultsKey;
- (_Bool)textFieldShouldReturn:(id)arg1;	// IMP=0x00100000005ae238
- (void)textFieldDidEndEditing:(id)arg1;	// IMP=0x00100000005ae125
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;	// IMP=0x00100000005ae108
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x00100000005ade2d
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;	// IMP=0x00100000005ade22
- (long long)numberOfSectionsInTableView:(id)arg1;	// IMP=0x00100000005ade17
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x00100000005addd7
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x00100000005add84
- (void)dealloc;	// IMP=0x00100000005add39
- (id)initWithStyle:(long long)arg1;	// IMP=0x00100000005adbf8
- (id)title;	// IMP=0x00100000005adbeb

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

