//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UITableViewController.h>

@class NSString, UITextView;
@protocol ExtensionTextInputViewControllerDelegate;

@interface ExtensionTextInputViewController : UITableViewController
{
    id <ExtensionTextInputViewControllerDelegate> _inputDelegate;	// 8 = 0x8
    NSString *_titleText;	// 16 = 0x10
    NSString *_placeholderText;	// 24 = 0x18
    NSString *_initializedText;	// 32 = 0x20
    UITextView *_textView;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x00200000000db17a
@property(retain, nonatomic) UITextView *textView; // @synthesize textView=_textView;
@property(retain, nonatomic) NSString *initializedText; // @synthesize initializedText=_initializedText;
@property(retain, nonatomic) NSString *placeholderText; // @synthesize placeholderText=_placeholderText;
@property(retain, nonatomic) NSString *titleText; // @synthesize titleText=_titleText;
@property(nonatomic) __weak id <ExtensionTextInputViewControllerDelegate> inputDelegate; // @synthesize inputDelegate=_inputDelegate;
@property(readonly, nonatomic) NSString *text;
- (void)doneButtonTapped:(id)arg1;	// IMP=0x00100000000db01d
- (void)configureTextView;	// IMP=0x00100000000dad9b
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;	// IMP=0x00100000000dacd1
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;	// IMP=0x00100000000dacc6
- (long long)numberOfSectionsInTableView:(id)arg1;	// IMP=0x00100000000dacbb
- (double)tableView:(id)arg1 estimatedHeightForRowAtIndexPath:(id)arg2;	// IMP=0x00100000000dacad
- (void)configureTableView;	// IMP=0x00100000000dab38
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x00100000000daac7
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x00100000000daa5d
- (void)viewDidLoad;	// IMP=0x00100000000daa1c
- (id)initWithTitle:(id)arg1 placeholderText:(id)arg2 text:(id)arg3;	// IMP=0x00100000000da92b

@end

