//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class FeatureDiscoveryView;

@interface FeatureDiscoveryCollectionViewCell
{
    FeatureDiscoveryView *_featureDiscoveryView;	// 8 = 0x8
}

+ (double)estimatedHeight;	// IMP=0x0040000000a1fead
- (void).cxx_destruct;	// IMP=0x0020000000a20263
@property(readonly, nonatomic) FeatureDiscoveryView *featureDiscoveryView; // @synthesize featureDiscoveryView=_featureDiscoveryView;
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0010000000a1ff5f

@end

