//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <GeoServices/GEOPlaceCollection.h>

@interface GEOPlaceCollection (LinkPresentationExtras)
- (id)joeColorImage;	// IMP=0x00100000005864f0
@end

