//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class CollectionsFilterSizeController, MKPlaceCollectionsSizeController, MKPlaceCompactCollectionSizeController, NSString, NSUUID;

@interface GuidesHomeSection : NSObject
{
    long long _kind;	// 8 = 0x8
    NSUUID *_sectionIdentifier;	// 16 = 0x10
    NSString *_sectionTitle;	// 24 = 0x18
    NSString *_actionButtonTitle;	// 32 = 0x20
    CDUnknownBlockType _actionHandler;	// 40 = 0x28
    long long _contentType;	// 48 = 0x30
    MKPlaceCollectionsSizeController *_collectionsSizeController;	// 56 = 0x38
    MKPlaceCompactCollectionSizeController *_compactCollectionsSizeController;	// 64 = 0x40
    CollectionsFilterSizeController *_filtersSizeController;	// 72 = 0x48
    unsigned long long _count;	// 80 = 0x50
    double _maxWidth;	// 88 = 0x58
    CDStruct_9f748a59 _configuration;	// 96 = 0x60
}

+ (double)loadingSectionHeight;	// IMP=0x00200000009c707f
- (void).cxx_destruct;	// IMP=0x00200000009c7ba8
@property(nonatomic) double maxWidth; // @synthesize maxWidth=_maxWidth;
@property(nonatomic) unsigned long long count; // @synthesize count=_count;
@property(retain, nonatomic) CollectionsFilterSizeController *filtersSizeController; // @synthesize filtersSizeController=_filtersSizeController;
@property(retain, nonatomic) MKPlaceCompactCollectionSizeController *compactCollectionsSizeController; // @synthesize compactCollectionsSizeController=_compactCollectionsSizeController;
@property(retain, nonatomic) MKPlaceCollectionsSizeController *collectionsSizeController; // @synthesize collectionsSizeController=_collectionsSizeController;
@property(nonatomic) long long contentType; // @synthesize contentType=_contentType;
@property(copy, nonatomic) CDUnknownBlockType actionHandler; // @synthesize actionHandler=_actionHandler;
@property(retain, nonatomic) NSString *actionButtonTitle; // @synthesize actionButtonTitle=_actionButtonTitle;
@property(retain, nonatomic) NSString *sectionTitle; // @synthesize sectionTitle=_sectionTitle;
@property(readonly, nonatomic) NSUUID *sectionIdentifier; // @synthesize sectionIdentifier=_sectionIdentifier;
@property(nonatomic) CDStruct_f6ae2b44 configuration; // @synthesize configuration=_configuration;
@property(readonly, nonatomic) long long kind; // @synthesize kind=_kind;
- (id)description;	// IMP=0x00100000009c79a1
- (id)layoutForCollectionsListSectionUsingLayoutEnvironment:(id)arg1 shouldAddSupplementaryHeaderView:(_Bool)arg2 objectsCount:(unsigned long long)arg3;	// IMP=0x00100000009c798f
- (id)layoutForFilterSectionUsingViewModels:(id)arg1 traitsEnvironment:(id)arg2 width:(double)arg3 shouldAddSupplementaryHeaderView:(_Bool)arg4;	// IMP=0x00100000009c797d
- (id)layoutForSectionUsingTraitsEnvironment:(id)arg1 usingWidth:(double)arg2 shouldAddSupplementaryHeaderView:(_Bool)arg3;	// IMP=0x00100000009c78ce
- (void)setupConfiguration;	// IMP=0x00100000009c7849
- (id)headerItem;	// IMP=0x00100000009c7570
- (id)layoutForPublishersListSectionUsingLayoutEnvironment:(id)arg1 shouldAddSupplementaryHeaderView:(_Bool)arg2 objectsCount:(unsigned long long)arg3;	// IMP=0x00100000009c7275
- (id)layoutSectionForLoadingUsingTraitEnvironment:(id)arg1;	// IMP=0x00100000009c708d
- (id)layoutSectionForCuratedCollectionsListUsingLayoutEnvironment:(id)arg1 shouldAddSupplementaryHeaderView:(_Bool)arg2 objectsCount:(unsigned long long)arg3;	// IMP=0x00100000009c6da9
- (id)layoutSectionForCuratedCollectionsUsingTraitsEnvironment:(id)arg1 usingWidth:(double)arg2 shouldAddSupplementaryHeaderView:(_Bool)arg3;	// IMP=0x00100000009c6819
- (id)layoutSectionForCompactCollectionsUsingTraitsEnvironment:(id)arg1 usingWidth:(double)arg2 shouldAddSupplementaryHeaderView:(_Bool)arg3;	// IMP=0x00100000009c6236
- (id)layoutSectionForFiltersUsingFilters:(id)arg1 traitsEnvironment:(id)arg2 width:(double)arg3 shouldAddSupplementaryHeaderView:(_Bool)arg4;	// IMP=0x00100000009c5af6
- (id)layoutSectionForFeaturedGuideUsingTraitsEnvironment:(id)arg1 usingWidth:(double)arg2 featuredGuideTitle:(id)arg3;	// IMP=0x00100000009c5907
- (id)initWithSectionKind:(long long)arg1 usingMaxWidth:(double)arg2 usingTraitEnvironment:(id)arg3 count:(unsigned long long)arg4;	// IMP=0x00100000009c5863

@end

