//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class MacFooterView;

@protocol MacFooterViewDelegate <NSObject>
- (void)macFooterViewBackButtonTapped:(MacFooterView *)arg1;
- (void)macFooterViewRightButtonTapped:(MacFooterView *)arg1;
- (void)macFooterViewLeftButtonTapped:(MacFooterView *)arg1;
@end

