//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@class DirectionsPlan, GEOMapItemStorage, GEOSearchCategoryStorage, GEOURLOptions, MISSING_TYPE, MSPDroppedPin, MSPTransitStorageLineItem, NSData, NSMutableArray, NSString;

@interface MapsActivity : PBCodable
{
    unsigned long long _selectedPlaceIndex;	// 8 = 0x8
    unsigned long long _selectedTransitFeatureID;	// 16 = 0x10
    int _collectionsMode;	// 24 = 0x18
    DirectionsPlan *_directionsPlan;	// 32 = 0x20
    GEOURLOptions *_displayOptions;	// 40 = 0x28
    MSPDroppedPin *_droppedPin;	// 48 = 0x30
    MSPTransitStorageLineItem *_lineItem;	// 56 = 0x38
    GEOMapItemStorage *_presentedMapItem;	// 64 = 0x40
    GEOSearchCategoryStorage *_searchCategoryStorage;	// 72 = 0x48
    NSMutableArray *_searchPlaces;	// 80 = 0x50
    NSString *_searchString;	// 88 = 0x58
    NSString *_selectedTransitLineName;	// 96 = 0x60
    NSString *_userCreatedCollectionID;	// 104 = 0x68
    _Bool _isDroppedPinPresented;	// 112 = 0x70
    _Bool _isDroppedPinSelected;	// 113 = 0x71
    _Bool _isPresentingSelectedPlace;	// 114 = 0x72
    struct {
        unsigned int selectedPlaceIndex:1;
        unsigned int selectedTransitFeatureID:1;
        unsigned int collectionsMode:1;
        unsigned int isDroppedPinPresented:1;
        unsigned int isDroppedPinSelected:1;
        unsigned int isPresentingSelectedPlace:1;
    } _has;	// 116 = 0x74
}

+ (Class)searchPlacesType;	// IMP=0x0020000000a8c1dd
+ (id)mapsActivityPerDefault;	// IMP=0x0010000000763879
+ (void)brandMapsActivityFromUserActivity:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000761e5e
- (void).cxx_destruct;	// IMP=0x0010000000a8e80c
@property(retain, nonatomic) NSString *userCreatedCollectionID; // @synthesize userCreatedCollectionID=_userCreatedCollectionID;
@property(retain, nonatomic) MSPTransitStorageLineItem *lineItem; // @synthesize lineItem=_lineItem;
@property(retain, nonatomic) NSString *selectedTransitLineName; // @synthesize selectedTransitLineName=_selectedTransitLineName;
@property(nonatomic) unsigned long long selectedTransitFeatureID; // @synthesize selectedTransitFeatureID=_selectedTransitFeatureID;
@property(retain, nonatomic) GEOSearchCategoryStorage *searchCategoryStorage; // @synthesize searchCategoryStorage=_searchCategoryStorage;
@property(retain, nonatomic) GEOMapItemStorage *presentedMapItem; // @synthesize presentedMapItem=_presentedMapItem;
@property(nonatomic) _Bool isDroppedPinPresented; // @synthesize isDroppedPinPresented=_isDroppedPinPresented;
@property(nonatomic) _Bool isDroppedPinSelected; // @synthesize isDroppedPinSelected=_isDroppedPinSelected;
@property(retain, nonatomic) MSPDroppedPin *droppedPin; // @synthesize droppedPin=_droppedPin;
@property(retain, nonatomic) DirectionsPlan *directionsPlan; // @synthesize directionsPlan=_directionsPlan;
@property(nonatomic) _Bool isPresentingSelectedPlace; // @synthesize isPresentingSelectedPlace=_isPresentingSelectedPlace;
@property(nonatomic) unsigned long long selectedPlaceIndex; // @synthesize selectedPlaceIndex=_selectedPlaceIndex;
@property(retain, nonatomic) NSMutableArray *searchPlaces; // @synthesize searchPlaces=_searchPlaces;
@property(retain, nonatomic) NSString *searchString; // @synthesize searchString=_searchString;
@property(retain, nonatomic) GEOURLOptions *displayOptions; // @synthesize displayOptions=_displayOptions;
- (void)mergeFrom:(id)arg1;	// IMP=0x0010000000a8e282
- (unsigned long long)hash;	// IMP=0x0010000000a8e032
- (_Bool)isEqual:(id)arg1;	// IMP=0x0010000000a8dc7f
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0010000000a8d85d
- (void)copyTo:(id)arg1;	// IMP=0x0010000000a8d5c1
- (void)writeTo:(id)arg1;	// IMP=0x0010000000a8d2b0
- (_Bool)readFrom:(id)arg1;	// IMP=0x0010000000a8cb4f
- (id)dictionaryRepresentation;	// IMP=0x0010000000a8c4a1
- (id)description;	// IMP=0x0010000000a8c3f2
@property(readonly, nonatomic) _Bool hasUserCreatedCollectionID;
@property(readonly, nonatomic) _Bool hasLineItem;
@property(readonly, nonatomic) _Bool hasSelectedTransitLineName;
@property(nonatomic) _Bool hasSelectedTransitFeatureID;
@property(readonly, nonatomic) _Bool hasSearchCategoryStorage;
@property(readonly, nonatomic) _Bool hasPresentedMapItem;
@property(nonatomic) _Bool hasIsDroppedPinPresented;
@property(nonatomic) _Bool hasIsDroppedPinSelected;
@property(readonly, nonatomic) _Bool hasDroppedPin;
@property(readonly, nonatomic) _Bool hasDirectionsPlan;
@property(nonatomic) _Bool hasIsPresentingSelectedPlace;
@property(nonatomic) _Bool hasSelectedPlaceIndex;
- (id)searchPlacesAtIndex:(unsigned long long)arg1;	// IMP=0x0010000000a8c1c0
- (unsigned long long)searchPlacesCount;	// IMP=0x0010000000a8c1a3
- (void)addSearchPlaces:(id)arg1;	// IMP=0x0010000000a8c139
- (void)clearSearchPlaces;	// IMP=0x0010000000a8c11c
@property(readonly, nonatomic) _Bool hasSearchString;
- (int)StringAsCollectionsMode:(id)arg1;	// IMP=0x0010000000a8c058
- (MISSING_TYPE *)collectionsModeAsString: /* Error: Ran out of types for this method. */;	// IMP=0x0010000000a8c00f
@property(nonatomic) _Bool hasCollectionsMode;
@property(nonatomic) int collectionsMode; // @synthesize collectionsMode=_collectionsMode;
@property(readonly, nonatomic) _Bool hasDisplayOptions;
- (id)categoryString;	// IMP=0x001000000054f4e7
- (id)_destinationDirectionsURL;	// IMP=0x001000000054f29b
- (id)destinationString;	// IMP=0x001000000054f0e3
- (long long)type;	// IMP=0x001000000054f00c
- (id)mapsSiriAction;	// IMP=0x001000000054ea4e
@property(readonly, nonatomic) _Bool affectsMapType;
@property(readonly, nonatomic) NSData *bzip2DataByIterativelyReducingIfNeeded;
@property(readonly, nonatomic) NSData *bzip2CompressedData;
- (id)initWithBzip2CompressedData:(id)arg1;	// IMP=0x001000000076351f
@property(readonly, nonatomic) NSString *name;
@property(readonly, nonatomic) _Bool shouldIndex;

@end

