//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class GEOFeatureStyleAttributes;

@interface MapsUIImageGEOFeatureSpec
{
    _Bool _markerFallback;	// 9 = 0x9
    _Bool _transparent;	// 10 = 0xa
    _Bool _inverted;	// 11 = 0xb
    GEOFeatureStyleAttributes *_style;	// 16 = 0x10
    unsigned long long _size;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x0020000000695198
@property(nonatomic) _Bool inverted; // @synthesize inverted=_inverted;
@property(nonatomic) _Bool transparent; // @synthesize transparent=_transparent;
@property(nonatomic) unsigned long long size; // @synthesize size=_size;
@property(nonatomic) _Bool markerFallback; // @synthesize markerFallback=_markerFallback;
- (id)description;	// IMP=0x001000000069502d
- (_Bool)isEqual:(id)arg1;	// IMP=0x0010000000694e5e
- (unsigned long long)hash;	// IMP=0x0010000000694d32
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0010000000694c40
@property(copy, nonatomic) GEOFeatureStyleAttributes *style; // @synthesize style=_style;
- (id)imageForScale:(double)arg1 isCarPlay:(_Bool)arg2;	// IMP=0x00100000006948fd
- (_Bool)useSearchImageFallback;	// IMP=0x00100000006948f5
- (id)init;	// IMP=0x001000000069489c

@end

