//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface MapsAppTestLookAround
{
    unsigned long long _waitingTests;	// 8 = 0x8
    _Bool _savedDebugDrawContinuously;	// 16 = 0x10
}

@property(nonatomic) _Bool savedDebugDrawContinuously; // @synthesize savedDebugDrawContinuously=_savedDebugDrawContinuously;
- (void)runExitTest;	// IMP=0x00100000002fbfeb
- (void)runPanTest;	// IMP=0x00100000002fbfe5
- (void)zoom:(struct CGPoint)arg1 countdown:(int)arg2 oldFactor:(double)arg3 mapView:(id)arg4;	// IMP=0x00100000002fb9fe
- (void)runZoomTest;	// IMP=0x00100000002fb3ce
- (void)tap:(struct CGPoint)arg1 countdown:(int)arg2 mapView:(id)arg3 totalTimeInMS:(double)arg4 firstTap:(_Bool)arg5;	// IMP=0x00100000002fac29
- (void)runNavTest;	// IMP=0x00100000002fa232
- (void)runExploreTest;	// IMP=0x00100000002f9ff5
- (void)runEnterTestWithContinuationBlock:(CDUnknownBlockType)arg1;	// IMP=0x00100000002f9d0e
- (void)runEnterTest;	// IMP=0x00100000002f9cfa
- (void)runBrowseTestWithContinuationBlock:(CDUnknownBlockType)arg1;	// IMP=0x00100000002f9672
- (void)runBrowseTest;	// IMP=0x00100000002f965e
- (void)expandLookAroundToFullscreen:(_Bool)arg1 withLookAroundView:(id)arg2 mapItem:(id)arg3 completionBlock:(CDUnknownBlockType)arg4;	// IMP=0x00100000002f941d
- (void)enterLookAroundWithLookAroundView:(id)arg1 mapItem:(id)arg2 showsFullScreen:(_Bool)arg3 completionBlock:(CDUnknownBlockType)arg4;	// IMP=0x00100000002f912d
- (void)storefrontWillMoveBlock:(CDUnknownBlockType)arg1 didMoveBlock:(CDUnknownBlockType)arg2;	// IMP=0x00100000002f8ef8
- (void)selectSearchResult:(id)arg1;	// IMP=0x00100000002f8d9b
- (void)displayPlacecardPhotosWithSearchString:(id)arg1 resultShortAddress:(id)arg2 didShowPreviewBlock:(CDUnknownBlockType)arg3;	// IMP=0x00100000002f8864
- (void)addObserverWithSearchString:(id)arg1 forDidShowPreviewBlock:(CDUnknownBlockType)arg2;	// IMP=0x00100000002f8544
- (void)onLookAroundView:(id)arg1 didCompletionPostTransitionAnimation:(CDUnknownBlockType)arg2;	// IMP=0x00100000002f8489
- (void)onLookAroundView:(id)arg1 didBecomeAdequatelyDrawnCallback:(CDUnknownBlockType)arg2;	// IMP=0x00100000002f8284
- (void)jumpToOptionsCoord:(CDUnknownBlockType)arg1;	// IMP=0x00100000002f7fb3
- (_Bool)runTest;	// IMP=0x00100000002f7b2c
- (void)cleanup:(_Bool)arg1;	// IMP=0x00100000002f799d

@end

