//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface NavigationAudioFeedbackCollector : NSObject
{
    struct GEONavigationAudioFeedback *_audioFeedback;	// 8 = 0x8
    _Bool _viewingAudioSettings;	// 16 = 0x10
    _Bool _sessionDidStart;	// 17 = 0x11
}

- (void)navigationService:(id)arg1 didStartSpeakingPrompt:(id)arg2;	// IMP=0x00200000004c673b
@property(readonly, nonatomic) struct GEONavigationAudioFeedback *audioFeedback;
- (void)updateViewingAudioSettings:(_Bool)arg1;	// IMP=0x00100000004c6715
- (void)endSession;	// IMP=0x00100000004c66b0
- (void)startSession;	// IMP=0x00100000004c6636
- (void)dealloc;	// IMP=0x00100000004c65fc

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

