//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class BackgroundColorButton, MapsProgressButton, NSString, NavTrafficIncidentHeaderView, UILabel, UILayoutGuide, UIStackView;
@protocol MKArtworkImageSource, NavUserDecisionConfirmationViewDelegate;

@interface NavUserDecisionConfirmationView
{
    NavTrafficIncidentHeaderView *_headerView;	// 8 = 0x8
    id <NavUserDecisionConfirmationViewDelegate> _delegate;	// 16 = 0x10
    BackgroundColorButton *_cancelButton;	// 24 = 0x18
    MapsProgressButton *_confirmButton;	// 32 = 0x20
    UIStackView *_buttonsStackView;	// 40 = 0x28
    UILayoutGuide *_paddingGuide;	// 48 = 0x30
}

- (void).cxx_destruct;	// IMP=0x00200000007c602e
@property(retain, nonatomic) UILayoutGuide *paddingGuide; // @synthesize paddingGuide=_paddingGuide;
@property(readonly, nonatomic) UIStackView *buttonsStackView; // @synthesize buttonsStackView=_buttonsStackView;
@property(retain, nonatomic) MapsProgressButton *confirmButton; // @synthesize confirmButton=_confirmButton;
@property(retain, nonatomic) BackgroundColorButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(nonatomic) __weak id <NavUserDecisionConfirmationViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)_didTapActionButton:(id)arg1;	// IMP=0x00100000007c5f35
- (void)_didTapCancelButton:(id)arg1;	// IMP=0x00100000007c5ee9
@property(nonatomic) _Bool progressBarHidden;
@property(nonatomic) double completionProgress;
- (void)confirmButtonTitlesetCompletionProgress:(double)arg1;	// IMP=0x00100000007c5d6b
@property(copy, nonatomic) NSString *confirmButtonTitle;
@property(copy, nonatomic) NSString *cancelButtonTitle;
@property(retain, nonatomic) id <MKArtworkImageSource> imageSource;
- (id);	// IMP=0x00100000007c5b88
@property(readonly, nonatomic) UILabel *primaryLabel;
- (id)_initialConstraints;	// IMP=0x00100000007c549f
- (void)_customInit;	// IMP=0x00100000007c5010
- (id)initWithCoder:(id)arg1;	// IMP=0x00100000007c4fb2
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00100000007c4f43

// Remaining properties
@property(readonly, nonatomic) UILabel *secondaryLabel;

@end

