//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSObject, NSString, ParkedCarPersonalizedItem;
@protocol OS_dispatch_queue;

@interface ParkedCarItemSource
{
    ParkedCarPersonalizedItem *_item;	// 8 = 0x8
    NSObject<OS_dispatch_queue> *_lockQueue;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x002000000098e935
- (void)parkedCarManager:(id)arg1 didUpdateParkedCar:(id)arg2;	// IMP=0x001000000098e74e
- (void)parkedCarManager:(id)arg1 didAddParkedCar:(id)arg2;	// IMP=0x001000000098e6c8
- (void)parkedCarManager:(id)arg1 didRemoveParkedCar:(id)arg2;	// IMP=0x001000000098e698
- (id)allItems;	// IMP=0x001000000098e50b
- (void)dealloc;	// IMP=0x001000000098e496
- (void)assignItem:(id)arg1;	// IMP=0x001000000098e3e6
- (id)init;	// IMP=0x001000000098e289

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

