//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class UIEvent, UIView;

@protocol PassThroughViewDelegate <NSObject>
@property(readonly, nonatomic) UIView *passThroughView;

@optional
- (void)passThroughView:(UIView *)arg1 didMoveToView:(UIView *)arg2;
- (_Bool)shouldPassPoint:(struct CGPoint)arg1 withEvent:(UIEvent *)arg2 inView:(UIView *)arg3;
@end

