//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSCache, NSMapTable, NSMutableDictionary, NSString;

@interface POISearchManager : NSObject
{
    NSCache *_poiCache;	// 8 = 0x8
    NSMapTable *_completionHandlers;	// 16 = 0x10
    NSMutableDictionary *_canShowActivityIndicatorForBusinessIDs;	// 24 = 0x18
    NSMutableDictionary *_loadingForBusinessIDs;	// 32 = 0x20
    NSMutableDictionary *_loadingTokensForBusinessIDs;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x00200000005564d7
- (void)didReceiveRAPNotification;	// IMP=0x00100000005564c1
- (void)searchForIdentifier:(id)arg1 allowExpired:(_Bool)arg2 traits:(id)arg3 completionHandler:(CDUnknownBlockType)arg4 callbackQueue:(id)arg5;	// IMP=0x00100000005564a5
- (void)searchForIdentifier:(id)arg1 allowExpired:(_Bool)arg2 traits:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;	// IMP=0x0010000000556449
- (void)searchForIdentifier:(id)arg1 allowExpired:(_Bool)arg2 traits:(id)arg3 completionHandler:(CDUnknownBlockType)arg4 searchResultType:(unsigned int)arg5 callbackQueue:(id)arg6;	// IMP=0x0010000000555f03
- (void)resourceManifestManagerDidChangeActiveTileGroup:(id)arg1;	// IMP=0x0010000000555eed
- (void)_cacheAndHandleSearchResult:(id)arg1 identifier:(id)arg2 completionHandlers:(id)arg3;	// IMP=0x0010000000555cc6
- (id)searchResultForIdentifier:(id)arg1;	// IMP=0x0010000000555c75
- (void)_setLoading:(_Bool)arg1 forIdentifier:(id)arg2;	// IMP=0x0010000000555bb5
- (void)setCanShowActivityIndicator:(_Bool)arg1 forIdentifier:(id)arg2;	// IMP=0x00100000005559c5
- (void)_updateActivityIndicatorForIdentifier:(id)arg1;	// IMP=0x001000000055583e
- (id)init;	// IMP=0x00100000005557bc

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

