//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSArray, NSMutableArray, NSString;
@protocol SupplementaryElementsDataSourceDelegate;

@interface RAPHomeDataSource
{
    NSArray *_allReports;	// 8 = 0x8
    NSArray *_reportsInReview;	// 16 = 0x10
    NSArray *_reportsAlreadyReviewed;	// 24 = 0x18
    NSMutableArray *_incidentReports;	// 32 = 0x20
    NSMutableArray *_homeViewSections;	// 40 = 0x28
    NSMutableArray *_reportActionSections;	// 48 = 0x30
    NSMutableArray *_incidentsSections;	// 56 = 0x38
    _Bool _reportsInReviewSectionShouldShowMoreButton;	// 64 = 0x40
    _Bool _reportsAlreadyReviewedSectionShouldShowMoreButton;	// 65 = 0x41
    _Bool _allReportsSectionShouldShowMoreButton;	// 66 = 0x42
    int _entryPoint;	// 68 = 0x44
    id <SupplementaryElementsDataSourceDelegate> _supplementaryElementsDelegate;	// 72 = 0x48
}

- (void).cxx_destruct;	// IMP=0x0020000000358106
@property(nonatomic) int entryPoint; // @synthesize entryPoint=_entryPoint;
@property(nonatomic) __weak id <SupplementaryElementsDataSourceDelegate> supplementaryElementsDelegate; // @synthesize supplementaryElementsDelegate=_supplementaryElementsDelegate;
- (id)collectionView:(id)arg1 contextMenuConfigurationForItemsAtIndexPaths:(id)arg2 point:(struct CGPoint)arg3;	// IMP=0x0010000000357ce2
- (_Bool)_isInternalInstall;	// IMP=0x0010000000357c97
- (int)analyticsTarget;	// IMP=0x0010000000357c8c
- (_Bool)_mapIsSprMap;	// IMP=0x0010000000357bd7
- (void)reportHistoryManagerDidUpdate:(id)arg1;	// IMP=0x0010000000357ad8
- (double)headerHeightForSection:(long long)arg1 collectionView:(id)arg2;	// IMP=0x0010000000357910
- (double)footerHeightForSection:(long long)arg1 collectionView:(id)arg2;	// IMP=0x001000000035768e
- (_Bool)collectionView:(id)arg1 shouldSelectItemAtIndexPath:(id)arg2;	// IMP=0x00100000003575ee
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;	// IMP=0x0010000000357394
- (void)seeAllTappedForReportForSection:(long long)arg1;	// IMP=0x00100000003572d6
- (void)privacyTextTapped;	// IMP=0x0010000000357299
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;	// IMP=0x0010000000356710
- (id)_footerLinkText;	// IMP=0x00100000003566a8
- (id)_footerStringReviewedSection;	// IMP=0x001000000035660c
- (id)_footerString90Days;	// IMP=0x0010000000356570
- (id)_headerStringActionsSection;	// IMP=0x00100000003564d4
- (id)_footerStringActionsSection;	// IMP=0x001000000035646c
- (id)_headerStringIncidentsReportedSection;	// IMP=0x00100000003563d0
- (id)_headerStringIssuesReportedSection;	// IMP=0x0010000000356334
- (id)_headerStringReviewedSection;	// IMP=0x0010000000356298
- (id)_headerStringInReviewSection;	// IMP=0x00100000003561fc
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;	// IMP=0x00100000003560e0
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;	// IMP=0x001000000035588d
- (long long)sectionForIndex:(unsigned long long)arg1;	// IMP=0x0010000000355812
- (long long)numberOfSectionsInCollectionView:(id)arg1;	// IMP=0x00100000003557f5
- (void)_addSections;	// IMP=0x00100000003555ed
- (void)_buildReportHistoryContent;	// IMP=0x00100000003552b8
- (void)_loadReportHistoryContent;	// IMP=0x001000000035525f
- (void)_populateIncidentsSection;	// IMP=0x001000000035509f
- (void)_populateActionSection;	// IMP=0x0010000000354f05
- (id)initWithCollectionView:(id)arg1 updateLocation:(_Bool)arg2;	// IMP=0x0010000000354c0c

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

