//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString, RAPReport, UIActivityIndicatorView;

@interface RAPReportComposerViewController
{
    RAPReport *_report;	// 8 = 0x8
    CDUnknownBlockType _completion;	// 16 = 0x10
    _Bool _shouldInstrumentPrivacyCancelOnNextBackAction;	// 24 = 0x18
    UIActivityIndicatorView *_sendSpinner;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x00200000008efa37
@property(readonly, nonatomic) RAPReport *report; // @synthesize report=_report;
- (void)returnFromViewController:(id)arg1;	// IMP=0x00100000008ef842
- (void)segueToViewController:(id)arg1 afterReturningFromViewController:(id)arg2;	// IMP=0x00100000008ef743
- (void)segueToViewController:(id)arg1;	// IMP=0x00100000008ef72c
- (void)_cancelWithAnalyticsTarget:(int)arg1;	// IMP=0x00100000008ef6eb
- (void)_sendWithFinalOutcome:(long long)arg1 acknowledgementOptions:(id)arg2;	// IMP=0x00100000008eeadb
- (void)_invokeCompletionWithOutcome:(long long)arg1;	// IMP=0x00100000008eeaa0
- (id)popViewControllerAnimated:(_Bool)arg1;	// IMP=0x00100000008ee957
- (void)_exitCommentCorrections;	// IMP=0x00100000008ee927
- (void)_exitCuratedCollections;	// IMP=0x00100000008ee8f7
- (void)_exitPlaceCorrections;	// IMP=0x00100000008ee8c4
- (void)_exitLookAround;	// IMP=0x00100000008ee891
- (void)_capturePrivacyBackActionIfNeeded;	// IMP=0x00100000008ee7e9
- (void)_handlePrivacyCancelledNotification:(id)arg1;	// IMP=0x00100000008ee779
- (void)_registerForPrivacyNotification;	// IMP=0x00100000008ee70a
- (id)_cancelButtonWithSelector:(SEL)arg1;	// IMP=0x00100000008ee655
- (id)initWithReport:(id)arg1 commentQuestion:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00100000008ee356
- (id)initWithReport:(id)arg1 curatedCollectionQuestion:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00100000008edf46
- (id)initWithReport:(id)arg1 lookAroundQuestion:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00100000008edc05
- (id)initWithReport:(id)arg1 placecardQuestion:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00100000008edb3b
- (id)initWithReport:(id)arg1 categoryQuestion:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00100000008ed86d

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

