//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface RideBookingImageCache : NSObject
{
    NSMutableDictionary *_imageCache;	// 8 = 0x8
}

+ (id)sharedCache;	// IMP=0x0040000000149792
- (void).cxx_destruct;	// IMP=0x0020000000149cb5
@property(retain, nonatomic) NSMutableDictionary *imageCache; // @synthesize imageCache=_imageCache;
- (id)imageForKey:(id)arg1;	// IMP=0x0010000000149ad4
- (void)cacheINImageData:(id)arg1 withKey:(id)arg2;	// IMP=0x00100000001497e7

@end

