//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class RoutePlanningRefinementModel;

@protocol RoutePlanningRefinementDelegate
- (void)updatedRefinementModel:(RoutePlanningRefinementModel *)arg1;
- (void)selectedRefinementModel:(RoutePlanningRefinementModel *)arg1;
- (void)pressedRefinementModel:(RoutePlanningRefinementModel *)arg1;
@end

