//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class ModalCardHeaderView, RoutePlanningOptionsDataSource, UIButton, UIStackView, UIView;
@protocol RoutePlanningDataCoordination;

@interface RoutePlanningOptionsViewController
{
    _Bool _didStartObservingUnsavedChanges;	// 16 = 0x10
    _Bool _didStartObservingCollectionViewBounds;	// 17 = 0x11
    _Bool _inUpdatePreferredContentSize;	// 18 = 0x12
    CDUnknownBlockType _completionHandler;	// 24 = 0x18
    unsigned long long _preferredPresentationStyle;	// 32 = 0x20
    id <RoutePlanningDataCoordination> _dataCoordinator;	// 40 = 0x28
    ModalCardHeaderView *_modalHeaderView;	// 48 = 0x30
    UIStackView *_stackView;	// 56 = 0x38
    UIView *_footerView;	// 64 = 0x40
    UIButton *_cancelButton;	// 72 = 0x48
    UIButton *_applyButton;	// 80 = 0x50
}

+ (Class)_dataSourceClass;	// IMP=0x00400000005fc4a0
+ (_Bool)useCollectionView;	// IMP=0x00100000005fc498
- (void).cxx_destruct;	// IMP=0x00200000005fee55
@property(nonatomic) __weak UIButton *applyButton; // @synthesize applyButton=_applyButton;
@property(nonatomic) __weak UIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(retain, nonatomic) UIView *footerView; // @synthesize footerView=_footerView;
@property(retain, nonatomic) UIStackView *stackView; // @synthesize stackView=_stackView;
@property(retain, nonatomic) ModalCardHeaderView *modalHeaderView; // @synthesize modalHeaderView=_modalHeaderView;
@property(readonly, nonatomic) __weak id <RoutePlanningDataCoordination> dataCoordinator; // @synthesize dataCoordinator=_dataCoordinator;
- (void)setPreferredPresentationStyle:(unsigned long long)arg1;	// IMP=0x00100000005fed62
- (unsigned long long)preferredPresentationStyle;	// IMP=0x00100000005fed51
- (int)_analyticsTarget;	// IMP=0x00100000005fecf1
- (int)_analyticsTargetForTransportType:(long long)arg1;	// IMP=0x00100000005fecd4
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;	// IMP=0x00100000005fec30
- (void)_presentRAP;	// IMP=0x00100000005fea72
- (void)dataSourceDidRebuildSections:(id)arg1;	// IMP=0x00100000005fea31
- (void)_didTapDoneButton:(id)arg1;	// IMP=0x00100000005fe912
- (void)_didTapCancelButton:(id)arg1;	// IMP=0x00100000005fe820
- (void)handleDismissAction:(id)arg1;	// IMP=0x00100000005fe80e
- (void)_updateDoneButtonIfNeeded;	// IMP=0x00100000005fe717
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x00100000005fe400
- (id)_titleForTransportType:(long long)arg1;	// IMP=0x00100000005fe30a
- (struct CGSize)_calculatePreferredContentSize;	// IMP=0x00100000005fe159
- (void)_updatePreferredContentSize;	// IMP=0x00100000005fe0b1
- (double)heightForLayout:(unsigned long long)arg1;	// IMP=0x00100000005fdfa6
- (id)initialConstraints;	// IMP=0x00100000005fd642
- (void)setupSubviews;	// IMP=0x00100000005fcbf2
- (void)viewDidLoad;	// IMP=0x00100000005fc82b
@property(readonly, nonatomic) RoutePlanningOptionsDataSource *routeOptionsDataSource;
- (id)initWithDataCoordinator:(id)arg1 automaticallySaveChanges:(_Bool)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x00100000005fc5a3
- (void)dealloc;	// IMP=0x00100000005fc4bc
- (long long)collectionViewListLayoutAppearanceStyle;	// IMP=0x00100000005fc4b1

@end

