//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class GEOMapServiceTraits, GEORelatedSearchSuggestion, NSArray, NSError, NSHashTable, NSString, SearchFieldItem, SearchInfo, SearchManager;
@protocol OS_dispatch_queue;

@interface SearchSession : NSObject
{
    _Bool _shouldBroadcast;	// 8 = 0x8
    _Bool _restoreSingleResult;	// 9 = 0x9
    _Bool _shouldCreateHistoryEntry;	// 10 = 0xa
    _Bool _isLoading;	// 11 = 0xb
    _Bool _isSuggestionSearch;	// 12 = 0xc
    _Bool _isResultRefinementsBarSearch;	// 13 = 0xd
    _Bool _invalidated;	// 14 = 0xe
    int _source;	// 16 = 0x10
    SearchFieldItem *_searchFieldItem;	// 24 = 0x18
    SearchInfo *_searchInfo;	// 32 = 0x20
    SearchManager *_searchManager;	// 40 = 0x28
    unsigned long long _options;	// 48 = 0x30
    unsigned long long _origin;	// 56 = 0x38
    GEOMapServiceTraits *_traits;	// 64 = 0x40
    GEORelatedSearchSuggestion *_suggestion;	// 72 = 0x48
    NSError *_lastError;	// 80 = 0x50
    NSHashTable *_observers;	// 88 = 0x58
    NSObject<OS_dispatch_queue> *_observersQueue;	// 96 = 0x60
    SearchInfo *_suggestionSearchInfo;	// 104 = 0x68
}

+ (void)setCurrentSearchSession:(id)arg1;	// IMP=0x00200000001a6f99
+ (id)currentSearchSession;	// IMP=0x00100000001a6f46
+ (void)initialize;	// IMP=0x00100000001a6e49
+ (void)performSearchForEngineType:(int)arg1 withObserver:(id)arg2;	// IMP=0x0010000000b0a068
- (void).cxx_destruct;	// IMP=0x00100000001a9176
@property(retain, nonatomic) SearchInfo *suggestionSearchInfo; // @synthesize suggestionSearchInfo=_suggestionSearchInfo;
@property(nonatomic, getter=isInvalidated) _Bool invalidated; // @synthesize invalidated=_invalidated;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *observersQueue; // @synthesize observersQueue=_observersQueue;
@property(retain, nonatomic) NSHashTable *observers; // @synthesize observers=_observers;
@property(nonatomic) _Bool isResultRefinementsBarSearch; // @synthesize isResultRefinementsBarSearch=_isResultRefinementsBarSearch;
@property(nonatomic) _Bool isSuggestionSearch; // @synthesize isSuggestionSearch=_isSuggestionSearch;
@property(nonatomic) _Bool isLoading; // @synthesize isLoading=_isLoading;
@property(readonly, nonatomic) NSError *lastError; // @synthesize lastError=_lastError;
@property(retain, nonatomic) GEORelatedSearchSuggestion *suggestion; // @synthesize suggestion=_suggestion;
@property(nonatomic) _Bool shouldCreateHistoryEntry; // @synthesize shouldCreateHistoryEntry=_shouldCreateHistoryEntry;
@property(nonatomic) int source; // @synthesize source=_source;
@property(retain, nonatomic) GEOMapServiceTraits *traits; // @synthesize traits=_traits;
@property(nonatomic) _Bool restoreSingleResult; // @synthesize restoreSingleResult=_restoreSingleResult;
@property(nonatomic) _Bool shouldBroadcast; // @synthesize shouldBroadcast=_shouldBroadcast;
@property(nonatomic) unsigned long long origin; // @synthesize origin=_origin;
@property(readonly, nonatomic) unsigned long long options; // @synthesize options=_options;
@property(retain, nonatomic) SearchManager *searchManager; // @synthesize searchManager=_searchManager;
@property(retain, nonatomic) SearchInfo *searchInfo; // @synthesize searchInfo=_searchInfo;
@property(retain, nonatomic) SearchFieldItem *searchFieldItem; // @synthesize searchFieldItem=_searchFieldItem;
- (void)_assertNotInvalidated;	// IMP=0x00100000001a8edd
- (void)searchManager:(id)arg1 didReceiveSearchInfo:(id)arg2 error:(id)arg3;	// IMP=0x00100000001a8cb1
- (void)searchManager:(id)arg1 willProcessSearchFieldItem:(id)arg2;	// IMP=0x00100000001a8bd0
- (void)_willProcessSearchFieldItem;	// IMP=0x00100000001a8b4e
- (void)_processResults:(id)arg1;	// IMP=0x00100000001a8927
- (void)_performSearch;	// IMP=0x00100000001a87ff
- (void)_performSearchIfNeeded;	// IMP=0x00100000001a8489
- (void)_notifyObservers:(id)arg1 block:(CDUnknownBlockType)arg2;	// IMP=0x00100000001a8360
- (void)_notifyAllObservers:(CDUnknownBlockType)arg1;	// IMP=0x00100000001a81ae
- (void)removeObserver:(id)arg1;	// IMP=0x00100000001a80ac
- (void)addObserver:(id)arg1;	// IMP=0x00100000001a7f9a
- (_Bool)isSingleResultToShowAsPlacecard;	// IMP=0x00100000001a7eb6
- (_Bool)isRedoOrAutoRedoSearchType;	// IMP=0x00100000001a7e99
@property(readonly, nonatomic) unsigned long long searchRequestType;
@property(nonatomic) unsigned long long selectedResultIndex;
@property(readonly, nonatomic) SearchInfo *currentResultsSearchInfo;
@property(readonly, nonatomic) NSArray *currentResults;
@property(readonly, nonatomic) NSString *stringToDisplay;
@property(readonly, nonatomic) _Bool isVenueQuery;
@property(readonly, nonatomic) _Bool singleResultMode;
- (void)invalidateWithReason:(unsigned long long)arg1;	// IMP=0x00100000001a77f9
- (void)invalidate;	// IMP=0x00100000001a77e5
- (void)didChangeSearchResults;	// IMP=0x00100000001a7763
- (void)notifyPPTDidChangeSearchResults;	// IMP=0x00100000001a7706
- (void)didChangeSearchFieldItem;	// IMP=0x00100000001a769e
- (void)showExistingSearchInfo:(id)arg1;	// IMP=0x00100000001a7670
- (void)restoreSearchForItem:(id)arg1 withResults:(id)arg2;	// IMP=0x00100000001a74c9
- (void)redoSearchWithTraits:(id)arg1;	// IMP=0x00100000001a7379
- (void)suggestionSearch:(id)arg1 withTraits:(id)arg2;	// IMP=0x00100000001a7171
- (void)startSearch:(id)arg1;	// IMP=0x00100000001a7001
- (void)becomeCurrent;	// IMP=0x00100000001a6fe5
- (id)initWithOrigin:(unsigned long long)arg1 options:(unsigned long long)arg2;	// IMP=0x00100000001a6cee
- (id)initWithOrigin:(unsigned long long)arg1;	// IMP=0x00100000001a6cda
- (id)init;	// IMP=0x00100000001a6cc6
@property(readonly, nonatomic) NSString *printedPageSubtitle;
@property(readonly, nonatomic) NSString *printedPageTitle;
@property(readonly, nonatomic) NSString *currentUserTypedSearchString;
@property(readonly, nonatomic) NSString *currentSearchString;
@property(readonly) _Bool isOptionsLowFuel;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

