//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface SearchHomeNoDataLayoutProvider : NSObject
{
}

- (id)layoutSectionWithLayoutEnvironment:(id)arg1 estimatedHeaderHeight:(double)arg2 estimatedFooterHeight:(double)arg3 deletionBlock:(CDUnknownBlockType)arg4 objectsCount:(unsigned long long)arg5 mapsTheme:(id)arg6;	// IMP=0x00200000002e4c14
- (id)cellForRowAtIndexPath:(id)arg1 collectionView:(id)arg2 item:(id)arg3;	// IMP=0x00100000002e4b2d
- (long long)type;	// IMP=0x00100000002e4b25
- (id)cellReuseIdentifier;	// IMP=0x00100000002e4b0c
- (id)cellClasses;	// IMP=0x00100000002e4aa0

// Remaining properties
// Error: Property attributes should begin with the type ('T') attribute, property name: debugDescription
// Property attributes: (null)

@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

