//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class NSDateComponentsFormatter, NSLayoutConstraint, NSNumberFormatter, UIButton, UILabel, UIStackView;
@protocol TraceControlViewDelegate;

@interface TraceControlView : UIView
{
    id <TraceControlViewDelegate> _delegate;	// 8 = 0x8
    _Bool _isPlaying;	// 16 = 0x10
    double _playSpeed;	// 24 = 0x18
    UIButton *_saveCameraSnapshotButton;	// 32 = 0x20
    UIButton *_playButton;	// 40 = 0x28
    UIButton *_ffButton;	// 48 = 0x30
    UIButton *_frButton;	// 56 = 0x38
    UIButton *_bookmarksButton;	// 64 = 0x40
    UIButton *_testLoggingButton;	// 72 = 0x48
    UILabel *_positionLabel;	// 80 = 0x50
    UIStackView *_firstLineStack;	// 88 = 0x58
    UIStackView *_secondLineStack;	// 96 = 0x60
    NSLayoutConstraint *_firstLineBottomToBottomConstraint;	// 104 = 0x68
    NSLayoutConstraint *_secondLineBottomToBottomConstraint;	// 112 = 0x70
    unsigned long long _numberOfControls;	// 120 = 0x78
    double _lastPositionInLabel;	// 128 = 0x80
    NSDateComponentsFormatter *_timePositionFormatter;	// 136 = 0x88
    NSNumberFormatter *_distancePositionFormatter;	// 144 = 0x90
    _Bool _useDistanceAsPosition;	// 152 = 0x98
    _Bool _isLogging;	// 153 = 0x99
    UIButton *_jumpBackButton;	// 160 = 0xa0
    UIButton *_viewCameraSnapshotsButton;	// 168 = 0xa8
}

- (void).cxx_destruct;	// IMP=0x0020000000267733
@property(readonly, nonatomic) UIButton *viewCameraSnapshotsButton; // @synthesize viewCameraSnapshotsButton=_viewCameraSnapshotsButton;
@property(nonatomic) _Bool isLogging; // @synthesize isLogging=_isLogging;
@property(nonatomic) _Bool useDistanceAsPosition; // @synthesize useDistanceAsPosition=_useDistanceAsPosition;
@property(readonly, nonatomic) UIButton *bookmarksButton; // @synthesize bookmarksButton=_bookmarksButton;
@property(readonly, nonatomic) UIButton *frButton; // @synthesize frButton=_frButton;
@property(readonly, nonatomic) UIButton *ffButton; // @synthesize ffButton=_ffButton;
@property(readonly, nonatomic) UIButton *playButton; // @synthesize playButton=_playButton;
@property(readonly, nonatomic) UIButton *jumpBackButton; // @synthesize jumpBackButton=_jumpBackButton;
@property(nonatomic) double playSpeed; // @synthesize playSpeed=_playSpeed;
@property(nonatomic) _Bool isPlaying; // @synthesize isPlaying=_isPlaying;
@property(nonatomic) __weak id <TraceControlViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void)_testLoggingButtonPressed:(id)arg1;	// IMP=0x00100000002675cb
@property(readonly, nonatomic) NSDateComponentsFormatter *timePositionFormatter;
- (void)setPosition:(double)arg1;	// IMP=0x001000000026733f
- (void)_viewCameraSnapshotsButtonPressed:(id)arg1;	// IMP=0x001000000026723c
- (void)_saveCameraSnapshotButtonPressed:(id)arg1;	// IMP=0x0010000000267200
- (void)_bookmarksButtonPressed:(id)arg1;	// IMP=0x00100000002671c4
- (void)_ffButtonPressed:(id)arg1;	// IMP=0x0010000000267120
- (void)_frButtonPressed:(id)arg1;	// IMP=0x0010000000267082
@property(readonly, nonatomic) unsigned long long _currentPlaySpeedIndex;
- (void)_playButtonPressed:(id)arg1;	// IMP=0x0010000000266f42
- (void)_jumpBackButtonPressed:(id)arg1;	// IMP=0x0010000000266f06
- (_Bool)_isSpanningTwoLines;	// IMP=0x0010000000266ea1
- (_Bool)_shouldSpanTwoLines;	// IMP=0x0010000000266e44
- (void)layoutSubviews;	// IMP=0x001000000026646f
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0010000000265575

@end

