//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSArray, TransitSchedulesDepartureDataProvider;
@protocol GEOTransitDeparture, GEOTransitDepartureSequence;

@protocol TransitSchedulesDepartureDataProviderDelegate
- (void)departureDataProvider:(TransitSchedulesDepartureDataProvider *)arg1 selectedDepartureSequence:(id <GEOTransitDepartureSequence>)arg2 withIndex:(unsigned long long)arg3;
- (void)departureDataProvider:(TransitSchedulesDepartureDataProvider *)arg1 updatedDepartureSequences:(NSArray *)arg2;
- (void)departureDataProvider:(TransitSchedulesDepartureDataProvider *)arg1 selectedDeparture:(id <GEOTransitDeparture>)arg2 withIndex:(unsigned long long)arg3;
- (void)departureDataProvider:(TransitSchedulesDepartureDataProvider *)arg1 updatedDepartures:(NSArray *)arg2;
@end

