//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface TransitContainerViewController
{
}

- (_Bool)allowsDisplayOnLockScreen;	// IMP=0x004000000047e204
- (_Bool)_canShowWhileLocked;	// IMP=0x001000000047e1fc

@end

