//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIViewController.h>

@class GEORPThirdPartyPhotoSharingPreference, NSString;

@interface UGCThirdPartyPhotoSharingSplashViewController : UIViewController
{
    GEORPThirdPartyPhotoSharingPreference *_thirdPartyPhotoSharingPreference;	// 8 = 0x8
}

+ (void)checkShouldPresentPhotoSharingSplash:(CDUnknownBlockType)arg1;	// IMP=0x0020000000ae086a
- (void).cxx_destruct;	// IMP=0x0020000000ae134f
@property(retain, nonatomic) GEORPThirdPartyPhotoSharingPreference *thirdPartyPhotoSharingPreference; // @synthesize thirdPartyPhotoSharingPreference=_thirdPartyPhotoSharingPreference;
- (_Bool)presentationControllerShouldDismiss:(id)arg1;	// IMP=0x0010000000ae1322
- (void)_setThirdPartyPhotoShareEnabled:(_Bool)arg1;	// IMP=0x0010000000ae0f94
- (void)_noThanksPressed;	// IMP=0x0010000000ae0f80
- (void)_sharePressed;	// IMP=0x0010000000ae0f69
- (id)_obViewController;	// IMP=0x0010000000ae0c5f
- (void)viewDidLoad;	// IMP=0x0010000000ae0a82

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

