//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class GEOObserverHashTable, NSArray, NSString;
@protocol MKMapServiceTicket;

@interface UserProfileReportHistoryManager : NSObject
{
    GEOObserverHashTable *_observers;	// 8 = 0x8
    NSString *_countryCode;	// 16 = 0x10
    NSArray *_allRAPReports;	// 24 = 0x18
    NSArray *_filteredRAPReports;	// 32 = 0x20
    NSArray *_allTrafficIncidentReports;	// 40 = 0x28
    NSArray *_filteredTrafficIncidentReports;	// 48 = 0x30
    _Bool _wantsRefinedRAPHistory;	// 56 = 0x38
    id <MKMapServiceTicket> _mapItemTicket;	// 64 = 0x40
    _Bool _hasInReviewRAPs;	// 72 = 0x48
    _Bool _hasReviewedRAPs;	// 73 = 0x49
    long long _crashesCount;	// 80 = 0x50
    long long _hazardsCount;	// 88 = 0x58
    long long _speedChecksCount;	// 96 = 0x60
    long long _roadWorkCount;	// 104 = 0x68
}

+ (id)sharedInstance;	// IMP=0x002000000065859b
- (void).cxx_destruct;	// IMP=0x0020000000659ff0
@property(readonly, nonatomic) long long roadWorkCount; // @synthesize roadWorkCount=_roadWorkCount;
@property(readonly, nonatomic) long long speedChecksCount; // @synthesize speedChecksCount=_speedChecksCount;
@property(readonly, nonatomic) long long hazardsCount; // @synthesize hazardsCount=_hazardsCount;
@property(readonly, nonatomic) long long crashesCount; // @synthesize crashesCount=_crashesCount;
@property(readonly, nonatomic) _Bool hasReviewedRAPs; // @synthesize hasReviewedRAPs=_hasReviewedRAPs;
@property(readonly, nonatomic) _Bool hasInReviewRAPs; // @synthesize hasInReviewRAPs=_hasInReviewRAPs;
- (void)rapRecordObjectsDidChange;	// IMP=0x0010000000659fa4
- (void)countryConfigurationDidChange:(id)arg1;	// IMP=0x0010000000659f2f
- (void)_cancelMapItemTicket;	// IMP=0x0010000000659efd
- (void)_fetchMapItemsForRAPHistoryIfNeeded;	// IMP=0x0010000000659481
- (void)refineRAPHistory;	// IMP=0x001000000065945c
@property(readonly, nonatomic) NSArray *rapHistory;
- (long long)_daysBetweenDates:(id)arg1 currentDate:(id)arg2;	// IMP=0x001000000065938a
- (void)_updateReports:(id)arg1 incidents:(id)arg2;	// IMP=0x0010000000658e04
- (void)_loadReportsAndIncidents;	// IMP=0x0010000000658a93
@property(readonly, nonatomic) _Bool hasIncidentReports;
- (_Bool)_shouldShowReportOrIncidentCreatedInCountry:(id)arg1;	// IMP=0x0010000000658985
@property(readonly, nonatomic, getter=isChinaUserOutsideOfChina) _Bool chinaUserOutsideOfChina;
- (_Bool)_isKoreaCountryCode:(id)arg1;	// IMP=0x00100000006587b1
- (_Bool)_isChinaCountryCode:(id)arg1;	// IMP=0x0010000000658795
- (_Bool)_inKorea;	// IMP=0x001000000065877f
@property(readonly, nonatomic) _Bool inChina;
@property(readonly, nonatomic) GEOObserverHashTable *observers;
- (id)init;	// IMP=0x00100000006585f0

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

