//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <VirtualGarage/VGVirtualGarageService.h>

@class NSString;

@interface VGVirtualGarageService (EvMetadata)
- (void)getEvChargingMetadata:(CDUnknownBlockType)arg1;	// IMP=0x00200000007a1079

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

