//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class MISSING_TYPE;

@interface _TtC18SharingViewService27B389NFCStatusViewController
{
    MISSING_TYPE *onDoneAction;	// 8 = 0x8
    MISSING_TYPE *previousNFCConfig;	// 24 = 0x18
    MISSING_TYPE *coalescer;	// 32 = 0x20
    MISSING_TYPE *nfcConfig;	// 40 = 0x28
    MISSING_TYPE *response;	// 48 = 0x30
    MISSING_TYPE *responseHandler;	// 64 = 0x40
    MISSING_TYPE *uiStartTicks;	// 80 = 0x50
    MISSING_TYPE *bigBtn;	// 88 = 0x58
    MISSING_TYPE *btnTitle;	// 96 = 0x60
    MISSING_TYPE *defaultBtnTitle;	// 112 = 0x70
    MISSING_TYPE *numberLbl;	// 128 = 0x80
    MISSING_TYPE *msgLbl;	// 136 = 0x88
    MISSING_TYPE *titleLabel;	// 144 = 0x90
    MISSING_TYPE *connectingLabel;	// 152 = 0x98
    MISSING_TYPE *spinner;	// 160 = 0xa0
    MISSING_TYPE *player;	// 168 = 0xa8
    MISSING_TYPE *heightConstraint;	// 176 = 0xb0
    MISSING_TYPE *subviewsToRemoveOnUpdate;	// 184 = 0xb8
}

- (void).cxx_destruct;	// IMP=0x00400000000452f0
- (id)initWithCoder:(id)arg1;	// IMP=0x0010000000045290
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;	// IMP=0x0010000000044ff0
- (id)initWithMainController:(id)arg1;	// IMP=0x0010000000044d20
- (void)_dismissX;	// IMP=0x0010000000044a90
- (void)_dismiss;	// IMP=0x0010000000044a60
- (void)contactPressed;	// IMP=0x00100000000447d0
- (void)viewDidDisappear:(_Bool)arg1;	// IMP=0x00100000000435b0
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0010000000040400

@end

