//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString, UIActivityIndicatorView, UIButton, UIImageView, UILabel, UIView;

@interface iOSSetupStartViewController
{
    UIButton *_dismissButton;	// 32 = 0x20
    UILabel *_titleLabel;	// 40 = 0x28
    UILabel *_infoLabel;	// 48 = 0x30
    UIImageView *_imageView;	// 56 = 0x38
    UIView *_progressView;	// 64 = 0x40
    UIActivityIndicatorView *_progressSpinner;	// 72 = 0x48
    UILabel *_progressLabel;	// 80 = 0x50
    UIButton *_startButton;	// 88 = 0x58
    _Bool _started;	// 96 = 0x60
    _Bool _autoStart;	// 97 = 0x61
}

- (void).cxx_destruct;	// IMP=0x002000000015183a
@property(nonatomic) _Bool autoStart; // @synthesize autoStart=_autoStart;
- (void)handleTapOutsideView:(id)arg1;	// IMP=0x0010000000151792
- (void)handleStartButton:(id)arg1;	// IMP=0x00100000001514f4
- (void)handleDeviceSetupNotification:(id)arg1;	// IMP=0x0010000000151292
- (void)handleDismissButton:(id)arg1;	// IMP=0x001000000015120a
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;	// IMP=0x0010000000151176
- (_Bool)_canShowWhileLocked;	// IMP=0x001000000015116e
- (void)viewDidDisappear:(_Bool)arg1;	// IMP=0x00100000001510a0
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x00100000001507ec

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

