//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSArray, NSString, SFAppContent, SVSSubCredentialActivationStartViewController, UIImage, UINavigationController, UIStoryboard;

@interface SubCredentialActivationMainController
{
    _Bool _activated;	// 24 = 0x18
    _Bool _appeared;	// 25 = 0x19
    NSString *_appName;	// 32 = 0x20
    UIImage *_appIconImage;	// 40 = 0x28
    _Bool _dismissed;	// 48 = 0x30
    UIStoryboard *_storyboard;	// 56 = 0x38
    SVSSubCredentialActivationStartViewController *_vcStart;	// 64 = 0x40
    _Bool _appInfoDownloadEnabled;	// 72 = 0x48
    SFAppContent *_appContent;	// 80 = 0x50
    NSArray *_adamIDs;	// 88 = 0x58
    NSString *_appStoreURL;	// 96 = 0x60
    NSString *_cardSubtitle;	// 104 = 0x68
    NSString *_cardTitle;	// 112 = 0x70
    NSString *_issuerID;	// 120 = 0x78
    NSString *_launchURL;	// 128 = 0x80
    UINavigationController *_proxCardNavigationController;	// 136 = 0x88
}

+ (_Bool)_isSecureForRemoteViewService;	// IMP=0x002000000018c78e
- (void).cxx_destruct;	// IMP=0x002000000018c4ea
@property(retain, nonatomic) UINavigationController *proxCardNavigationController; // @synthesize proxCardNavigationController=_proxCardNavigationController;
@property(copy, nonatomic) NSString *launchURL; // @synthesize launchURL=_launchURL;
@property(copy, nonatomic) NSString *issuerID; // @synthesize issuerID=_issuerID;
@property(copy, nonatomic) NSString *cardTitle; // @synthesize cardTitle=_cardTitle;
@property(copy, nonatomic) NSString *cardSubtitle; // @synthesize cardSubtitle=_cardSubtitle;
@property(copy, nonatomic) NSString *appStoreURL; // @synthesize appStoreURL=_appStoreURL;
@property(nonatomic) _Bool appInfoDownloadEnabled; // @synthesize appInfoDownloadEnabled=_appInfoDownloadEnabled;
@property(copy, nonatomic) NSArray *adamIDs; // @synthesize adamIDs=_adamIDs;
@property(retain, nonatomic) SFAppContent *appContent; // @synthesize appContent=_appContent;
- (void)proxCardFlowDidDismiss;	// IMP=0x001000000018c39d
- (void)dismissAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000018c1e4
- (void)dismiss:(int)arg1;	// IMP=0x001000000018c16f
- (void)viewDidDisappear:(_Bool)arg1;	// IMP=0x001000000018c071
- (void)viewDidAppear:(_Bool)arg1;	// IMP=0x001000000018bfd2
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x001000000018bf5b
- (void)viewUpdateAppInfo;	// IMP=0x001000000018bf0b
- (void)viewPresentStartViewControllerIfReady;	// IMP=0x001000000018bdeb
- (void)viewFetchContent;	// IMP=0x001000000018bc6b
- (unsigned long long)supportedInterfaceOrientations;	// IMP=0x001000000018bba3
- (void)configureWithContext:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000018af21
- (_Bool)_canShowWhileLocked;	// IMP=0x001000000018af19

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

