//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface SIKGPhones
{
}

+ (id)labels;	// IMP=0x0040000000027afe
+ (Class)nodeClass;	// IMP=0x0010000000027aed
- (void)enumeratePhonesInGraph:(id)arg1 usingBlock:(CDUnknownBlockType)arg2;	// IMP=0x0040000000027d37
- (id)initWithPhone:(id)arg1 inGraph:(id)arg2;	// IMP=0x0010000000027bb8

@end

