//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <MediaRemote/MRDeviceInfo.h>

@interface MRDeviceInfo (Provider)
+ (id)_readDeviceInfo;	// IMP=0x001000000004cfaa
+ (void)_writeDeviceInfo:(id)arg1 toPath:(id)arg2;	// IMP=0x001000000004ce54
+ (id)_readLegacyDeviceInfoIdentifier;	// IMP=0x001000000004cdab
+ (id)_deviceInfoArchiveClasses;	// IMP=0x001000000004ccf0
+ (id)_deviceInfoFilePath;	// IMP=0x001000000004ccaa
+ (id)networkIdentifier;	// IMP=0x001000000004cc36
+ (id)clusteredDevices;	// IMP=0x001000000004c906
+ (id)_discoverySession;	// IMP=0x001000000004c89c
+ (id)currentDeviceInfo;	// IMP=0x001000000004ba17
@end

