//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, MRCompanionLinkClient, NSMutableArray;
@protocol MRDRapportRemoteControlServiceDelegate;

@interface MRDRapportRemoteControlService : NSObject
{
    MISSING_TYPE *_workerQueue;	// 8 = 0x8
    id <MRDRapportRemoteControlServiceDelegate> _delegate;	// 16 = 0x10
    MRCompanionLinkClient *_client;	// 24 = 0x18
    NSMutableArray *_connections;	// 32 = 0x20
}

+ (void)_writeConnectionRecordsToDisk:(id)arg1;	// IMP=0x002000000002ae7f
+ (id)_readConnectionRecordsFromDisk;	// IMP=0x001000000002ad52
+ (id)userDefaults;	// IMP=0x0010000000029a11
- (void).cxx_destruct;	// IMP=0x002000000002b09c
@property(retain, nonatomic) NSMutableArray *connections; // @synthesize connections=_connections;
@property(retain, nonatomic) MRCompanionLinkClient *client; // @synthesize client=_client;
@property(nonatomic) __weak id <MRDRapportRemoteControlServiceDelegate> delegate; // @synthesize delegate=_delegate;
- (void)_resetPersistedConnections;	// IMP=0x001000000002aa0d
- (void)_persistConnectionRecordsToDisk;	// IMP=0x001000000002a997
- (void)_onWorkerQueue_disconnectRemoteControlChannelsWithError:(id)arg1 predicate:(CDUnknownBlockType)arg2;	// IMP=0x001000000002a624
- (void)_onWorkerQueue_disconnectRemoteControlChannelForSource:(id)arg1 destination:(id)arg2 session:(id)arg3;	// IMP=0x001000000002a424
- (void)_onWorkerQueue_disconnectAllRemoteControlChannels;	// IMP=0x001000000002a3eb
- (void)_onWorkerQueue_connectRemoteControlChannelForSource:(id)arg1 destination:(id)arg2 destinationGroupUID:(id)arg3 session:(id)arg4 name:(id)arg5;	// IMP=0x0010000000029c9a
- (id)_connectionForSource:(id)arg1 destination:(id)arg2 session:(id)arg3;	// IMP=0x0010000000029a89
- (void)stop;	// IMP=0x0010000000029a83
- (void)start;	// IMP=0x0010000000029a7d
- (id)init;	// IMP=0x0010000000028f21

@end

