//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UICollectionViewCell.h>

@class UIImageView, UILabel, UIView;

@interface COSDiscoverCell : UICollectionViewCell
{
    double _preferredWidth;	// 8 = 0x8
    UIImageView *_heroImageView;	// 16 = 0x10
    UIView *_trayView;	// 24 = 0x18
    UILabel *_titleLabel;	// 32 = 0x20
    UILabel *_subtitleLabel;	// 40 = 0x28
    UIImageView *_subtitleImage;	// 48 = 0x30
    UIView *_divider;	// 56 = 0x38
}

+ (id)reuseIdentifier;	// IMP=0x004000000010f36d
- (void).cxx_destruct;	// IMP=0x0020000000110650
@property(retain, nonatomic) UIView *divider; // @synthesize divider=_divider;
@property(retain, nonatomic) UIImageView *subtitleImage; // @synthesize subtitleImage=_subtitleImage;
@property(retain, nonatomic) UILabel *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIView *trayView; // @synthesize trayView=_trayView;
@property(retain, nonatomic) UIImageView *heroImageView; // @synthesize heroImageView=_heroImageView;
@property(nonatomic) double preferredWidth; // @synthesize preferredWidth=_preferredWidth;
- (id)preferredLayoutAttributesFittingAttributes:(id)arg1;	// IMP=0x00100000001104a0
- (void)setHighlighted:(_Bool)arg1;	// IMP=0x0010000000110419
- (void)setImage:(id)arg1 title:(id)arg2 subtitle:(id)arg3 wantsCellDivider:(_Bool)arg4;	// IMP=0x001000000011033a
- (id)_subtitleLabelFont;	// IMP=0x0010000000110317
- (id)_titleLabelFont;	// IMP=0x00100000001102f4
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x001000000010f37a

@end

