//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface COSiTunesStoreAuthController : NSObject
{
}

+ (void)repairDialogsForActiveDeviceWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0040000000109a4c
+ (void)saveToPairedDeviceiTunesStoreAccount:(id)arg1 fromAccountStore:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0010000000109925
+ (id)iTunesStoreAccountInAccountStore:(id)arg1;	// IMP=0x00100000001098d4
+ (id)altDSIDForiTunesStoreAccount:(id)arg1;	// IMP=0x0010000000109862
+ (id)DSIDForiTunesStoreAccount:(id)arg1;	// IMP=0x00100000001097f0
+ (id)usernameForiTunesStoreAccount:(id)arg1;	// IMP=0x00100000001097db

@end

