//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableDictionary;

@interface COSInternalPairingDashboardModel : NSObject
{
    _Bool _tinker;	// 8 = 0x8
    NSMutableDictionary *_eventGuide;	// 16 = 0x10
    NSArray *_eventNames;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x00200000000d4a75
@property(nonatomic) _Bool tinker; // @synthesize tinker=_tinker;
@property(retain, nonatomic) NSArray *eventNames; // @synthesize eventNames=_eventNames;
@property(retain, nonatomic) NSMutableDictionary *eventGuide; // @synthesize eventGuide=_eventGuide;
- (id)eventSummaryForKey:(id)arg1;	// IMP=0x00100000000d49aa
- (id)changedIndicesForGenericPairingEvent:(id)arg1 andValue:(id)arg2;	// IMP=0x00100000000d4666
- (id)changedIndicesForPairingBegins:(id)arg1 andValue:(id)arg2;	// IMP=0x00100000000d44f6
- (id)changedIndicesForPushedController:(id)arg1 andValue:(id)arg2;	// IMP=0x00100000000d420a
- (void)_checkIfTinker;	// IMP=0x00100000000d416f
- (id)updateEvent:(id)arg1;	// IMP=0x00100000000d3e5b
- (id)pairingEvents;	// IMP=0x00100000000d3c64
- (id)_tinkerPairingEventList;	// IMP=0x00100000000d3b84
- (id)_classicPairingEventList;	// IMP=0x00100000000d3aba
- (void)populateEventGuide;	// IMP=0x00100000000d3826
- (id)init;	// IMP=0x00100000000d37a6

@end

