//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <PassKitUI/PKPaymentSetupAssistantController.h>

@interface COSPaymentSetupAssistantController : PKPaymentSetupAssistantController
{
}

+ (id)passLibraryDataProvider;	// IMP=0x0040000000085bca
+ (_Bool)passkitFlowNeedsToRun:(unsigned long long *)arg1;	// IMP=0x0010000000085aad
+ (id)paymentSetupControllerContext;	// IMP=0x0010000000085a46
- (id)initWithDelegate:(id)arg1;	// IMP=0x0040000000085991

@end

