//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIViewController.h>

@class COSAppInstallationController, COSPartnerAppAMSDelegate, MISSING_TYPE, NSString, UIButton, UIImageView, UILabel;
@protocol COSBuddyControllerDelegate;

@interface COSPartnerAppInstallChoiceViewController : UIViewController
{
    id <COSBuddyControllerDelegate> _delegate;	// 8 = 0x8
    UIImageView *_victoryLogoFloating;	// 16 = 0x10
    UILabel *_titleLabel;	// 24 = 0x18
    UILabel *_descriptionLabel;	// 32 = 0x20
    UIImageView *_backgroundView;	// 40 = 0x28
    UIButton *_acceptButton;	// 48 = 0x30
    UIButton *_skipButton;	// 56 = 0x38
    COSAppInstallationController *_installController;	// 64 = 0x40
    COSPartnerAppAMSDelegate *_amsDelegate;	// 72 = 0x48
}

+ (unsigned long long)didSkipInstallEvent;	// IMP=0x00200000000ea78b
+ (unsigned long long)didInstallEvent;	// IMP=0x00100000000ea6ea
+ (unsigned long long)wasNotInstalledEvent;	// IMP=0x00100000000ea649
+ (unsigned long long)wasInstalledEvent;	// IMP=0x00100000000ea5a8
+ (long long)storeIdentifier;	// IMP=0x00100000000ea507
+ (id)bundleIdentifier;	// IMP=0x00100000000ea466
+ (id)minimumAppVersion;	// IMP=0x00100000000ea3c5
+ (id)bundleExtensionIdentifier;	// IMP=0x00100000000ea324
- (void).cxx_destruct;	// IMP=0x00200000000ec2d8
@property(retain, nonatomic) COSPartnerAppAMSDelegate *amsDelegate; // @synthesize amsDelegate=_amsDelegate;
@property(retain, nonatomic) COSAppInstallationController *installController; // @synthesize installController=_installController;
@property(retain, nonatomic) UIButton *skipButton; // @synthesize skipButton=_skipButton;
@property(retain, nonatomic) UIButton *acceptButton; // @synthesize acceptButton=_acceptButton;
@property(retain, nonatomic) UIImageView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) UILabel *descriptionLabel; // @synthesize descriptionLabel=_descriptionLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *victoryLogoFloating; // @synthesize victoryLogoFloating=_victoryLogoFloating;
@property(nonatomic) __weak id <COSBuddyControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)appIsAvailableStateDidChange:(unsigned long long)arg1;	// IMP=0x00100000000ec0b8
- (void)didCompleteInstallationWithSuccess:(_Bool)arg1;	// IMP=0x00100000000ebfec
- (void)didBeginInstallationWithSuccess:(_Bool)arg1;	// IMP=0x00100000000ebeaf
- (void)didInitiatePurchase;	// IMP=0x00100000000ebe21
- (void)setButtonEnabled:(_Bool)arg1;	// IMP=0x00100000000ebdd3
- (void)selectedSkipUpdate:(id)arg1;	// IMP=0x00100000000ebd97
- (void)selectedUpdate:(id)arg1;	// IMP=0x00100000000ebd5f
- (void)selectedContinue:(id)arg1;	// IMP=0x00100000000ebd23
- (void)selectedInstallLater:(id)arg1;	// IMP=0x00100000000ebcb2
- (void)selectedInstall:(id)arg1;	// IMP=0x00100000000ebc45
- (void)viewDidLayoutSubviews;	// IMP=0x00100000000eb5e5
- (void)updateControllerState;	// IMP=0x00100000000eadd3
- (MISSING_TYPE *)viewDidLoad;	// IMP=0x00100000000ea88b
- (_Bool)isInstalledOrInstalling;	// IMP=0x00100000000ea849
- (_Bool)isAlreadyInstalled;	// IMP=0x00100000000ea82c
- (id)installationButtonName;	// IMP=0x00100000000ea283
- (id)backgroundImageFileName;	// IMP=0x00100000000ea1e2
- (id)floatingHeaderImage;	// IMP=0x00100000000ea141
- (id)detailString;	// IMP=0x00100000000ea0a0
- (id)titleString;	// IMP=0x00100000000e9fff
- (void)viewDidDisappear:(_Bool)arg1;	// IMP=0x00100000000e9f7f
- (void)viewWillDisappear:(_Bool)arg1;	// IMP=0x00100000000e9ef4
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x00100000000e9e29
- (void)dealloc;	// IMP=0x00100000000e9ddd
- (id)init;	// IMP=0x00100000000e9ca2

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

