//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class BRRTCPairingReportManager, COSActivationResponseManager, COSAppleIDAuthController, COSAppleIDSilentSignInController, COSBuddyNavigationController, COSInternalPairingDashboardViewController, COSPairingTypeSelectionViewController, COSPasscodeChoiceViewController, COSRegistryDispatcher, COSResumePairingStateController, COSWatchKitAppChoiceUpdater, COSWatchUnpairInstructionsController, COSWristAttributeVisualDetector, FAFamilyCircle, FAFamilyMember, FAProfilePictureStore, NBBackup, NRDevice, NSArray, NSDate, NSMutableArray, NSString, UIActivityIndicatorView;
@protocol COSBuddyController, OS_dispatch_source;

@interface COSSetupController : NSObject
{
    _Bool _hasAddedPasscode;	// 8 = 0x8
    _Bool _hasSignedInToiCloud;	// 9 = 0x9
    _Bool _hasSignedInToiMessage;	// 10 = 0xa
    _Bool _hasSignedInToFaceTime;	// 11 = 0xb
    _Bool _hasSignedInToiTunesStore;	// 12 = 0xc
    _Bool _hasCombinedIDSSignInFailed;	// 13 = 0xd
    _Bool _hasStartedSilentAppleIDSignIn;	// 14 = 0xe
    _Bool _waitingForSilentiCloudSignInToComplete;	// 15 = 0xf
    _Bool _waitingForSilentiMessageSignInToComplete;	// 16 = 0x10
    _Bool _waitingForSilentFaceTimeSignInToComplete;	// 17 = 0x11
    _Bool _waitingForSilentiTunesStoreSignInToComplete;	// 18 = 0x12
    _Bool _silentiCloudSignInWasSuccessful;	// 19 = 0x13
    _Bool _silentiMessageSignInWasSuccessful;	// 20 = 0x14
    _Bool _silentFaceTimeSignInWasSuccessful;	// 21 = 0x15
    _Bool _silentiTunesStoreSignInWasSuccessful;	// 22 = 0x16
    _Bool _updateInSetupFlowHasCompleted;	// 23 = 0x17
    _Bool _alreadyStartPostActivationCompatiblePairingBackgroundTasks;	// 24 = 0x18
    _Bool _didWaitAfterRevLockUpdate;	// 25 = 0x19
    _Bool _isObservingLockStatusNotificationForRevLockUpdate;	// 26 = 0x1a
    _Bool _isDeKOTAFlow;	// 27 = 0x1b
    _Bool _didAllowTinkerHealthSharing;	// 28 = 0x1c
    _Bool _expressMode;	// 29 = 0x1d
    _Bool _wristChoicesDetected;	// 30 = 0x1e
    _Bool _didAllowTinkerLocationPermissions;	// 31 = 0x1f
    _Bool _isPreliminaryControllerActive;	// 32 = 0x20
    COSActivationResponseManager *_activationManager;	// 40 = 0x28
    COSAppleIDAuthController *_tinkerAuthenticationController;	// 48 = 0x30
    COSBuddyNavigationController *_navigationController;	// 56 = 0x38
    NSMutableArray *_buddyControllers;	// 64 = 0x40
    BRRTCPairingReportManager *_pairingReportManager;	// 72 = 0x48
    COSPairingTypeSelectionViewController *_pairingTypeSelectionController;	// 80 = 0x50
    COSPasscodeChoiceViewController *_passcodeChoiceController;	// 88 = 0x58
    id <COSBuddyController>;	// 96 = 0x60
    id <COSBuddyController> _nextControllerAfterHold;	// 104 = 0x68
    UIActivityIndicatorView *_customActivityIndicator;	// 112 = 0x70
    COSAppleIDSilentSignInController *_silentSignInController;	// 120 = 0x78
    NSDate *_revLockDelayAfterUpdateDate;	// 128 = 0x80
    NSObject<OS_dispatch_source> *_revLockDelayAfterUpdateTimer;	// 136 = 0x88
    COSRegistryDispatcher *_alreadyPairedDispatcher;	// 144 = 0x90
    CDUnknownBlockType _holdWaitScreenBlock;	// 152 = 0x98
    CDUnknownBlockType _deferredHoldBlock;	// 160 = 0xa0
    NSObject<OS_dispatch_source> *_holdWaitScreenPresentationTimer;	// 168 = 0xa8
    COSWristAttributeVisualDetector *_detector;	// 176 = 0xb0
    COSWatchUnpairInstructionsController *_unpairInstructions;	// 184 = 0xb8
    COSWatchKitAppChoiceUpdater *_appChoiceUpdater;	// 192 = 0xc0
    NRDevice *_scannedDevice;	// 200 = 0xc8
    unsigned long long _mode;	// 208 = 0xd0
    unsigned long long _forcedSoftwareUpdateCheckReason;	// 216 = 0xd8
    NBBackup *_backupRestoredFrom;	// 224 = 0xe0
    NRDevice *_deviceRestoredFrom;	// 232 = 0xe8
    NRDevice *_expressModeDevice;	// 240 = 0xf0
    COSInternalPairingDashboardViewController *_internalDashboardController;	// 248 = 0xf8
    NSString *_tinkerUserName;	// 256 = 0x100
    FAFamilyMember *_tinkerFamilyMember;	// 264 = 0x108
    FAFamilyMember *_organizerFamilyMember;	// 272 = 0x110
    FAFamilyMember *_pairingParentFamilyMember;	// 280 = 0x118
    FAFamilyCircle *_familyCircle;	// 288 = 0x120
    FAProfilePictureStore *_profilePictureStore;	// 296 = 0x128
    NSString *_tinkerSignInId;	// 304 = 0x130
    NSArray *_expressModeControllers;	// 312 = 0x138
    COSResumePairingStateController *_resumePairingController;	// 320 = 0x140
}

+ (id)classicBuddyFlowMapping;	// IMP=0x00200000000900ff
+ (id)bundleFlowMapping;	// IMP=0x001000000008fc00
+ (id)tinkerBuddyFlowMapping;	// IMP=0x001000000008ee51
+ (void)addBundlesToTinkerFlowMapping:(id)arg1;	// IMP=0x001000000008e3bc
+ (id)debugTinkerBuddyFlowMapping;	// IMP=0x001000000008e3aa
+ (id)buddyFlowMapping;	// IMP=0x001000000008e327
+ (double)delayForRevLockDuringPairingBeforeEnteringConfigureState;	// IMP=0x001000000008cd3a
+ (_Bool)isDeviceUnlocked;	// IMP=0x001000000008cd32
+ (id)loadBundleControllerClasses;	// IMP=0x001000000008b2d2
- (void).cxx_destruct;	// IMP=0x002000000009796e
@property(retain, nonatomic) COSResumePairingStateController *resumePairingController; // @synthesize resumePairingController=_resumePairingController;
@property(nonatomic) _Bool isPreliminaryControllerActive; // @synthesize isPreliminaryControllerActive=_isPreliminaryControllerActive;
@property(copy, nonatomic) NSArray *expressModeControllers; // @synthesize expressModeControllers=_expressModeControllers;
@property(nonatomic) _Bool didAllowTinkerLocationPermissions; // @synthesize didAllowTinkerLocationPermissions=_didAllowTinkerLocationPermissions;
@property(copy, nonatomic) NSString *tinkerSignInId; // @synthesize tinkerSignInId=_tinkerSignInId;
@property(retain, nonatomic) FAProfilePictureStore *profilePictureStore; // @synthesize profilePictureStore=_profilePictureStore;
@property(retain, nonatomic) FAFamilyCircle *familyCircle; // @synthesize familyCircle=_familyCircle;
@property(retain, nonatomic) FAFamilyMember *pairingParentFamilyMember; // @synthesize pairingParentFamilyMember=_pairingParentFamilyMember;
@property(retain, nonatomic) FAFamilyMember *organizerFamilyMember; // @synthesize organizerFamilyMember=_organizerFamilyMember;
@property(retain, nonatomic) FAFamilyMember *tinkerFamilyMember; // @synthesize tinkerFamilyMember=_tinkerFamilyMember;
@property(copy, nonatomic) NSString *tinkerUserName; // @synthesize tinkerUserName=_tinkerUserName;
@property(retain, nonatomic) COSInternalPairingDashboardViewController *internalDashboardController; // @synthesize internalDashboardController=_internalDashboardController;
@property(nonatomic) _Bool wristChoicesDetected; // @synthesize wristChoicesDetected=_wristChoicesDetected;
@property(nonatomic) NRDevice *expressModeDevice; // @synthesize expressModeDevice=_expressModeDevice;
@property(nonatomic) _Bool expressMode; // @synthesize expressMode=_expressMode;
@property(nonatomic) NRDevice *deviceRestoredFrom; // @synthesize deviceRestoredFrom=_deviceRestoredFrom;
@property(nonatomic) NBBackup *backupRestoredFrom; // @synthesize backupRestoredFrom=_backupRestoredFrom;
@property(nonatomic) unsigned long long forcedSoftwareUpdateCheckReason; // @synthesize forcedSoftwareUpdateCheckReason=_forcedSoftwareUpdateCheckReason;
@property(nonatomic) unsigned long long mode; // @synthesize mode=_mode;
@property(retain, nonatomic) NRDevice *scannedDevice; // @synthesize scannedDevice=_scannedDevice;
@property(retain, nonatomic) COSWatchKitAppChoiceUpdater *appChoiceUpdater; // @synthesize appChoiceUpdater=_appChoiceUpdater;
@property(retain, nonatomic) COSWatchUnpairInstructionsController *unpairInstructions; // @synthesize unpairInstructions=_unpairInstructions;
@property(nonatomic) _Bool didAllowTinkerHealthSharing; // @synthesize didAllowTinkerHealthSharing=_didAllowTinkerHealthSharing;
@property(nonatomic) _Bool isDeKOTAFlow; // @synthesize isDeKOTAFlow=_isDeKOTAFlow;
@property(retain, nonatomic) COSWristAttributeVisualDetector *detector; // @synthesize detector=_detector;
@property(retain, nonatomic) NSObject<OS_dispatch_source> *holdWaitScreenPresentationTimer; // @synthesize holdWaitScreenPresentationTimer=_holdWaitScreenPresentationTimer;
@property(copy, nonatomic) CDUnknownBlockType deferredHoldBlock; // @synthesize deferredHoldBlock=_deferredHoldBlock;
@property(copy, nonatomic) CDUnknownBlockType holdWaitScreenBlock; // @synthesize holdWaitScreenBlock=_holdWaitScreenBlock;
@property(retain, nonatomic) COSRegistryDispatcher *alreadyPairedDispatcher; // @synthesize alreadyPairedDispatcher=_alreadyPairedDispatcher;
@property(nonatomic) _Bool isObservingLockStatusNotificationForRevLockUpdate; // @synthesize isObservingLockStatusNotificationForRevLockUpdate=_isObservingLockStatusNotificationForRevLockUpdate;
@property(nonatomic) _Bool didWaitAfterRevLockUpdate; // @synthesize didWaitAfterRevLockUpdate=_didWaitAfterRevLockUpdate;
@property(retain, nonatomic) NSObject<OS_dispatch_source> *revLockDelayAfterUpdateTimer; // @synthesize revLockDelayAfterUpdateTimer=_revLockDelayAfterUpdateTimer;
@property(retain, nonatomic) NSDate *revLockDelayAfterUpdateDate; // @synthesize revLockDelayAfterUpdateDate=_revLockDelayAfterUpdateDate;
@property(nonatomic) _Bool alreadyStartPostActivationCompatiblePairingBackgroundTasks; // @synthesize alreadyStartPostActivationCompatiblePairingBackgroundTasks=_alreadyStartPostActivationCompatiblePairingBackgroundTasks;
@property(nonatomic) _Bool updateInSetupFlowHasCompleted; // @synthesize updateInSetupFlowHasCompleted=_updateInSetupFlowHasCompleted;
@property(nonatomic) _Bool silentiTunesStoreSignInWasSuccessful; // @synthesize silentiTunesStoreSignInWasSuccessful=_silentiTunesStoreSignInWasSuccessful;
@property(nonatomic) _Bool silentFaceTimeSignInWasSuccessful; // @synthesize silentFaceTimeSignInWasSuccessful=_silentFaceTimeSignInWasSuccessful;
@property(nonatomic) _Bool silentiMessageSignInWasSuccessful; // @synthesize silentiMessageSignInWasSuccessful=_silentiMessageSignInWasSuccessful;
@property(nonatomic) _Bool silentiCloudSignInWasSuccessful; // @synthesize silentiCloudSignInWasSuccessful=_silentiCloudSignInWasSuccessful;
@property(nonatomic) _Bool waitingForSilentiTunesStoreSignInToComplete; // @synthesize waitingForSilentiTunesStoreSignInToComplete=_waitingForSilentiTunesStoreSignInToComplete;
@property(nonatomic) _Bool waitingForSilentFaceTimeSignInToComplete; // @synthesize waitingForSilentFaceTimeSignInToComplete=_waitingForSilentFaceTimeSignInToComplete;
@property(nonatomic) _Bool waitingForSilentiMessageSignInToComplete; // @synthesize waitingForSilentiMessageSignInToComplete=_waitingForSilentiMessageSignInToComplete;
@property(nonatomic) _Bool waitingForSilentiCloudSignInToComplete; // @synthesize waitingForSilentiCloudSignInToComplete=_waitingForSilentiCloudSignInToComplete;
@property(nonatomic) _Bool hasStartedSilentAppleIDSignIn; // @synthesize hasStartedSilentAppleIDSignIn=_hasStartedSilentAppleIDSignIn;
@property(retain, nonatomic) COSAppleIDSilentSignInController *silentSignInController; // @synthesize silentSignInController=_silentSignInController;
@property(retain, nonatomic) UIActivityIndicatorView *customActivityIndicator; // @synthesize customActivityIndicator=_customActivityIndicator;
@property(retain, nonatomic) id <COSBuddyController> nextControllerAfterHold; // @synthesize nextControllerAfterHold=_nextControllerAfterHold;
@property(retain, nonatomic) id <COSBuddyController> controllerDisplayedWhileOnHold; // @synthesize controllerDisplayedWhileOnHold=_controllerDisplayedWhileOnHold;
@property(retain, nonatomic) COSPasscodeChoiceViewController *passcodeChoiceController; // @synthesize passcodeChoiceController=_passcodeChoiceController;
@property(retain, nonatomic) COSPairingTypeSelectionViewController *pairingTypeSelectionController; // @synthesize pairingTypeSelectionController=_pairingTypeSelectionController;
@property(retain, nonatomic) BRRTCPairingReportManager *pairingReportManager; // @synthesize pairingReportManager=_pairingReportManager;
@property(retain, nonatomic) NSMutableArray *buddyControllers; // @synthesize buddyControllers=_buddyControllers;
@property(readonly, nonatomic) COSBuddyNavigationController *navigationController; // @synthesize navigationController=_navigationController;
@property(nonatomic) _Bool hasCombinedIDSSignInFailed; // @synthesize hasCombinedIDSSignInFailed=_hasCombinedIDSSignInFailed;
@property(nonatomic) _Bool hasSignedInToiTunesStore; // @synthesize hasSignedInToiTunesStore=_hasSignedInToiTunesStore;
@property(nonatomic) _Bool hasSignedInToFaceTime; // @synthesize hasSignedInToFaceTime=_hasSignedInToFaceTime;
@property(nonatomic) _Bool hasSignedInToiMessage; // @synthesize hasSignedInToiMessage=_hasSignedInToiMessage;
@property(nonatomic) _Bool hasSignedInToiCloud; // @synthesize hasSignedInToiCloud=_hasSignedInToiCloud;
@property(nonatomic) _Bool hasAddedPasscode; // @synthesize hasAddedPasscode=_hasAddedPasscode;
- (void)tellAppConduitToInstallAllApps;	// IMP=0x0010000000097405
@property(readonly, nonatomic) COSAppleIDAuthController *tinkerAuthenticationController; // @synthesize tinkerAuthenticationController=_tinkerAuthenticationController;
- (id)visualDetector;	// IMP=0x00100000000973b9
- (void)prewarmVisualDetector;	// IMP=0x00100000000972e9
- (void)appleIDSilentSignInControllerSignedAccountType:(unsigned long long)arg1 withSuccess:(_Bool)arg2;	// IMP=0x00100000000970b3
- (void)completePairingMetricForAppTermination;	// IMP=0x0010000000097076
- (void)checkInWithPairingMetricForSignInState;	// IMP=0x0010000000097001
@property(readonly, nonatomic) COSActivationResponseManager *activationManager; // @synthesize activationManager=_activationManager;
- (void)saveCombinedPasswordBasediTunesStoreAccount:(id)arg1 fromAccountStore:(id)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x0010000000096d14
- (void)startSilentAppleIDSignIn;	// IMP=0x0010000000096afd
- (void)startPostActivationCompatiblePairingBackgroundTasks;	// IMP=0x00100000000969f4
- (void)finishedActivating:(id)arg1;	// IMP=0x00100000000964a5
- (void)activationServerResponded;	// IMP=0x0010000000096449
- (id)dashboardController;	// IMP=0x0010000000096437
- (unsigned int)state;	// IMP=0x001000000009642f
- (unsigned int)position;	// IMP=0x0010000000096427
- (void)_pushGizmoBuddyController:(id)arg1;	// IMP=0x0000000000096317
- (void)popViewController:(id)arg1;	// IMP=0x0010000000095b85
- (_Bool)_controllerShouldMirrorToGizmo:(id)arg1;	// IMP=0x00100000000959a1
- (void)showBusyIndicator:(_Bool)arg1;	// IMP=0x0010000000095818
- (void)popControllerAnimated:(_Bool)arg1;	// IMP=0x00100000000957f9
- (void)popRUIObject:(id)arg1 animated:(_Bool)arg2;	// IMP=0x001000000009563d
- (void)pushRUIObject:(id)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x00100000000950cf
- (void)gizmoDidFinishHealthSharingOptIn:(_Bool)arg1;	// IMP=0x0010000000095054
- (void)companionDidFinishHealthSharingOptIn:(_Bool)arg1;	// IMP=0x0010000000094fba
- (void)didBeginMigrationSync;	// IMP=0x0010000000094ea7
@property(readonly, nonatomic) _Bool isMigrating;
- (void)passcodeCreationComplete;	// IMP=0x0010000000094e24
- (void)passcodeCreationFailed;	// IMP=0x0010000000094d7f
- (void)promptWhetherToResetPairing:(id)arg1;	// IMP=0x001000000009454f
- (id)_titleForViewController:(id)arg1;	// IMP=0x0010000000094491
- (void)navigationController:(id)arg1 didShowViewController:(id)arg2 animated:(_Bool)arg3;	// IMP=0x00100000000942bf
- (id)navigationController:(id)arg1 animationControllerForOperation:(long long)arg2 fromViewController:(id)arg3 toViewController:(id)arg4;	// IMP=0x0010000000094248
- (void)buddyControllerWillPushNextControllerClass:(Class)arg1 outNextController:(id *)arg2 ontoNavigationController:(id)arg3;	// IMP=0x0010000000094139
- (id)topBuddyController;	// IMP=0x0010000000094123
- (id)popToBuddyControllerWithClass:(Class)arg1 animated:(_Bool)arg2;	// IMP=0x001000000009411b
- (void)buddyControllerDone:(id)arg1 nextControllerClass:(Class)arg2;	// IMP=0x0010000000094106
- (void)buddyControllerDone:(id)arg1;	// IMP=0x00100000000940ef
- (void)buddyControllerDone:(id)arg1 transitionToMode:(unsigned long long)arg2;	// IMP=0x00100000000940d1
- (void)buddyControllerCancelAnyHold;	// IMP=0x0010000000093f2f
- (void)buddyControllerReleaseHoldAndSkip:(id)arg1;	// IMP=0x0010000000093f18
- (void)buddyControllerReleaseHold:(id)arg1;	// IMP=0x0010000000093f04
- (_Bool)buddyControllerIsBeingHeldOff:(id)arg1;	// IMP=0x0010000000093ef7
- (void)postUserNotificationForController;	// IMP=0x0010000000093a88
- (_Bool)_shouldSkipForBetterTogether:(id)arg1;	// IMP=0x0010000000093a30
- (void)_buddyControllerReleaseHold:(id)arg1 andSkip:(_Bool)arg2;	// IMP=0x001000000009307c
- (void)cleanupHoldWaitTimer;	// IMP=0x0010000000092f7b
- (void)buddyControllerHold:(id)arg1 beforePresentingBuddyController:(id)arg2;	// IMP=0x00100000000922e4
- (void)_buddyControllerDone:(id)arg1 nextControllerClass:(Class)arg2 nextController:(id)arg3;	// IMP=0x0010000000091e01
- (void)blockGoingBackFromCurrentController;	// IMP=0x0010000000091c23
- (void)_transitionFromBuddyController:(id)arg1 toBuddyController:(id)arg2;	// IMP=0x0010000000091a60
- (void)_pushBuddyController:(id)arg1 ontoNavigationController:(id)arg2;	// IMP=0x0010000000091948
- (void)_pushBuddyController:(id)arg1;	// IMP=0x0010000000091934
- (id)_viewControllerForBuddyController:(id)arg1;	// IMP=0x00100000000918b4
- (id)_controllerForClass:(Class)arg1;	// IMP=0x00100000000915b0
- (void)_finishBuddy;	// IMP=0x001000000009143f
- (id)_controllerFollowingControllerClass:(Class)arg1;	// IMP=0x0010000000090dee
- (void)displayPairingFailureWatchAlreadyPairedToCompanion:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000008d853
- (void)updateAttemptCompleteOrUpToDate;	// IMP=0x001000000008d598
- (void)displayPairingFailureAlertForMessage:(id)arg1 title:(id)arg2 failureCode:(id)arg3 withCompletion:(CDUnknownBlockType)arg4;	// IMP=0x001000000008d1ec
- (id)_alertMessageForReason:(unsigned long long)arg1 andCode:(id)arg2;	// IMP=0x001000000008cf9c
- (void)displayPairingFailureAlertForReason:(unsigned long long)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x001000000008ce68
- (_Bool)shouldForceSoftwareUpdateCheck;	// IMP=0x001000000008cd78
- (void)displayUnsupportedWatchPairingAlertToBetterTogetherDeviceWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x001000000008cb15
- (void)promptWhetherToUpdateGizmo:(CDUnknownBlockType)arg1;	// IMP=0x001000000008c78c
- (void)displayUnsupportedTinkerHardwareFailure:(CDUnknownBlockType)arg1;	// IMP=0x001000000008c35f
- (void)displayCompanionTooOldPairingFailureAlertWithDismissalHandler:(CDUnknownBlockType)arg1;	// IMP=0x001000000008bf4f
- (void)displayWatchAppearsPairedOrOffAlert:(CDUnknownBlockType)arg1;	// IMP=0x001000000008bb18
- (void)displayUnpairingInstructions;	// IMP=0x001000000008ba78
@property(readonly, nonatomic) _Bool hasStartedPairing;
- (_Bool)canPairAgain;	// IMP=0x001000000008ba11
- (_Bool)isAlreadyPaired;	// IMP=0x001000000008b8e0
- (void)finalCleanup;	// IMP=0x001000000008b72b
- (void)dealloc;	// IMP=0x001000000008b66f
- (void)loadSetupBundle;	// IMP=0x001000000008b2b0
- (void)run;	// IMP=0x001000000008a602
- (void)enableMigration;	// IMP=0x0010000000089f8e
- (void)invalidateState;	// IMP=0x0010000000089d0e
- (void)reloadAppearance;	// IMP=0x0010000000089cd5
- (id)setupFlowUserInfo;	// IMP=0x0010000000089924
- (id)activePairingDevice;	// IMP=0x0010000000089908
- (id)initWithMode:(unsigned long long)arg1;	// IMP=0x00100000000895df
- (id)init;	// IMP=0x00100000000895c8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

