//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NRDevice, NSString, UIViewController;

@interface COSUnpairActionsHelperContext : NSObject
{
    _Bool _markAsMissing;	// 8 = 0x8
    UIViewController *_presentingViewController;	// 16 = 0x10
    NRDevice *_device;	// 24 = 0x18
    NSString *_activationLockRemovalTitle;	// 32 = 0x20
    NSString *_failureMessage;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x0020000000115026
@property(retain, nonatomic) NSString *failureMessage; // @synthesize failureMessage=_failureMessage;
@property(retain, nonatomic) NSString *activationLockRemovalTitle; // @synthesize activationLockRemovalTitle=_activationLockRemovalTitle;
@property(retain, nonatomic) NRDevice *device; // @synthesize device=_device;
@property(nonatomic) _Bool markAsMissing; // @synthesize markAsMissing=_markAsMissing;
@property(retain, nonatomic) UIViewController *presentingViewController; // @synthesize presentingViewController=_presentingViewController;

@end

