//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface MotionTuple : NSObject
{
    float _x;	// 8 = 0x8
    float _y;	// 12 = 0xc
    float _z;	// 16 = 0x10
}

+ (id)motionWithX:(float)arg1 andY:(float)arg2 andZ:(float)arg3;	// IMP=0x004000000005a31c
- (void);	// IMP=0x002000000005a3c9
@property(nonatomic) float z; // @synthesize z=_z;
@property(nonatomic) float y; // @synthesize y=_y;
@property(nonatomic) float x; // @synthesize x=_x;

@end

