//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface REDDaemon : NSObject
{
}

+ (void)run;	// IMP=0x004000000000b42b
+ (void)setup;	// IMP=0x001000000000b378

@end

