//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class PAApplication, PABridgedTCCIdentity;

@interface PALResolvedAccessorCacheKey : NSObject
{
    PAApplication *_accessor;	// 8 = 0x8
    PABridgedTCCIdentity *_clientProvidedIdentity;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0020000000003046
@property(readonly, nonatomic) PABridgedTCCIdentity *clientProvidedIdentity; // @synthesize clientProvidedIdentity=_clientProvidedIdentity;
@property(readonly, nonatomic) PAApplication *accessor; // @synthesize accessor=_accessor;
- (_Bool)isEqual:(id)arg1;	// IMP=0x0010000000002f4d
- (unsigned long long)hash;	// IMP=0x0010000000002f06
- (id)initWithAccessor:(id)arg1 clientProvidedIdentity:(id)arg2;	// IMP=0x0010000000002e6d

@end

