//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class LUIManagedDevicesViewController;

@interface LUIManagedDevicesNavigationController
{
    LUIManagedDevicesViewController *_managedDevicesViewController;	// 8 = 0x8
}

- (void).cxx_destruct;	// IMP=0x0020000000007381
@property(retain, nonatomic) LUIManagedDevicesViewController *managedDevicesViewController; // @synthesize managedDevicesViewController=_managedDevicesViewController;
- (void)doneButtonPressed:(id)arg1;	// IMP=0x0010000000007343
- (void)_setupNavigationItem;	// IMP=0x001000000000729d
- (id)initWithOrganizationName:(id)arg1;	// IMP=0x00100000000071f1

@end

