//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class UIButton, UILabel;

@interface LUIUserSwitchTestOngoingIndicatorView : UIView
{
    UILabel *_textLabel;	// 8 = 0x8
    UIButton *_cancelButton;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x0020000000010d2f
@property(retain, nonatomic) UIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(retain, nonatomic) UILabel *textLabel; // @synthesize textLabel=_textLabel;
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0010000000010813
- (id)init;	// IMP=0x00100000000107d5

@end

