//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface MCAirPlayPayloadHandler
{
}

+ (void)recomputeAirPlaySettings;	// IMP=0x00400000000750cd
- (void)unsetAside;	// IMP=0x00400000000750bb
- (void)remove;	// IMP=0x001000000007504f
- (void)setAside;	// IMP=0x001000000007503d
- (void)_removeDependency;	// IMP=0x0010000000074c16
- (void)_addDependency;	// IMP=0x00100000000747ef
- (_Bool)installWithInstaller:(id)arg1 options:(id)arg2 interactionClient:(id)arg3 outError:(id *)arg4;	// IMP=0x0010000000074398

@end

