//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface MCNetworkUsageRulesPayloadHandler
{
}

+ (id)internalErrorWithCode:(int)arg1 underlyingError:(id)arg2;	// IMP=0x0040000000022274
+ (id)internalErrorWithCode:(int)arg1;	// IMP=0x0010000000022260
- (void)remove;	// IMP=0x004000000002232f
- (void)unsetAside;	// IMP=0x0010000000022329
- (void)setAside;	// IMP=0x0010000000022323
- (_Bool)installWithInstaller:(id)arg1 options:(id)arg2 interactionClient:(id)arg3 outError:(id *)arg4;	// IMP=0x001000000002231b

@end

