//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface CDDPaths : NSObject
{
}

+ (id)userLocalKnowledgeDatabaseDirectory;	// IMP=0x004000000001dc9f
+ (id)peopleDatabaseDirectory;	// IMP=0x001000000001dbc3
+ (id)knowledgeDatabaseDirectory;	// IMP=0x001000000001dba3
+ (id)CDDConfigurationBundlePath;	// IMP=0x001000000001db45
+ (id)CDDConfigurationBundlePathDefault;	// IMP=0x001000000001db1e
+ (id)CDDUserDatabaseDirectory;	// IMP=0x001000000001db0c
+ (id)CDDDatabaseDirectory;	// IMP=0x001000000001daec
+ (id)simulatorSharedPathFor:(id)arg1;	// IMP=0x001000000001da26
+ (id)simulatorHomePathFor:(id)arg1;	// IMP=0x001000000001d9be
+ (id)simulatorSystemPathFor:(id)arg1 withEnvVar:(id)arg2;	// IMP=0x001000000001d8d7

@end

