//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIResponder.h>

@class NSString, UIWindow;

@interface AKUIServiceAppDelegate : UIResponder
{
}

- (void)applicationWillTerminate:(id)arg1;	// IMP=0x0020000000005e53
- (void)applicationDidBecomeActive:(id)arg1;	// IMP=0x0010000000005e4d
- (void)applicationWillEnterForeground:(id)arg1;	// IMP=0x0010000000005e47
- (void)applicationDidEnterBackground:(id)arg1;	// IMP=0x0010000000005e41
- (void)applicationWillResignActive:(id)arg1;	// IMP=0x0010000000005e3b
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;	// IMP=0x0010000000005e33

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(retain, nonatomic) UIWindow *window;

@end

