//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <CloudPhotoLibrary/CPLSyncSession.h>

@class CPLCloudKitRescheduler;

@interface CPLSyncSession (CPLCloudKit)
@property(readonly, nonatomic) CPLCloudKitRescheduler *cloudKitRescheduler;
- (void)createCloudKitReschedulerIfNcessary;	// IMP=0x001000000012590f
@end

