//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class LSRecordPromise, MIBundleContainer, MIClientConnection, MIDataContainer, MIStashedBundleContainer, NSArray, NSDictionary, NSMutableArray, NSString;

@interface MIReverter : NSObject
{
    _Bool _isLocked;	// 8 = 0x8
    NSDictionary *_receipt;	// 16 = 0x10
    LSRecordPromise *_recordPromise;	// 24 = 0x18
    MIClientConnection *_client;	// 32 = 0x20
    NSDictionary *_options;	// 40 = 0x28
    NSString *_bundleID;	// 48 = 0x30
    MIBundleContainer *_existingBundleContainer;	// 56 = 0x38
    MIStashedBundleContainer *_stashedContainer;	// 64 = 0x40
    MIBundleContainer *_bundleContainer;	// 72 = 0x48
    NSArray *_appExtensionBundles;	// 80 = 0x50
    MIDataContainer *_dataContainer;	// 88 = 0x58
    NSMutableArray *_appExtensionDataContainers;	// 96 = 0x60
}

+ (id)reverterForBundleIdentifier:(id)arg1 withOptions:(id)arg2 forClient:(id)arg3;	// IMP=0x004000000001dfc2
- (void).cxx_destruct;	// IMP=0x0020000000021347
@property(retain, nonatomic) NSMutableArray *appExtensionDataContainers; // @synthesize appExtensionDataContainers=_appExtensionDataContainers;
@property(retain, nonatomic) MIDataContainer *dataContainer; // @synthesize dataContainer=_dataContainer;
@property(retain, nonatomic) NSArray *appExtensionBundles; // @synthesize appExtensionBundles=_appExtensionBundles;
@property(retain, nonatomic) MIBundleContainer *bundleContainer; // @synthesize bundleContainer=_bundleContainer;
@property(retain, nonatomic) MIStashedBundleContainer *stashedContainer; // @synthesize stashedContainer=_stashedContainer;
@property(retain, nonatomic) MIBundleContainer *existingBundleContainer; // @synthesize existingBundleContainer=_existingBundleContainer;
@property(nonatomic) _Bool isLocked; // @synthesize isLocked=_isLocked;
@property(retain, nonatomic) NSString *bundleID; // @synthesize bundleID=_bundleID;
@property(copy, nonatomic) NSDictionary *options; // @synthesize options=_options;
@property(nonatomic) __weak MIClientConnection *client; // @synthesize client=_client;
@property(readonly, nonatomic) LSRecordPromise *recordPromise; // @synthesize recordPromise=_recordPromise;
@property(readonly, nonatomic) NSDictionary *receipt; // @synthesize receipt=_receipt;
- (_Bool)performRevertWithError:(id *)arg1;	// IMP=0x0010000000020aab
- (id)_launchServicesDictionariesWithError:(id *)arg1;	// IMP=0x0010000000020649
- (_Bool)_finalizeInstallationWithError:(id *)arg1;	// IMP=0x001000000001f7e2
- (_Bool)_refreshUUIDForContainer:(id)arg1 withError:(id *)arg2;	// IMP=0x001000000001f688
- (_Bool)_postFlightInstallationWithError:(id *)arg1;	// IMP=0x001000000001f4c4
- (_Bool)_postFlightAppExtensionsWithError:(id *)arg1;	// IMP=0x001000000001f020
- (_Bool)_performInstallationWithError:(id *)arg1;	// IMP=0x001000000001ee2d
- (_Bool)_validateAndEstablishLinkToParentContainer:(id *)arg1;	// IMP=0x001000000001ebe2
- (_Bool)_performVerificationWithError:(id *)arg1;	// IMP=0x001000000001e92f
- (id)_validateBundle:(id)arg1 error:(id *)arg2;	// IMP=0x001000000001e7b0
- (_Bool)_performPreflightWithError:(id *)arg1;	// IMP=0x001000000001e4f4
- (void)_fireCallbackWithStatus:(id)arg1;	// IMP=0x001000000001e482
- (void)_fireCallbackWithStatus:(id)arg1 percentComplete:(unsigned int)arg2;	// IMP=0x001000000001e40a
- (void)dealloc;	// IMP=0x001000000001e10d
- (id)initForBundleIdentifier:(id)arg1 options:(id)arg2 forClient:(id)arg3;	// IMP=0x001000000001e055

@end

