//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class ACXAvailableApplicationManager, ACXDevice, ACXGizmoState, ACXInstallQueue, ACXLocalAppStoreInstallQueue, ACXRemoteAppList, ACXRemoteSystemAppList, NSString;
@protocol OS_dispatch_queue;

@interface ACXCompanionSyncConnection : NSObject
{
    _Bool _reunionSyncRunning;	// 8 = 0x8
    _Bool _needsAvailableSystemAppFetch;	// 9 = 0x9
    _Bool _availableSystemAppFetchRunning;	// 10 = 0xa
    ACXDevice *_device;	// 16 = 0x10
    ACXGizmoState *_gizmoState;	// 24 = 0x18
    ACXRemoteAppList *_remoteAppList;	// 32 = 0x20
    ACXRemoteSystemAppList *_availableSystemAppList;	// 40 = 0x28
    NSObject<OS_dispatch_queue> *_internalQueue;	// 48 = 0x30
    ACXInstallQueue *_installQueue;	// 56 = 0x38
    ACXAvailableApplicationManager *_applicationManager;	// 64 = 0x40
    ACXLocalAppStoreInstallQueue *_appStoreLocalQueue;	// 72 = 0x48
}

- (void).cxx_destruct;	// IMP=0x0020000000032ab3
@property(nonatomic) _Bool availableSystemAppFetchRunning; // @synthesize availableSystemAppFetchRunning=_availableSystemAppFetchRunning;
@property(nonatomic) _Bool needsAvailableSystemAppFetch; // @synthesize needsAvailableSystemAppFetch=_needsAvailableSystemAppFetch;
@property(nonatomic) _Bool reunionSyncRunning; // @synthesize reunionSyncRunning=_reunionSyncRunning;
@property(readonly, nonatomic) ACXLocalAppStoreInstallQueue *appStoreLocalQueue; // @synthesize appStoreLocalQueue=_appStoreLocalQueue;
@property(readonly, nonatomic) ACXAvailableApplicationManager *applicationManager; // @synthesize applicationManager=_applicationManager;
@property(readonly, nonatomic) ACXInstallQueue *installQueue; // @synthesize installQueue=_installQueue;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *internalQueue; // @synthesize internalQueue=_internalQueue;
@property(readonly, nonatomic) ACXRemoteSystemAppList *availableSystemAppList; // @synthesize availableSystemAppList=_availableSystemAppList;
@property(readonly, nonatomic) ACXRemoteAppList *remoteAppList; // @synthesize remoteAppList=_remoteAppList;
@property(readonly, nonatomic) ACXGizmoState *gizmoState; // @synthesize gizmoState=_gizmoState;
@property(readonly, nonatomic) ACXDevice *device; // @synthesize device=_device;
- (void)noteCompanionAppDatabaseRebuild;	// IMP=0x00100000000329c3
- (void)noteNewCompanionApps:(id)arg1 updatedApps:(id)arg2 removedApps:(id)arg3 forDBUUID:(id)arg4 endingSequenceNumber:(unsigned long long)arg5;	// IMP=0x0010000000032010
- (void)_processSystemAppChangesForNewApps:(id)arg1 updatedApps:(id)arg2 removedApps:(id)arg3;	// IMP=0x0010000000031758
- (void)resyncCompleted;	// IMP=0x0010000000031683
- (void)applicationsRemoved:(id)arg1;	// IMP=0x0010000000031451
- (void)applicationsUpdated:(id)arg1;	// IMP=0x001000000003120d
- (void)applicationsAdded:(id)arg1;	// IMP=0x0010000000030df2
- (void)_setLocallyAvailableForRemoteApplicationInstances:(id)arg1;	// IMP=0x0010000000030bd1
- (void)acknowledgeAppEventsForDBUUID:(id)arg1 throughSequenceNumber:(unsigned long long)arg2;	// IMP=0x0010000000030ae7
- (void)fetchOutstandingAppEvents;	// IMP=0x00100000000309ff
- (void)fetchBundleIDList;	// IMP=0x0010000000030917
- (void)fetchAppInfoForBundleIDs:(id)arg1;	// IMP=0x001000000003080c
- (_Bool)supportsRemoteAppList;	// IMP=0x00100000000307d9
- (void)updatePreferencesForApplicationWithIdentifier:(id)arg1 preferences:(id)arg2 writingToPreferencesLocation:(unsigned long long)arg3 options:(unsigned long long)arg4 completion:(CDUnknownBlockType)arg5;	// IMP=0x001000000003012c
- (void)fetchProvisioningProfilesForApplicationWithBundleID:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000002fb89
- (void)fetchProvisioningProfilesWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x001000000002fb72
- (void)removeProvisioningProfileWithID:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000002f5c4
- (void)installProvisioningProfileWithData:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x001000000002f016
- (void)acknowledgeTestFlightInstallBegunForWatchApp:(id)arg1;	// IMP=0x001000000002efa0
- (void)noteInstallFailure:(id)arg1 forWatchAppWithBundleID:(id)arg2 wasUserInitiated:(_Bool)arg3;	// IMP=0x001000000002ee6e
- (void)performReunionSyncWithReason:(id)arg1;	// IMP=0x001000000002ed28
- (void)processPendingStateWithReason:(id)arg1;	// IMP=0x001000000002ec24
- (void)handleIncomingMessage:(id)arg1;	// IMP=0x001000000002e3e9
- (void)_onQueue_handleAppInstallFailureMessage:(id)arg1;	// IMP=0x001000000002dc47
- (void)_onQueue_handleIconForWatchAppMessage:(id)arg1;	// IMP=0x001000000002d66a
- (void)_onQueue_handleCompatibleWatchAppsOnCompanionMessage:(id)arg1;	// IMP=0x001000000002d1dd
- (void)_onQueue_handleInstallAppMessage:(id)arg1;	// IMP=0x001000000002cda3
- (void)_onQueue_handleAppDeleteMessage:(id)arg1;	// IMP=0x001000000002c8c7
- (id)_onQueue_availableCompanionAppBundleIDForWatchApp:(id)arg1;	// IMP=0x001000000002c7e5
- (id)_onQueue_applicationForWatchAppWithBundleID:(id)arg1;	// IMP=0x001000000002c6f2
- (void)_onQueue_handleAppInstallMessage:(id)arg1;	// IMP=0x001000000002c67d
- (void)_onQueue_handleAppInstallMessage:(id)arg1 withAppManager:(id)arg2;	// IMP=0x001000000002bee9
- (void)_onQueue_processPendingGizmoState;	// IMP=0x001000000002a728
- (_Bool)_onQueue_appNeedsInstall:(id)arg1;	// IMP=0x001000000002a54b
- (void)_onQueue_triggerLocalAppStoreInstallForWatchApp:(id)arg1 userInitiated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;	// IMP=0x001000000002a28f
- (void)_onQueue_sendRemoveMessageForBundleIDs:(id)arg1 isUserInitiated:(_Bool)arg2 withCompletion:(CDUnknownBlockType)arg3;	// IMP=0x001000000002a08e
- (void)_onQueue_sendInstallOnGizmoMessageForSystemAppBundleIDs:(id)arg1 appsWithStoreMetadata:(id)arg2 isUserInitiated:(_Bool)arg3 exclusiveInstall:(_Bool)arg4 withCompletion:(CDUnknownBlockType)arg5;	// IMP=0x0010000000029a64
- (void);	// IMP=0x00100000000294c1
- (void)_onQueue_beginReunionSync;	// IMP=0x00100000000292a5
- (void)_onQueue_processReunionSyncMessage:(id)arg1 withAppManager:(id)arg2;	// IMP=0x001000000002573d
- (void)_onQueue_processReunionSyncMessage:(id)arg1;	// IMP=0x00100000000256c8
- (_Bool)_value:(id)arg1 isDifferentFrom:(id)arg2;	// IMP=0x00100000000256b8
- (void)_onQueue_handleSADAppInfoResponse:(id)arg1;	// IMP=0x00100000000250a3
- (void)_onQueue_fetchAvailableSystemAppsWithRetryCount:(unsigned long long)arg1;	// IMP=0x0010000000024b45
- (void)_onQueue_fetchAvailableSystemApps;	// IMP=0x0010000000024a43
- (void)removeWatchAppWithBundleID:(id)arg1 completion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000024621
- (id)remoteAppWithBundleID:(id)arg1;	// IMP=0x0010000000024387
- (void)_installQueuedOrCompletedForWatchBundleID:(id)arg1 companionAppBundleID:(id)arg2 withName:(id)arg3 userInitiated:(_Bool)arg4 withError:(id)arg5 withCompletion:(CDUnknownBlockType)arg6;	// IMP=0x0010000000023ef3
- (void)installWatchAppAtURL:(id)arg1 installOptions:(id)arg2 size:(long long)arg3 completionWithError:(CDUnknownBlockType)arg4;	// IMP=0x0010000000023335
- (id)_appBundleFromURL:(id)arg1;	// IMP=0x0010000000022fb6
- (void)_installWatchAppWithBundleID:(id)arg1 withProvisioningProfileInfo:(id)arg2 installationPendingBlock:(CDUnknownBlockType)arg3 completionWithError:(CDUnknownBlockType)arg4;	// IMP=0x00100000000221f5
- (void)installWatchAppWithBundleID:(id)arg1 withProvisioningProfileInfo:(id)arg2 completionWithError:(CDUnknownBlockType)arg3;	// IMP=0x00100000000221dd
- (void)installSystemApplicationsWithBundleIDs:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;	// IMP=0x0010000000022069
- (_Bool)_onQueue_installFailedForWatchAppBundleID:(id)arg1 companionBundleID:(id)arg2 withError:(id)arg3 appName:(id)arg4 userInitiated:(_Bool)arg5 userPresentableError:(id *)arg6;	// IMP=0x0010000000021d70
- (void)cancelPendingInstallations;	// IMP=0x0010000000021c4d
- (void)markAllApplicationsAsRemoved;	// IMP=0x00100000000218ef
- (void)installAllApplications;	// IMP=0x00100000000212d3
- (void)reachabilityChangedForDevice:(id)arg1;	// IMP=0x00100000000210aa
- (void)_onQueue_configureRemoteAppListsAndFetchSystemAppsIfNeeded;	// IMP=0x0010000000020d3b
- (id)messager;	// IMP=0x0010000000020ceb
- (void)dealloc;	// IMP=0x0010000000020c7d
- (id)initWithDevice:(id)arg1;	// IMP=0x0010000000020914

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

