//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class ACXTimedIdentifierList;
@protocol OS_dispatch_queue;

@interface ACXTestFlightInstallQueue : NSObject
{
    NSObject<OS_dispatch_queue> *_internalQueue;	// 8 = 0x8
    ACXTimedIdentifierList *_list;	// 16 = 0x10
}

+ (id)sharedInstaller;	// IMP=0x004000000001107f
- (void).cxx_destruct;	// IMP=0x0020000000011a10
@property(readonly, nonatomic) ACXTimedIdentifierList *list; // @synthesize list=_list;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *internalQueue; // @synthesize internalQueue=_internalQueue;
- (void)removePendingInstallForAppWithBundleID:(id)arg1;	// IMP=0x00100000000118b4
- (void)removePendingInstallForApp:(id)arg1;	// IMP=0x0010000000011865
- (void)installWatchApp:(id)arg1 targetDevice:(id)arg2;	// IMP=0x001000000001132f
- (id)init;	// IMP=0x001000000001110c

@end

