//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString, UIImage;

@interface _MFIconCacheItem : NSObject
{
    NSString *_filename;	// 8 = 0x8
    UIImage *_cachedImage;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x00200000000396bb
@property(retain, nonatomic) UIImage *cachedImage; // @synthesize cachedImage=_cachedImage;
@property(readonly, copy, nonatomic) NSString *filename; // @synthesize filename=_filename;
- (id)initWithFilename:(id)arg1;	// IMP=0x00100000000395f7

@end

