//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class EFQuery, EMMessageRepository;

@protocol EMMessageRepositoryCountQueryObserver <NSObject>
- (void)messageRepository:(EMMessageRepository *)arg1 query:(EFQuery *)arg2 countDidChange:(long long)arg3;
@end

