//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface MCSChangeUtilities : NSObject
{
}

+ (id)mergeMessageChanges:(id)arg1 withChanges:(id)arg2;	// IMP=0x004000000004451d
+ (id)allMessagesInChanges:(id)arg1;	// IMP=0x001000000004436e
+ (id)flagChangesForKey:(id)arg1;	// IMP=0x0010000000044022

@end

