//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface MFNanoBridgeSettingsMailbox : NSObject
{
}

+ (_Bool)supportsSecureCoding;	// IMP=0x0020000000097806
+ (unsigned long long)sourceTypeForMailboxFilterType:(unsigned long long)arg1;	// IMP=0x001000000009777c
+ (id)defaultSelectedMailboxes;	// IMP=0x00100000000973a0
- (_Bool)isEqual:(id)arg1;	// IMP=0x0040000000097827
- (id)initWithCoder:(id)arg1;	// IMP=0x0010000000097814
- (void)encodeWithCoder:(id)arg1;	// IMP=0x001000000009780e
- (_Bool)isValid;	// IMP=0x00100000000977fe
- (void)configureCell:(id)arg1;	// IMP=0x00100000000977f8
- (unsigned long long)level;	// IMP=0x00100000000977f0
- (id)icon;	// IMP=0x00100000000977e8
- (id)displayName;	// IMP=0x00100000000977e0
- (unsigned long long)mailboxFilterType;	// IMP=0x00100000000977d8

@end

