//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@class PDURLSessionProxySessionMessage;

@interface PDURLSessionProxyInvalidateSession : PBCodable
{
    PDURLSessionProxySessionMessage *_session;	// 8 = 0x8
    _Bool _shouldCancel;	// 16 = 0x10
    struct {
        unsigned int shouldCancel:1;
    } _has;	// 20 = 0x14
}

- (void).cxx_destruct;	// IMP=0x0020000000044b1d
@property(nonatomic) _Bool shouldCancel; // @synthesize shouldCancel=_shouldCancel;
@property(retain, nonatomic) PDURLSessionProxySessionMessage *session; // @synthesize session=_session;
- (void)mergeFrom:(id)arg1;	// IMP=0x0010000000044a6b
- (unsigned long long)hash;	// IMP=0x0010000000044a18
- (_Bool)isEqual:(id)arg1;	// IMP=0x0010000000044947
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00100000000448af
- (void)copyTo:(id)arg1;	// IMP=0x001000000004484c
- (void)writeTo:(id)arg1;	// IMP=0x00100000000447e7
- (_Bool)readFrom:(id)arg1;	// IMP=0x001000000004459c
- (id)dictionaryRepresentation;	// IMP=0x00100000000444b6
- (id)description;	// IMP=0x0010000000044407
@property(nonatomic) _Bool hasShouldCancel;
@property(readonly, nonatomic) _Bool hasSession;

@end

