//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSDate, NSMutableDictionary, NSProgress, NSString, NSURL, NSUUID;

@interface DSFileServiceProgressGroup : NSObject
{
    NSUUID *_uuid;	// 8 = 0x8
    NSProgress *_progress;	// 16 = 0x10
    NSURL *_publishingURL;	// 24 = 0x18
    NSMutableDictionary *_childProgresses;	// 32 = 0x20
    NSDate *_dateStarted;	// 40 = 0x28
    NSString *_firstChildName;	// 48 = 0x30
}

- (void).cxx_destruct;	// IMP=0x002000000004fe61
@property(readonly, copy, nonatomic) NSString *firstChildName; // @synthesize firstChildName=_firstChildName;
@property(readonly, copy, nonatomic) NSDate *dateStarted; // @synthesize dateStarted=_dateStarted;
@property(retain, nonatomic) NSMutableDictionary *childProgresses; // @synthesize childProgresses=_childProgresses;
- (void)setPublishingURL:(id)arg1;	// IMP=0x001000000004fe23
- (id)publishingURL;	// IMP=0x001000000004fe19
@property(copy, nonatomic) NSProgress *progress; // @synthesize progress=_progress;
@property(copy, nonatomic) NSUUID *uuid; // @synthesize uuid=_uuid;
- (void)unpublish;	// IMP=0x001000000004fd96
- (void)publish;	// IMP=0x001000000004fd45
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;	// IMP=0x001000000004f996
- (id)_timeRemainingEstimateWithTimeElapsed:(double)arg1 fractionDone:(double)arg2;	// IMP=0x001000000004f911
@property(readonly, nonatomic) _Bool hasOutstandingChildren;
- (void)removeChildProgress:(id)arg1;	// IMP=0x001000000004f698
- (void)addChildProgress:(id)arg1;	// IMP=0x001000000004f05b
- (void)dealloc;	// IMP=0x001000000004edfb
- (void)updateProgressLocalizedStrings;	// IMP=0x001000000004ed88
- (id)initWithUUID:(id)arg1 operationKind:(id)arg2 groupCount:(long long)arg3 publishingURL:(id)arg4 firstChildName:(id)arg5 dateStarted:(id)arg6 utType:(id)arg7;	// IMP=0x001000000004e250

@end

