//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;
@protocol NavdDoomStorageSnapshotDataSource, OS_dispatch_queue;

@interface NavdDoomCache : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;	// 8 = 0x8
    id <NavdDoomStorageSnapshotDataSource> _snapshotDataSource;	// 16 = 0x10
}

+ (id)loadFromFilePath:(id)arg1;	// IMP=0x002000000000289c
+ (_Bool)saveToFilePath:(id)arg1 storage:(id)arg2;	// IMP=0x00100000000024cd
+ (id)defaultPath;	// IMP=0x00100000000024ad
- (void).cxx_destruct;	// IMP=0x0020000000002f98
@property(retain, nonatomic) id <NavdDoomStorageSnapshotDataSource> snapshotDataSource; // @synthesize snapshotDataSource=_snapshotDataSource;
- (void)didEndUpdate;	// IMP=0x0010000000002f6b
- (void)didScheduleWakeup;	// IMP=0x0010000000002f59
- (void)didFireAlert;	// IMP=0x0010000000002f47
- (void)willFireAlert;	// IMP=0x0010000000002f35
- (void)didUpdateRoutes;	// IMP=0x0010000000002f23
- (void)willUpdateRoutes;	// IMP=0x0010000000002f11
- (void)didUpdateDestinations;	// IMP=0x0010000000002eff
- (void)willUpdateDestinations;	// IMP=0x0010000000002eed
- (void)didUpdateWindow;	// IMP=0x0010000000002edb
- (void)didInvalidateWindow;	// IMP=0x0010000000002ec9
- (void)didUpdateExitTime;	// IMP=0x0010000000002eb7
- (void)willUpdateExitTime;	// IMP=0x0010000000002ea5
- (void)willStartUpdate;	// IMP=0x0010000000002e93
- (void)_writeToDisk;	// IMP=0x0010000000002da3
- (id)init;	// IMP=0x0010000000002d0f

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

