//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class AppInstall, AppInstallDownloadResponse, AppInstallInfo, AppPackage, IXAppInstallCoordinator;

@interface AppInstallDownloadTask
{
    IXAppInstallCoordinator *_coordinator;	// 8 = 0x8
    _Bool _didLoadAssetSize;	// 16 = 0x10
    long long _installID;	// 24 = 0x18
    AppInstall *_install;	// 32 = 0x20
    AppInstallInfo *_installInfo;	// 40 = 0x28
    AppPackage *_package;	// 48 = 0x30
    AppInstallDownloadResponse *_downloadResponse;	// 56 = 0x38
}

- (void).cxx_destruct;	// IMP=0x00200000000fa7ad
- (void)main;	// IMP=0x00100000000fa77a

@end

