//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class RequestProxy;

@protocol RequestController
- (void)startUsingProxy:(RequestProxy *)arg1 withErrorHandler:(void (^)(NSError *))arg2;
- (void)cancelUsingProxy:(RequestProxy *)arg1 withErrorHandler:(void (^)(NSError *))arg2;
@end

