//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class NSError;
@protocol StreamDelegate;

@protocol Stream <NSObject>
@property(readonly) unsigned long long streamStatus;
@property(readonly) NSError *streamError;
@property __weak id <StreamDelegate> delegate;
- (void)close;
- (void)open;
@end

