//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class ACAccount, AMSBagValue, ApplicationProxy, NSString;

@interface SwitchAppOwnerTask
{
    ACAccount *_account;	// 8 = 0x8
    NSString *_fromUserName;	// 16 = 0x10
    NSString *_logKey;	// 24 = 0x18
    ApplicationProxy *_proxy;	// 32 = 0x20
    AMSBagValue *_swithUserBagUrl;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x002000000026374e
- (_Bool)_refreshReceiptForAppProxyForMacOS;	// IMP=0x0010000000263746
- (_Bool)_swithUserForMacOS;	// IMP=0x001000000026373e
- (_Bool)_repairReceiptForAppProxyIOS:(id)arg1 receiptData:(id)arg2;	// IMP=0x0010000000263736
- (_Bool)_repairSINFUsingContentRestore;	// IMP=0x001000000026372e
- (id)_performRequestWithError:(id *)arg1;	// IMP=0x0010000000263486
- (id)_newBaseRequestBodyDictionary;	// IMP=0x0010000000263333
- (id)_getSinf;	// IMP=0x001000000026332b
- (id)_getReceipt;	// IMP=0x0010000000263323
- (void)main;	// IMP=0x0010000000263037
- (id)initWithAccount:(id)arg1 fromUserName:(id)arg2 proxy:(id)arg3;	// IMP=0x0010000000262f1c

@end

