//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@protocol CRRecentsMigratorDelegate;

@interface CRRecentsMigrator : NSObject
{
    id <CRRecentsMigratorDelegate> _delegate;	// 8 = 0x8
    int _needsRebuild;	// 16 = 0x10
}

+ (_Bool)executeSQL:(id)arg1 database:(id)arg2;	// IMP=0x0040000000010d65
+ (void)setVersion:(int)arg1 ofDatabase:(id)arg2;	// IMP=0x0010000000010d3d
+ (int)versionOfDatabase:(id)arg1;	// IMP=0x0010000000010d20
+ (void)migrateLibraryFilesFrom:(id)arg1 to:(id)arg2;	// IMP=0x0010000000010a53
- (void)migrateMailEmbeddedLibraryToPath:(id)arg1;	// IMP=0x00200000000109df
- (_Bool)migrateWithSQLiteConnection:(id)arg1 toVersion:(int)arg2;	// IMP=0x001000000000f2e2
- (_Bool)migrateWithSQLiteConnection:(id)arg1;	// IMP=0x001000000000f2cb
- (void)noteNeedsRebuild;	// IMP=0x001000000000f2b9
- (_Bool)needsRebuild;	// IMP=0x001000000000f2a4
- (void)dealloc;	// IMP=0x001000000000f26d
- (id)initWithDelegate:(id)arg1;	// IMP=0x001000000000f230

@end

