//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface CRWeakReference : NSObject
{
    id _weakRef;	// 8 = 0x8
}

+ (id)weakReferenceWithObject:(id)arg1;	// IMP=0x00400000000194da
- (id)object;	// IMP=0x0020000000019597
- (void)dealloc;	// IMP=0x001000000001955b
- (id)initWithObject:(id)arg1;	// IMP=0x0010000000019509

@end

