//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString, PHPhotoLibrary, PVPersonPromoter, VCPFaceClusterer, VCPPersonBuilder, VCPPhotosFaceProcessingContext;

@interface MADPhotosPersonProcessingTask
{
    PHPhotoLibrary *_photoLibrary;	// 8 = 0x8
    VCPPhotosFaceProcessingContext *_context;	// 16 = 0x10
    unsigned long long _requirement;	// 24 = 0x18
    VCPFaceClusterer *_faceClusterer;	// 32 = 0x20
    VCPPersonBuilder *_personBuilder;	// 40 = 0x28
    PVPersonPromoter *_personPromoter;	// 48 = 0x30
    NSString *_logPrefix;	// 56 = 0x38
}

+ (id)taskWithPhotoLibrary:(id)arg1 requirement:(unsigned long long)arg2 faceClusterer:(id)arg3 andContext:(id)arg4;	// IMP=0x00400000000a8fb8
- (void).cxx_destruct;	// IMP=0x00200000000abdb1
- (void)process;	// IMP=0x00100000000a94ab
- (int)_updateVIPModels;	// IMP=0x00100000000a9070
- (id)initWithPhotoLibrary:(id)arg1 requirement:(unsigned long long)arg2 faceClusterer:(id)arg3 andContext:(id)arg4;	// IMP=0x00100000000a8cbc

@end

