//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class VCPTimer;
@protocol OS_dispatch_queue;

@interface VCPProgressReporter : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;	// 8 = 0x8
    VCPTimer *_timer;	// 16 = 0x10
    long long _processedJobCountOnLastUpdate;	// 24 = 0x18
    long long _processedJobCount;	// 32 = 0x20
    long long _totalJobCount;	// 40 = 0x28
}

+ (id)reporterWithIntervalSeconds:(unsigned long long)arg1 andTotalJobCount:(long long)arg2 andBlock:(CDUnknownBlockType)arg3;	// IMP=0x0040000000013bdc
- (void).cxx_destruct;	// IMP=0x0020000000013e5f
- (void)_reportProgressWithBlock:(CDUnknownBlockType)arg1;	// IMP=0x0010000000013ce5
- (void)increaseProcessedJobCountByOne;	// IMP=0x0010000000013cdb
- (void)dealloc;	// IMP=0x0010000000013c55
- (id)initWithIntervalSeconds:(unsigned long long)arg1 andTotalJobCount:(long long)arg2 andBlock:(CDUnknownBlockType)arg3;	// IMP=0x001000000001385e
- (id)init;	// IMP=0x0010000000013850

@end

