//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface VCPResumePausedAnalysisTask
{
}

+ (id)taskWithPhotoLibrary:(id)arg1;	// IMP=0x00400000000bc293
- (int)mainInternal;	// IMP=0x00400000000bc2f8

@end

