//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface UAAnalyticsEvent : NSObject
{
}

- (id)firstPartyActivityTypeOrUnknown:(id)arg1;	// IMP=0x00400000000569cc
- (id)description;	// IMP=0x001000000005690f
- (void)sendEvent;	// IMP=0x0010000000056909
- (id)eventPayload;	// IMP=0x0010000000056901
- (id)eventName;	// IMP=0x00100000000568f4

@end

