//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface CLAppTileDataProviderRequest : NSObject
{
    _Bool _includeRegionalApps;	// 8 = 0x8
    _Bool _marqueeAppsOnly;	// 9 = 0x9
    float _radiusMeters;	// 12 = 0xc
    double _lat;	// 16 = 0x10
    double _lon;	// 24 = 0x18
    CDUnknownBlockType _handler;	// 32 = 0x20
    double _timestamp;	// 40 = 0x28
}

@property(nonatomic) double timestamp; // @synthesize timestamp=_timestamp;
@property(copy, nonatomic) CDUnknownBlockType handler; // @synthesize handler=_handler;
@property(nonatomic) _Bool marqueeAppsOnly; // @synthesize marqueeAppsOnly=_marqueeAppsOnly;
@property(nonatomic) _Bool includeRegionalApps; // @synthesize includeRegionalApps=_includeRegionalApps;
@property(nonatomic) float radiusMeters; // @synthesize radiusMeters=_radiusMeters;
@property(nonatomic) double lon; // @synthesize lon=_lon;
@property(nonatomic) double lat; // @synthesize lat=_lat;
- (void)dealloc;	// IMP=0x00100000009a1459

@end

