//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <LocationSupport/CLIntersiloService.h>

@class CLTimer, NSMutableArray, NSMutableSet, NSString, WPAirPlaySolo;

@interface CLATVAirplayMonitor : CLIntersiloService
{
    _Bool _power;	// 8 = 0x8
    NSMutableSet *_clients;	// 16 = 0x10
    WPAirPlaySolo *_airplaySolo;	// 24 = 0x18
    CLTimer *_scanDeliveryDelayTimer;	// 32 = 0x20
    NSMutableArray *_bufferedDevices;	// 40 = 0x28
}

+ (id)getSilo;	// IMP=0x0020000000387fa6
+ (void)performSyncOnSilo:(id)arg1 invoker:(CDUnknownBlockType)arg2;	// IMP=0x0010000000387f8d
+ (void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2;	// IMP=0x0010000000387f30
@property(retain, nonatomic) NSMutableArray *bufferedDevices; // @synthesize bufferedDevices=_bufferedDevices;
@property(retain, nonatomic) CLTimer *scanDeliveryDelayTimer; // @synthesize scanDeliveryDelayTimer=_scanDeliveryDelayTimer;
@property(nonatomic) _Bool power; // @synthesize power=_power;
- (void);	// IMP=0x00100000003890d8
@property(retain, nonatomic) WPAirPlaySolo *airplaySolo; // @synthesize airplaySolo=_airplaySolo;
@property(retain, nonatomic) NSMutableSet *clients; // @synthesize clients=_clients;
- (void)airPlaySolo:(id)arg1 failedToStartScanningWithError:(id)arg2;	// IMP=0x0010000000388f9f
- (void)airPlaySoloStoppedScanning:(id)arg1;	// IMP=0x0010000000388ef0
- (void)airPlaySoloStartedScanning:(id)arg1;	// IMP=0x0010000000388e41
- (void)airPlaySolo:(id)arg1 foundDevice:(id)arg2 withData:(id)arg3;	// IMP=0x0010000000388954
- (void)airPlaySoloDidUpdateState:(id)arg1;	// IMP=0x001000000038891a
- (void)sendBufferedScanNotifications;	// IMP=0x001000000038881e
- (void)stopScan;	// IMP=0x00100000003887eb
- (void)startScan;	// IMP=0x00100000003885f8
- (void)withClients:(CDUnknownBlockType)arg1;	// IMP=0x00100000003884db
- (id)init;	// IMP=0x001000000038849e
- (void)getPowerWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0010000000388476
- (void)stopMonitoringDevicesForClient:(byref id)arg1;	// IMP=0x00100000003883fb
- (void)startMonitoringDevicesForClient:(byref id)arg1;	// IMP=0x00100000003883b1
- (void)removeClient:(byref id)arg1;	// IMP=0x001000000038835a
- (void)addClient:(byref id)arg1;	// IMP=0x0010000000388303
- (void)dealloc;	// IMP=0x00100000003882c5
- (void)releaseData;	// IMP=0x001000000038825b
- (void)endService;	// IMP=0x0010000000388220
- (void)beginServiceWithAirPlaySolo:(id)arg1;	// IMP=0x0010000000388054
- (void)beginService;	// IMP=0x0010000000388002

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(nonatomic) _Bool valid;

@end

