//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@protocol CLAvengerScannerClientServiceProtocol <NSObject>
- (_Bool)poweredOn;
- (void)setOptedIn:(_Bool)arg1;
- (_Bool)getOptedIn;
- (_Bool)isScanning;
- (_Bool)stopBTFindingScan;
- (_Bool)startBTFindingScan;
- (_Bool)performTemporaryHawkeyeLowEnergyScan;
- (_Bool)stopTemporaryLongAggressiveScan;
- (_Bool)performTemporaryLongAggressiveScan;
- (_Bool)performTemporaryAggressiveScan;
@end

