//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <LocationSupport/CLIntersiloService.h>

@class NSString;

@interface CLDistributedSensingService : CLIntersiloService
{
}

+ (_Bool)isSupported;	// IMP=0x002000000012b228
+ (id)getSilo;	// IMP=0x001000000012b1cc
+ (void)performSyncOnSilo:(id)arg1 invoker:(CDUnknownBlockType)arg2;	// IMP=0x001000000012b1b3
+ (void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2;	// IMP=0x001000000012b156
- (void)unregisterClient:(byref id)arg1 forNotification:(int)arg2;	// IMP=0x002000000012b2ae
- (void)registerClient:(byref id)arg1 forNotification:(int)arg2;	// IMP=0x001000000012b2a8
- (void)endService;	// IMP=0x001000000012b2a2
- (void)beginService;	// IMP=0x001000000012b29c
- (void)dealloc;	// IMP=0x001000000012b26d
- (id)init;	// IMP=0x001000000012b230

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(nonatomic) _Bool valid;

@end

