//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <CoreLocationProtobuf/CLPMotionActivity.h>

@interface CLPMotionActivity (Initializers)
- (id)initWithCLMotionActivity:(struct CLMotionActivity)arg1;	// IMP=0x0010000000a90d28
@end

