//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <LocationSupport/CLIntersiloService.h>

@class CLLocation, NSMutableArray, NSMutableSet, NSString;
@protocol CLTransitMacTileDataProviderProtocol, CLWifiServiceProtocol;

@interface CLTransitMacMonitor : CLIntersiloService
{
    id <CLWifiServiceProtocol> _wifiServiceProxy;	// 8 = 0x8
    struct unique_ptr<CLWifiService_Type::Client, std::default_delete<CLWifiService_Type::Client>> _wifiServiceClient;	// 16 = 0x10
    id <CLTransitMacTileDataProviderProtocol> _transitMacTileDataProviderProxy;	// 24 = 0x18
    struct unique_ptr<CLFilteredLocationController_Type::Client, std::default_delete<CLFilteredLocationController_Type::Client>> _locationClient;	// 32 = 0x20
    unsigned long long _currentState;	// 40 = 0x28
    NSMutableSet *_clients;	// 48 = 0x30
    NSMutableArray *_observedTransitAccessPointsCache;	// 56 = 0x38
    CLLocation *_mostRecentLocation;	// 64 = 0x40
}

+ (_Bool)isSupported;	// IMP=0x0020000000a39205
+ (id)getSilo;	// IMP=0x0010000000a3916c
+ (void)performSyncOnSilo:(id)arg1 invoker:(CDUnknownBlockType)arg2;	// IMP=0x0010000000a39153
+ (void)becameFatallyBlocked:(id)arg1 index:(unsigned long long)arg2;	// IMP=0x0010000000a390f6
- (id).cxx_construct;	// IMP=0x0020000000a3b31f
- (void).cxx_destruct;	// IMP=0x0010000000a3b2cd
@property(retain, nonatomic) CLLocation *mostRecentLocation; // @synthesize mostRecentLocation=_mostRecentLocation;
@property(retain, nonatomic) NSMutableArray *observedTransitAccessPointsCache; // @synthesize observedTransitAccessPointsCache=_observedTransitAccessPointsCache;
@property(retain, nonatomic) NSMutableSet *clients; // @synthesize clients=_clients;
@property(nonatomic) unsigned long long currentState; // @synthesize currentState=_currentState;
- (void)onLocationNotification:(int)arg1 data:(struct NotificationData)arg2;	// IMP=0x0010000000a3b0cb
- (void)onWifiServiceNotification:(int)arg1 data:(struct NotificationData)arg2;	// IMP=0x0010000000a3a8a4
- (void)processNewAccessPoints:(const void *)arg1 transitTileResults:(id)arg2;	// IMP=0x0010000000a39bcb
- (void)stopMonitoringTransitStateForClient:(byref id)arg1;	// IMP=0x0010000000a398a8
- (void)startMonitoringTransitStateForClient:(byref id)arg1;	// IMP=0x0010000000a3979a
- (void)endService;	// IMP=0x0010000000a3962d
- (void)beginService;	// IMP=0x0010000000a3920d
- (id)init;	// IMP=0x0010000000a391c8

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(nonatomic) _Bool valid;

@end

