//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class MediaControlsLanguageOptionsViewController;

@protocol MediaControlsLanguageOptionsViewControllerDelegate <NSObject>
- (void)dismissLanguageOptionsViewController:(MediaControlsLanguageOptionsViewController *)arg1;
- (void)didLoadOptionsForLanguageOptionsViewController:(MediaControlsLanguageOptionsViewController *)arg1;
@end

