//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIViewController.h>

@class NSString, NSURL, UINavigationController, WFServicePINEntryViewController;
@protocol WFPINEntryViewControllerProtocol;

@interface WFServicePINEntryNavigationController : UIViewController
{
    id <WFPINEntryViewControllerProtocol> _remoteViewControllerProxy;	// 8 = 0x8
    UINavigationController *_navController;	// 16 = 0x10
    WFServicePINEntryViewController *_PINEntryViewController;	// 24 = 0x18
    NSURL *_URL;	// 32 = 0x20
    NSString *_pageTitle;	// 40 = 0x28
}

+ (id)_remoteViewControllerInterface;	// IMP=0x0020000000002164
+ (id)_exportedInterface;	// IMP=0x0010000000002144
- (void).cxx_destruct;	// IMP=0x00200000000024dc
- (void)didCancelEnteringPIN;	// IMP=0x00100000000024bf
- (void)didAcceptEnteredPIN;	// IMP=0x001000000000247c
- (void)cancel;	// IMP=0x0010000000002468
- (void)permitURLWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x00100000000023af
- (void)getIsPINPresentWithCompletion:(CDUnknownBlockType)arg1;	// IMP=0x0010000000002361
- (void)setPageTitle:(id)arg1;	// IMP=0x00100000000022f8
- (void)setURL:(id)arg1;	// IMP=0x0010000000002198
- (void)_willAppearInRemoteViewController:(id)arg1;	// IMP=0x0010000000002184
- (unsigned long long)supportedInterfaceOrientations;	// IMP=0x00100000000020ea
- (void)viewDidLoad;	// IMP=0x0010000000001f68

@end

