//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIApplication.h>

@class SSSAppDelegate;

@interface SSSApplication : UIApplication
{
}

+ (id)sharedSSSApplication;	// IMP=0x004000000000fba2
- (_Bool)_canAnimateDragCancelInApp;	// IMP=0x00100000000107c7
- (void)_handlePlatformSpecificActions:(id)arg1 forScene:(id)arg2 withTransitionContext:(id)arg3;	// IMP=0x001000000000ff28
- (id)_preheatActionInActions:(id)arg1;	// IMP=0x001000000000fec1
- (id)_documentUpdateActionInActions:(id)arg1;	// IMP=0x001000000000fe5a
- (id)_metadataUpdateActionInActions:(id)arg1;	// IMP=0x001000000000fdf3
- (id)_imageIdentifierActionInActions:(id)arg1;	// IMP=0x001000000000fd8c
- (id)_screenshotActionInActions:(id)arg1;	// IMP=0x001000000000fd25
- (id)_actionInActions:(id)arg1 ofClass:(Class)arg2;	// IMP=0x001000000000fbcd
@property(readonly, nonatomic) SSSAppDelegate *sssAppDelegate;
- (_Bool)runTest:(id)arg1 options:(id)arg2;	// IMP=0x001000000000403e
- (id)_pptTestInfos;	// IMP=0x0010000000003db4

@end

