//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSDate, NSString, STUserID;

@interface STDowntimeStateEvent : NSObject
{
    NSString *_identifier;	// 8 = 0x8
    NSDate *_downtimeDate;	// 16 = 0x10
    STUserID *_userID;	// 24 = 0x18
    long long _downtimeConfigurationState;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x00200000000ac178
@property(readonly) long long downtimeConfigurationState; // @synthesize downtimeConfigurationState=_downtimeConfigurationState;
@property(readonly, copy) STUserID *userID; // @synthesize userID=_userID;
@property(readonly, copy) NSDate *downtimeDate; // @synthesize downtimeDate=_downtimeDate;
@property(readonly, copy) NSString *identifier; // @synthesize identifier=_identifier;
- (unsigned long long)hash;	// IMP=0x00100000000ac060
- (_Bool)isEqualToDowntimeStateEvent:(id)arg1;	// IMP=0x00100000000abead
- (_Bool)isEqual:(id)arg1;	// IMP=0x00100000000abe4a
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00100000000abe0e
@property(readonly) _Bool enabled;
- (id)initWithIdentifier:(id)arg1 downtimeConfigurationState:(long long)arg2 downtimeDate:(id)arg3 userID:(id)arg4;	// IMP=0x00100000000abcdf

@end

