//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSXPCConnection;

@interface STReactorToolClient : NSObject
{
    NSXPCConnection *_connection;	// 8 = 0x8
}

+ (id)_newConnection;	// IMP=0x0040000000078aba
- (void).cxx_destruct;	// IMP=0x0000000000079659
@property(readonly) NSXPCConnection *connection; // @synthesize connection=_connection;
- (id)currentMessageTransportReachabilityMap:(id *)arg1;	// IMP=0x00100000000793d5
- (_Bool)scheduleFailStuckMessagesWithError:(id *)arg1;	// IMP=0x00100000000791b9
- (_Bool)scheduleStoreClenaupWithError:(id *)arg1;	// IMP=0x0010000000078f9d
- (_Bool)scheduleMessageRetryWithError:(id *)arg1;	// IMP=0x0010000000078d81
- (_Bool)shutdownReactorWithError:(id *)arg1;	// IMP=0x0010000000078b40
- (void)dealloc;	// IMP=0x0010000000078a78
- (id)init;	// IMP=0x0010000000078a09

@end

