//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString;

@interface STRemoteViewServiceDescription : NSObject
{
    NSString *_serviceName;	// 8 = 0x8
    NSString *_viewControllerClassName;	// 16 = 0x10
    NSDictionary *_configurationContextUserInfo;	// 24 = 0x18
}

+ (id)sharedDescriptionWithServiceName:(id)arg1 viewControllerClassName:(id)arg2 configurationContextUserInfo:(id)arg3;	// IMP=0x00200000000799e7
- (void).cxx_destruct;	// IMP=0x0020000000079ee1
@property(readonly) NSDictionary *configurationContextUserInfo; // @synthesize configurationContextUserInfo=_configurationContextUserInfo;
@property(readonly, copy) NSString *viewControllerClassName; // @synthesize viewControllerClassName=_viewControllerClassName;
@property(readonly, copy) NSString *serviceName; // @synthesize serviceName=_serviceName;
- (unsigned long long)hash;	// IMP=0x0010000000079de6
- (_Bool)isEqualToServiceDescription:(id)arg1;	// IMP=0x0010000000079c09
- (_Bool)isEqual:(id)arg1;	// IMP=0x0010000000079ba6
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0010000000079b55
- (id)description;	// IMP=0x001000000007996b
- (id)_initWithServiceName:(id)arg1 viewControllerClassName:(id)arg2 configurationContextUserInfo:(id)arg3;	// IMP=0x001000000007989b

@end

