//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface BKDisplayAnnotationEmphasizedStyle : NSObject
{
}

- (void)applyAppearanceToTextLayer:(id)arg1;	// IMP=0x0020000000021f7d
- (void)applyAppearanceToShapeLayer:(id)arg1;	// IMP=0x0010000000021eef
- (void)applyToLayer:(id)arg1 forContent:(id)arg2;	// IMP=0x0010000000021e70

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

