//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray, NSMapTable;

@interface BKMousePointerRegionArrangement : NSObject
{
    struct CGPoint _baseTranslation;	// 8 = 0x8
    struct CGRect _globalBounds;	// 24 = 0x18
    NSMapTable *_regionToComputedFrame;	// 56 = 0x38
    NSMapTable *_regionToLayoutDescriptor;	// 64 = 0x40
}

- (void).cxx_destruct;	// IMP=0x002000000008ea0c
@property(readonly, nonatomic) struct CGRect globalBounds; // @synthesize globalBounds=_globalBounds;
- (id)_layoutDescriptorForRegion:(id)arg1;	// IMP=0x001000000008e850
- (struct CGRect)_frameForRegion:(id)arg1;	// IMP=0x001000000008e67a
- (id)_copyMousePointerRegionArrangementWithClass:(Class)arg1;	// IMP=0x001000000008e5ed
- (struct CGPoint)convertFromGlobalPoint:(struct CGPoint)arg1 toRegion:(id)arg2;	// IMP=0x001000000008e59c
- (struct CGPoint)convertToGlobalPoint:(struct CGPoint)arg1 fromRegion:(id)arg2;	// IMP=0x001000000008e54b
- (id)closestRegionForGlobalPoint:(struct CGPoint)arg1 returningClosestContainingPoint:(out struct CGPoint *)arg2 returningEdgeMask:(out unsigned char *)arg3;	// IMP=0x001000000008df3b
- (id)regionForDisplayUUID:(id)arg1;	// IMP=0x001000000008dd80
@property(readonly, copy, nonatomic) NSArray *regions;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;	// IMP=0x001000000008dcdb
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x001000000008dcd0

@end

