//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class BKSystemShellDescriptor, BSServiceConnection, NSDate, NSString;
@protocol BSServiceConnectionHost;

@interface BKSystemShellClient : NSObject
{
    _Bool _pendingCheckIn;	// 8 = 0x8
    _Bool _checkedIn;	// 9 = 0x9
    _Bool _finishedStartup;	// 10 = 0xa
    _Bool _isAlternateShell;	// 11 = 0xb
    _Bool _wasAlive;	// 12 = 0xc
    BKSystemShellDescriptor *_descriptor;	// 16 = 0x10
    BSServiceConnection<BSServiceConnectionHost> *_connection;	// 24 = 0x18
    NSDate *_connectDate;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x002000000005c42a
- (void)appendDescriptionToFormatter:(id)arg1;	// IMP=0x001000000005c393
@property(readonly, copy) NSString *description;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

