//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@class NSString;

@interface ABSPBFavoritesEntry : PBCodable
{
    int _abIdentifier;	// 8 = 0x8
    NSString *_actionType;	// 16 = 0x10
    NSString *_bundleIdentifier;	// 24 = 0x18
    int _entryType;	// 32 = 0x20
    NSString *_guid;	// 40 = 0x28
    NSString *_label;	// 48 = 0x30
    NSString *_name;	// 56 = 0x38
    int _property;	// 64 = 0x40
    NSString *_value;	// 72 = 0x48
    struct {
        unsigned int abIdentifier:1;
        unsigned int entryType:1;
        unsigned int property:1;
    } _has;	// 80 = 0x50
}

- (void).cxx_destruct;	// IMP=0x0020000000003eb2
@property(retain, nonatomic) NSString *bundleIdentifier; // @synthesize bundleIdentifier=_bundleIdentifier;
@property(retain, nonatomic) NSString *actionType; // @synthesize actionType=_actionType;
@property(retain, nonatomic) NSString *guid; // @synthesize guid=_guid;
@property(retain, nonatomic) NSString *label; // @synthesize label=_label;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *value; // @synthesize value=_value;
@property(nonatomic) int property; // @synthesize property=_property;
@property(nonatomic) int abIdentifier; // @synthesize abIdentifier=_abIdentifier;
@property(nonatomic) int entryType; // @synthesize entryType=_entryType;
- (void)mergeFrom:(id)arg1;	// IMP=0x0010000000003c69
- (unsigned long long)hash;	// IMP=0x0010000000003b45
- (_Bool)isEqual:(id)arg1;	// IMP=0x0010000000003921
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0010000000003792
- (void)copyTo:(id)arg1;	// IMP=0x0010000000003657
- (void)writeTo:(id)arg1;	// IMP=0x0010000000003519
- (_Bool)readFrom:(id)arg1;	// IMP=0x001000000000350c
- (id)dictionaryRepresentation;	// IMP=0x0010000000002efa
- (id)description;	// IMP=0x0010000000002e4b
@property(readonly, nonatomic) _Bool hasBundleIdentifier;
@property(readonly, nonatomic) _Bool hasActionType;
@property(readonly, nonatomic) _Bool hasGuid;
@property(readonly, nonatomic) _Bool hasLabel;
@property(readonly, nonatomic) _Bool hasName;
@property(readonly, nonatomic) _Bool hasValue;
@property(nonatomic) _Bool hasProperty;
@property(nonatomic) _Bool hasAbIdentifier;
@property(nonatomic) _Bool hasEntryType;

@end

