//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface IPCMessageObject : NSObject
{
}

+ (id)_dictionaryValueFromData:(id)arg1;	// IMP=0x002000000000cfe3
+ (_Bool)supportsSecureCoding;	// IMP=0x001000000000cf31
- (id)initWithCoder:(id)arg1;	// IMP=0x002000000000d21f
- (void)encodeWithCoder:(id)arg1;	// IMP=0x001000000000d1a6
- (id)_dataValue;	// IMP=0x001000000000cf39
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x001000000000cea7
@property(readonly) unsigned long long hash;
- (_Bool)isEqual:(id)arg1;	// IMP=0x001000000000cdb6
- (id)dictionaryValue;	// IMP=0x001000000000cda9
- (id)initWithDictionary:(id)arg1;	// IMP=0x001000000000cd58
- (id)init;	// IMP=0x001000000000cd3f

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end

