//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MDState, MapsPushManager, NSString;

@interface MDDevicePushManager : NSObject
{
    MDState *_state;	// 8 = 0x8
    MapsPushManager *_pushManager;	// 16 = 0x10
}

- (void).cxx_destruct;	// IMP=0x002000000000cd17
- (void)pushManager:(id)arg1 receivedPhotoLivenessMUID:(id)arg2 title:(id)arg3 message:(id)arg4 actionURL:(id)arg5;	// IMP=0x001000000000cc6b
- (void)pushManager:(id)arg1 receivedFixedProblemNotification:(id)arg2 manifestToken:(id)arg3;	// IMP=0x001000000000c902
- (void)pushManager:(id)arg1 gotPushData:(id)arg2;	// IMP=0x001000000000c5bd
- (void)_cleanupRAPNotifications;	// IMP=0x001000000000c3f8
- (_Bool)_shouldDisplayNotificationForProblemStatus:(id)arg1;	// IMP=0x001000000000c353
- (void)simulateUGCPhotoSubmissionResolution;	// IMP=0x001000000000c33d
- (void)simulateProblemResolution;	// IMP=0x001000000000c327
- (id)devicePushToken;	// IMP=0x001000000000c311
- (void)dealloc;	// IMP=0x001000000000c2bb
- (id)initWithState:(id)arg1;	// IMP=0x001000000000c203

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

