//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <FileProviderDaemon/FPDDomainIndexer.h>

@class MISSING_TYPE;

@interface _TtC9libfssync11FPFSIndexer : FPDDomainIndexer
{
    MISSING_TYPE *enumerator;	// 8 = 0x8
    MISSING_TYPE *lastIndexedAnchor;	// 0 = 0x0
    MISSING_TYPE *spotlightIndexer;	// 7120232 = 0x6ca568
}

- (void).cxx_destruct;	// IMP=0x00400000005a4bc0
- (id)init;	// IMP=0x00100000005a4b40
- (id)initWithExtension:(id)arg1 domain:(id)arg2 enabled:(_Bool)arg3;	// IMP=0x00100000005a4b00
- (void)dumpStateTo:(id)arg1;	// IMP=0x00100000005a4a60
- (void)indexOneBatchWithCompletionHandler:(CDUnknownBlockType)arg1;	// IMP=0x00100000005a4a00
@property(nonatomic, readonly) _Bool learnNeedsAuthenticationFromBatchError;

@end

