//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class BCCloudDataManager, NSArray;

@protocol BDSCloudDataManagerMonitor
- (void)dataManager:(BCCloudDataManager *)arg1 didInsertNewRecords:(NSArray *)arg2;
@end

