//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <Foundation/NSValueTransformer.h>

@interface CKRecordSystemFieldsTransformer : NSValueTransformer
{
}

+ (Class)transformedValueClass;	// IMP=0x004000000004f09e
- (id)reverseTransformedValue:(id)arg1;	// IMP=0x004000000004f17e
- (id)transformedValue:(id)arg1;	// IMP=0x001000000004f0af

@end

