//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString, REMList;
@protocol DADREMUserNotificationContent;

@protocol DADREMUserNotificationPresenting
- (id <DADREMUserNotificationContent>)calDAVSharedListNotificationContentWithList:(REMList *)arg1;
- (void)showNotificationWithIdentifier:(NSString *)arg1 content:(id <DADREMUserNotificationContent>)arg2 completion:(void (^)(NSError *))arg3;
@end

