//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSString;

@interface REMCDAuxiliaryReminderChangeDeleteInfo
{
}

+ (id)cdEntityName;	// IMP=0x0010000000063760
+ (_Bool)isAbstract;	// IMP=0x0010000000063758
+ (id)fetchRequest;	// IMP=0x001000000006aef5

// Remaining properties
@property(copy, nonatomic) NSString *oldExternalIdentifier; // @dynamic oldExternalIdentifier;
@property(copy, nonatomic) NSString *oldListIdentifier; // @dynamic oldListIdentifier;

@end

