//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE, NSString;

@interface NPSDatabase : NSObject
{
    NSString *_path;	// 8 = 0x8
    unsigned long long _version;	// 16 = 0x10
    struct sqlite3 *_db;	// 24 = 0x18
    struct sqlite3_stmt *_getMessageTypeForMessageID;	// 32 = 0x20
    struct sqlite3_stmt *_setMessageTypeForMessageID;	// 40 = 0x28
    struct sqlite3_stmt *_setMessageIDForSettingSync;	// 48 = 0x30
    struct sqlite3_stmt *_setMessageIDForSettingBackup;	// 56 = 0x38
    struct sqlite3_stmt *_setMessageIDForFileBackup;	// 64 = 0x40
    struct sqlite3_stmt *_untrackSettingsSyncMessage;	// 72 = 0x48
    struct sqlite3_stmt *_untrackSettingsBackupMessage;	// 80 = 0x50
    struct sqlite3_stmt *_untrackFileBackupMessage;	// 88 = 0x58
    struct sqlite3_stmt *_untrackSettingsSyncForMessageID;	// 96 = 0x60
    struct sqlite3_stmt *_untrackSettingsBackupForMessageID;	// 104 = 0x68
    struct sqlite3_stmt *_untrackFileBackupForMessageID;	// 112 = 0x70
    struct sqlite3_stmt *_removeMessageFromMessageTypeTable;	// 120 = 0x78
    struct sqlite3_stmt *_setNullMessageIDForSettingSync;	// 128 = 0x80
    struct sqlite3_stmt *_setNullMessageIDForSettingBackup;	// 136 = 0x88
    struct sqlite3_stmt *_setNullMessageIDForFileBackup;	// 144 = 0x90
    struct sqlite3_stmt *_getSettingsSyncForMessageID;	// 152 = 0x98
    struct sqlite3_stmt *_getSettingsBackupForMessageID;	// 160 = 0xa0
    struct sqlite3_stmt *_getFileBackupForMessageID;	// 168 = 0xa8
    struct sqlite3_stmt *_getSettingsSyncWithNullMessageID;	// 176 = 0xb0
    struct sqlite3_stmt *_getSettingsBackupWithNullMessageID;	// 184 = 0xb8
    struct sqlite3_stmt *_getFileBackupWithNullMessageID;	// 192 = 0xc0
    struct sqlite3_stmt *_stashSettingsSyncData;	// 200 = 0xc8
    struct sqlite3_stmt *_getStashedSettingSyncData;	// 208 = 0xd0
    struct sqlite3_stmt *_flushStashedSettingSyncData;	// 216 = 0xd8
    struct sqlite3_stmt *_purgeMessageTypeTable;	// 224 = 0xe0
    struct sqlite3_stmt *_purgeSettingsSyncTable;	// 232 = 0xe8
    struct sqlite3_stmt *_purgeSettingsBackupTable;	// 240 = 0xf0
    struct sqlite3_stmt *_purgeFileBackupTable;	// 248 = 0xf8
}

- (MISSING_TYPE *).cxx_destruct;	// IMP=0x00200000000222ad
@property(nonatomic) struct sqlite3_stmt *purgeFileBackupTable; // @synthesize purgeFileBackupTable=_purgeFileBackupTable;
@property(nonatomic) struct sqlite3_stmt *purgeSettingsBackupTable; // @synthesize purgeSettingsBackupTable=_purgeSettingsBackupTable;
@property(nonatomic) struct sqlite3_stmt *purgeSettingsSyncTable; // @synthesize purgeSettingsSyncTable=_purgeSettingsSyncTable;
@property(nonatomic) struct sqlite3_stmt *purgeMessageTypeTable; // @synthesize purgeMessageTypeTable=_purgeMessageTypeTable;
@property(nonatomic) struct sqlite3_stmt *flushStashedSettingSyncData; // @synthesize flushStashedSettingSyncData=_flushStashedSettingSyncData;
@property(nonatomic) struct sqlite3_stmt *getStashedSettingSyncData; // @synthesize getStashedSettingSyncData=_getStashedSettingSyncData;
@property(nonatomic) struct sqlite3_stmt *stashSettingsSyncData; // @synthesize stashSettingsSyncData=_stashSettingsSyncData;
@property(nonatomic) struct sqlite3_stmt *getFileBackupWithNullMessageID; // @synthesize getFileBackupWithNullMessageID=_getFileBackupWithNullMessageID;
@property(nonatomic) struct sqlite3_stmt *getSettingsBackupWithNullMessageID; // @synthesize getSettingsBackupWithNullMessageID=_getSettingsBackupWithNullMessageID;
@property(nonatomic) struct sqlite3_stmt *getSettingsSyncWithNullMessageID; // @synthesize getSettingsSyncWithNullMessageID=_getSettingsSyncWithNullMessageID;
@property(nonatomic) struct sqlite3_stmt *getFileBackupForMessageID; // @synthesize getFileBackupForMessageID=_getFileBackupForMessageID;
@property(nonatomic) struct sqlite3_stmt *getSettingsBackupForMessageID; // @synthesize getSettingsBackupForMessageID=_getSettingsBackupForMessageID;
@property(nonatomic) struct sqlite3_stmt *getSettingsSyncForMessageID; // @synthesize getSettingsSyncForMessageID=_getSettingsSyncForMessageID;
@property(nonatomic) struct sqlite3_stmt *setNullMessageIDForFileBackup; // @synthesize setNullMessageIDForFileBackup=_setNullMessageIDForFileBackup;
@property(nonatomic) struct sqlite3_stmt *setNullMessageIDForSettingBackup; // @synthesize setNullMessageIDForSettingBackup=_setNullMessageIDForSettingBackup;
@property(nonatomic) struct sqlite3_stmt *setNullMessageIDForSettingSync; // @synthesize setNullMessageIDForSettingSync=_setNullMessageIDForSettingSync;
@property(nonatomic) struct sqlite3_stmt *removeMessageFromMessageTypeTable; // @synthesize removeMessageFromMessageTypeTable=_removeMessageFromMessageTypeTable;
@property(nonatomic) struct sqlite3_stmt *untrackFileBackupForMessageID; // @synthesize untrackFileBackupForMessageID=_untrackFileBackupForMessageID;
@property(nonatomic) struct sqlite3_stmt *untrackSettingsBackupForMessageID; // @synthesize untrackSettingsBackupForMessageID=_untrackSettingsBackupForMessageID;
@property(nonatomic) struct sqlite3_stmt *untrackSettingsSyncForMessageID; // @synthesize untrackSettingsSyncForMessageID=_untrackSettingsSyncForMessageID;
@property(nonatomic) struct sqlite3_stmt *untrackFileBackupMessage; // @synthesize untrackFileBackupMessage=_untrackFileBackupMessage;
@property(nonatomic) struct sqlite3_stmt *untrackSettingsBackupMessage; // @synthesize untrackSettingsBackupMessage=_untrackSettingsBackupMessage;
@property(nonatomic) struct sqlite3_stmt *untrackSettingsSyncMessage; // @synthesize untrackSettingsSyncMessage=_untrackSettingsSyncMessage;
@property(nonatomic) struct sqlite3_stmt *setMessageIDForFileBackup; // @synthesize setMessageIDForFileBackup=_setMessageIDForFileBackup;
@property(nonatomic) struct sqlite3_stmt *setMessageIDForSettingBackup; // @synthesize setMessageIDForSettingBackup=_setMessageIDForSettingBackup;
@property(nonatomic) struct sqlite3_stmt *setMessageIDForSettingSync; // @synthesize setMessageIDForSettingSync=_setMessageIDForSettingSync;
@property(nonatomic) struct sqlite3_stmt *setMessageTypeForMessageID; // @synthesize setMessageTypeForMessageID=_setMessageTypeForMessageID;
@property(nonatomic) struct sqlite3_stmt *getMessageTypeForMessageID; // @synthesize getMessageTypeForMessageID=_getMessageTypeForMessageID;
@property(nonatomic) struct sqlite3 *db; // @synthesize db=_db;
@property(readonly, nonatomic) unsigned long long version; // @synthesize version=_version;
@property(retain, nonatomic) NSString *path; // @synthesize path=_path;
- (_Bool)_openDBAtPath:(id)arg1;	// IMP=0x0010000000020793
- (int)_getSchemaVersion;	// IMP=0x001000000002056b
- (void)purgePendingOutgoingMessages;	// IMP=0x00100000000202e5
- (void)flushStashedSettingsSyncData;	// IMP=0x001000000002006a
- (void)getStashedSettingsSyncDataWithHandler:(CDUnknownBlockType)arg1;	// IMP=0x001000000001fe50
- (void)stashSettingsSyncData:(id)arg1 forDomain:(id)arg2 key:(id)arg3 isTwoWaySync:(_Bool)arg4 timestamp:(double)arg5;	// IMP=0x001000000001fa77
- (void)getFileBackupDataForMessage:(id)arg1 handler:(CDUnknownBlockType)arg2;	// IMP=0x001000000001f7f0
- (void)getSettingsBackupDataForMessage:(id)arg1 handler:(CDUnknownBlockType)arg2;	// IMP=0x001000000001f3c9
- (void)getSettingsSyncDataForMessage:(id)arg1 handler:(CDUnknownBlockType)arg2;	// IMP=0x001000000001efee
- (void)messageWasPurged:(id)arg1;	// IMP=0x001000000001ecf0
- (void)messageWasDelivered:(id)arg1;	// IMP=0x001000000001e9f5
- (void)untrackFileBackupMessageForFileAtPath:(id)arg1;	// IMP=0x001000000001e751
- (void)sentFileBackupMessage:(id)arg1 forFileAtPath:(id)arg2;	// IMP=0x001000000001e444
- (void)untrackSettingsBackupMessageForContainer:(id)arg1 domain:(id)arg2 keys:(id)arg3;	// IMP=0x001000000001e00c
- (void)sentSettingsBackupMessage:(id)arg1 forContainer:(id)arg2 domain:(id)arg3 keys:(id)arg4;	// IMP=0x001000000001db64
- (void)untrackSettingsSyncMessagesForDomain:(id)arg1 keys:(id)arg2 cloudEnabled:(_Bool)arg3;	// IMP=0x001000000001d73f
- (void)sentSettingsSyncMessage:(id)arg1 forDomain:(id)arg2 keys:(id)arg3 cloudEnabled:(_Bool)arg4;	// IMP=0x001000000001d110
- (_Bool)removeMessageFromMessageTypeTable:(id)arg1;	// IMP=0x001000000001cffb
- (_Bool)getMessageType:(int *)arg1 forMessageID:(id)arg2;	// IMP=0x001000000001ced2
- (_Bool)setMessageType:(int)arg1 forMessageID:(id)arg2;	// IMP=0x001000000001cd3e
- (void)invalidate;	// IMP=0x001000000001cbe6
- (void)dealloc;	// IMP=0x001000000001cba8
- (id)initWithPath:(id)arg1;	// IMP=0x001000000001caf0

@end

