//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ProtocolBuffer/PBCodable.h>

@class NSData, NSString;

@interface NPSManagedConfigurationMsg : PBCodable
{
    NSString *_feature;	// 8 = 0x8
    NSString *_kind;	// 16 = 0x10
    NSData *_restriction;	// 24 = 0x18
    NSData *_setting;	// 32 = 0x20
    NSData *_userSettingsAndRestrictions;	// 40 = 0x28
}

- (void).cxx_destruct;	// IMP=0x0020000000002967
@property(retain, nonatomic) NSData *userSettingsAndRestrictions; // @synthesize userSettingsAndRestrictions=_userSettingsAndRestrictions;
@property(retain, nonatomic) NSData *restriction; // @synthesize restriction=_restriction;
@property(retain, nonatomic) NSData *setting; // @synthesize setting=_setting;
@property(retain, nonatomic) NSString *feature; // @synthesize feature=_feature;
@property(retain, nonatomic) NSString *kind; // @synthesize kind=_kind;
- (void)mergeFrom:(id)arg1;	// IMP=0x00100000000027eb
- (unsigned long long)hash;	// IMP=0x0010000000002748
- (_Bool)isEqual:(id)arg1;	// IMP=0x00100000000025e8
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x00100000000024d0
- (void)copyTo:(id)arg1;	// IMP=0x001000000000240d
- (void)writeTo:(id)arg1;	// IMP=0x0010000000002359
- (_Bool)readFrom:(id)arg1;	// IMP=0x001000000000234c
- (id)dictionaryRepresentation;	// IMP=0x0010000000002050
- (id)description;	// IMP=0x0010000000001fa1
@property(readonly, nonatomic) _Bool hasUserSettingsAndRestrictions;
@property(readonly, nonatomic) _Bool hasRestriction;
@property(readonly, nonatomic) _Bool hasSetting;
@property(readonly, nonatomic) _Bool hasFeature;
@property(readonly, nonatomic) _Bool hasKind;

@end

