//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <ConfigurationEngineModel/CEMImageDeclaration.h>

@class NSString;

@interface CEMImageDeclaration (DMDAdditions)
- (id)dmf_removeAssetOperationWithInstallMetadata:(id)arg1 error:(id *)arg2;	// IMP=0x00200000000069c2
- (id)dmf_installAssetOperationWithReferenceResolver:(id)arg1 error:(id *)arg2;	// IMP=0x0010000000006966

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@end

