//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface DMDCoreTelephonyUtilities : NSObject
{
}

+ (_Bool)_supportsVoiceRoaming;	// IMP=0x002000000003b93e
+ (_Bool)hasCDMA;	// IMP=0x001000000003b90b
+ (_Bool)hasGSM;	// IMP=0x001000000003b8d8
+ (void)setVoiceRoamingEnabled:(_Bool)arg1;	// IMP=0x001000000003b8d2
+ (_Bool)voiceRoamingEnabled;	// IMP=0x001000000003b8ca
+ (_Bool)isRoaming;	// IMP=0x001000000003b8c2
+ (_Bool)isSubscriptionRoaming:(id)arg1 client:(id)arg2;	// IMP=0x001000000003b8ba
+ (void)setDataRoamingEnabled:(_Bool)arg1;	// IMP=0x001000000003b8b4
+ (_Bool)dataRoamingEnabled;	// IMP=0x001000000003b8ac
+ (id)currentMobileNetworkCode;	// IMP=0x001000000003b8a4
+ (id)currentMobileCountryCode;	// IMP=0x001000000003b89c
+ (id)carrierBundleVersion;	// IMP=0x001000000003b894
+ (id)carrierName;	// IMP=0x001000000003b820
+ (id)currentNetworkName;	// IMP=0x001000000003b818
+ (id)ICCID;	// IMP=0x001000000003b810
+ (id)modemFirmwareVersion;	// IMP=0x001000000003b808
+ (id)MEID;	// IMP=0x001000000003b800
+ (id)IMEI;	// IMP=0x001000000003b7f8
+ (id)formattedICCIDStringFromString:(id)arg1;	// IMP=0x001000000003b6f2
+ (id)formattedIMEIStringFromString:(id)arg1;	// IMP=0x001000000003b5fe

@end

