//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface DMDFetchLocationOperation
{
}

+ (_Bool)validateRequest:(id)arg1 error:(id *)arg2;	// IMP=0x0040000000053fda
+ (id)requiredEntitlements;	// IMP=0x0010000000053fcd
+ (id)whitelistedClassesForRequest;	// IMP=0x0010000000053f9b
- (void)runWithRequest:(id)arg1;	// IMP=0x0010000000054104

@end

