//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface DMDMDMUtilities : NSObject
{
}

+ (_Bool)setSkipBackupAttribute:(_Bool)arg1 toItemAtPath:(id)arg2;	// IMP=0x0040000000063905
+ (id)iTunesAccountHashForUniqueIdentifier:(id)arg1;	// IMP=0x0010000000063816

@end

