//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface DMDSetDataRoamingEnabledOperation
{
}

+ (id)requiredEntitlements;	// IMP=0x00400000000796ec
+ (id)whitelistedClassesForRequest;	// IMP=0x00100000000796ba
- (void)runWithRequest:(id)arg1;	// IMP=0x00100000000796f9

@end

