//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface DMDUserNotificationQueueEntry : NSObject
{
    _Bool _displayOnLockScreen;	// 8 = 0x8
    _Bool _displayInAppWhitelistModes;	// 9 = 0x9
    NSString *_identifier;	// 16 = 0x10
    NSString *_title;	// 24 = 0x18
    NSString *_message;	// 32 = 0x20
    NSString *_defaultButtonText;	// 40 = 0x28
    NSString *_alternateButtonText;	// 48 = 0x30
    NSString *_otherButtonText;	// 56 = 0x38
    double _dismissAfterTimeInterval;	// 64 = 0x40
    CDUnknownBlockType _completionBlock;	// 72 = 0x48
    id _notification;	// 80 = 0x50
}

- (void).cxx_destruct;	// IMP=0x0020000000083f80
@property(retain, nonatomic) id notification; // @synthesize notification=_notification;
@property(copy, nonatomic) CDUnknownBlockType completionBlock; // @synthesize completionBlock=_completionBlock;
@property(nonatomic) double dismissAfterTimeInterval; // @synthesize dismissAfterTimeInterval=_dismissAfterTimeInterval;
@property(nonatomic) _Bool displayInAppWhitelistModes; // @synthesize displayInAppWhitelistModes=_displayInAppWhitelistModes;
@property(nonatomic) _Bool displayOnLockScreen; // @synthesize displayOnLockScreen=_displayOnLockScreen;
@property(retain, nonatomic) NSString *otherButtonText; // @synthesize otherButtonText=_otherButtonText;
@property(retain, nonatomic) NSString *alternateButtonText; // @synthesize alternateButtonText=_alternateButtonText;
@property(retain, nonatomic) NSString *defaultButtonText; // @synthesize defaultButtonText=_defaultButtonText;
@property(retain, nonatomic) NSString *message; // @synthesize message=_message;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;

@end

