//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSCopying-Protocol.h"
#import "NSObject-Protocol.h"

@class NSArray, NSString;

@protocol CHSWidgetConfigurationHost <NSObject, NSCopying>
- (NSArray *)widgetConfigurationsForApplicationContainerBundleIdentifier:(NSString *)arg1;
@property(nonatomic, readonly) NSArray *widgetConfigurations;
@property(nonatomic, readonly) NSString *identifier;
@end

