//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class GKClientProxy, GKResourceManager, NSManagedObjectContext;

@interface GKCacheTransactionGroup
{
    NSManagedObjectContext *_context;	// 64 = 0x40
    GKClientProxy *_client;	// 72 = 0x48
    GKResourceManager *_resourceManager;	// 80 = 0x50
}

+ (id)transactionGroupWithContext:(id)arg1 resourceManager:(id)arg2 client:(id)arg3;	// IMP=0x004000000013711c
+ (id)dispatchGroupWithName:(id)arg1;	// IMP=0x0010000000137003
+ (id)dispatchGroup;	// IMP=0x0010000000136eea
- (void).cxx_destruct;	// IMP=0x0020000000138ce8
@property(nonatomic) __weak GKResourceManager *resourceManager; // @synthesize resourceManager=_resourceManager;
@property(retain, nonatomic) GKClientProxy *client; // @synthesize client=_client;
@property(retain, nonatomic) NSManagedObjectContext *context; // @synthesize context=_context;
- (void)notifyOnMainQueueWithBlock:(CDUnknownBlockType)arg1;	// IMP=0x0010000000138b4c
- (void)notifyOnQueue:(id)arg1 block:(CDUnknownBlockType)arg2;	// IMP=0x00100000001389d7
- (void)stripGKPlayerInternalPIIs;	// IMP=0x00100000001385f9
- (void)performOnQueue:(id)arg1 block:(CDUnknownBlockType)arg2;	// IMP=0x001000000013848a
- (void)readResources:(id)arg1 queue:(id)arg2 block:(CDUnknownBlockType)arg3;	// IMP=0x001000000013831b
- (void)writeResources:(id)arg1 queue:(id)arg2 block:(CDUnknownBlockType)arg3;	// IMP=0x0010000000138309
- (void)performAndJoinForResources:(id)arg1 queue:(id)arg2 block:(CDUnknownBlockType)arg3;	// IMP=0x0010000000138054
- (void)performOnManagedObjectContext:(CDUnknownBlockType)arg1;	// IMP=0x0010000000137d3e
- (void)dealloc;	// IMP=0x00100000001379b0
- (id)initWithName:(id)arg1 context:(id)arg2 resourceManager:(id)arg3 client:(id)arg4;	// IMP=0x001000000013766c
- (id)initWithName:(id)arg1;	// IMP=0x001000000013754a
- (id)transactionGroup;	// IMP=0x00100000001373ff

@end

