//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class GKGameCacheObject, GKPlayerProfileCacheObject, NSDate, NSNumber, NSSet, NSString;

@interface GKLeaderboardCacheObject
{
}

+ (id)entityName;	// IMP=0x0020000000064f6f
- (id)internalRepresentation;	// IMP=0x0020000000064ac8
- (void)updateWithServerRepresentation:(id)arg1;	// IMP=0x00100000000641d5

// Remaining properties
@property(retain, nonatomic) NSString *baseLeaderboardID; // @dynamic baseLeaderboardID;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(retain, nonatomic) NSNumber *duration; // @dynamic duration;
@property(retain, nonatomic) NSNumber *friendRank; // @dynamic friendRank;
@property(retain, nonatomic) GKGameCacheObject *game; // @dynamic game;
@property(retain, nonatomic) NSString *groupIdentifier; // @dynamic groupIdentifier;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) NSString *identifier; // @dynamic identifier;
@property(retain, nonatomic) NSString *image128; // @dynamic image128;
@property(retain, nonatomic) NSString *image256; // @dynamic image256;
@property(retain, nonatomic) NSString *image512; // @dynamic image512;
@property(retain, nonatomic) NSString *image64; // @dynamic image64;
@property(retain, nonatomic) NSString *imageTemplate; // @dynamic imageTemplate;
@property(nonatomic) _Bool isPrimary; // @dynamic isPrimary;
@property(retain, nonatomic) NSDate *lastSubmittedDate; // @dynamic lastSubmittedDate;
@property(retain, nonatomic) NSSet *listEntries; // @dynamic listEntries;
@property(retain, nonatomic) NSString *localizedTitle; // @dynamic localizedTitle;
@property(retain, nonatomic) NSNumber *maxFriendRank; // @dynamic maxFriendRank;
@property(retain, nonatomic) NSNumber *maxRank; // @dynamic maxRank;
@property(retain, nonatomic) NSDate *nextStartDate; // @dynamic nextStartDate;
@property(retain, nonatomic) GKPlayerProfileCacheObject *player; // @dynamic player;
@property(retain, nonatomic) GKLeaderboardCacheObject *previousInstance; // @dynamic previousInstance;
@property(nonatomic) _Bool previousInstanceLoaded; // @dynamic previousInstanceLoaded;
@property(retain, nonatomic) NSNumber *rank; // @dynamic rank;
@property(retain, nonatomic) NSString *recordID; // @dynamic recordID;
@property(retain, nonatomic) NSString *scoreType; // @dynamic scoreType;
@property(retain, nonatomic) NSDate *startDate; // @dynamic startDate;
@property(readonly) Class superclass;
@property(retain, nonatomic) NSString *type; // @dynamic type;

@end

