//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MediaConversionQueueEntry, NSMutableArray, NSString, PFCameraViewfinderSessionWatcher;
@protocol MediaConversionQueueDelegate, OS_dispatch_queue;

@interface MediaConversionQueue : NSObject
{
    struct os_unfair_lock_s _queueStateLock;	// 8 = 0x8
    unsigned long long _queueEntryCounter;	// 16 = 0x10
    unsigned long long _requestCounter;	// 24 = 0x18
    NSMutableArray *_queuedRequests;	// 32 = 0x20
    NSObject<OS_dispatch_queue> *_requestProcessingQueue;	// 40 = 0x28
    NSObject<OS_dispatch_queue> *_cameraWatcherQueue;	// 48 = 0x30
    MediaConversionQueueEntry *_currentlyProcessingRequestQueueEntry;	// 56 = 0x38
    NSObject<MediaConversionQueueDelegate> *_delegate;	// 64 = 0x40
    PFCameraViewfinderSessionWatcher *_cameraWatcher;	// 72 = 0x48
}

- (void).cxx_destruct;	// IMP=0x002000000000e163
@property(retain) PFCameraViewfinderSessionWatcher *cameraWatcher; // @synthesize cameraWatcher=_cameraWatcher;
@property __weak NSObject<MediaConversionQueueDelegate> *delegate; // @synthesize delegate=_delegate;
@property(retain) MediaConversionQueueEntry *currentlyProcessingRequestQueueEntry; // @synthesize currentlyProcessingRequestQueueEntry=_currentlyProcessingRequestQueueEntry;
@property(retain) NSObject<OS_dispatch_queue> *cameraWatcherQueue; // @synthesize cameraWatcherQueue=_cameraWatcherQueue;
@property(retain) NSObject<OS_dispatch_queue> *requestProcessingQueue; // @synthesize requestProcessingQueue=_requestProcessingQueue;
@property(retain) NSMutableArray *queuedRequests; // @synthesize queuedRequests=_queuedRequests;
@property unsigned long long requestCounter; // @synthesize requestCounter=_requestCounter;
@property unsigned long long queueEntryCounter; // @synthesize queueEntryCounter=_queueEntryCounter;
@property struct os_unfair_lock_s queueStateLock; // @synthesize queueStateLock=_queueStateLock;
- (void)cameraWatcherDidChangeState:(id)arg1;	// IMP=0x001000000000de7d
- (void)sendCancellationReplyForClientRequest:(id)arg1;	// IMP=0x001000000000dc68
- (void)cancelRequestsForConnectionIdentifier:(id)arg1;	// IMP=0x001000000000da5e
- (void)assertDelegate:(id)arg1 respondsToSelector:(SEL)arg2;	// IMP=0x001000000000d91b
- (_Bool)findAndRemoveCancelledRequest:(id *)arg1 queueEntryWithoutRemainingClients:(id *)arg2 forRequestIdentifier:(id)arg3 shouldCancelCurrentQueueEntry:(_Bool *)arg4;	// IMP=0x001000000000d607
- (void)cancelRequestWithIdentifier:(id)arg1;	// IMP=0x001000000000d390
- (void)modifyRequestWithIdentifier:(id)arg1 changeHandler:(CDUnknownBlockType)arg2;	// IMP=0x001000000000d127
- (id)orderingSummaryForRequestList:(id)arg1;	// IMP=0x001000000000d0c6
- (_Bool)copyConversionOutput:(id)arg1 toRequestDestination:(id)arg2 requestIdentifier:(id)arg3 error:(id *)arg4;	// IMP=0x001000000000cec6
- (void)processCompletedQueueEntry:(id)arg1 resultURLCollection:(id)arg2 didConvertSuccessfully:(_Bool)arg3 conversionOutputInformation:(id)arg4 conversionOutputData:(id)arg5 conversionOutputFileType:(id)arg6 conversionError:(id)arg7;	// IMP=0x001000000000c604
- (id)markCompletionAndRetrieveClientRequestsForQueueEntry:(id)arg1 resultURLCollection:(id)arg2 didConvertSuccessfully:(_Bool)arg3 conversionOutputInformation:(id)arg4 conversionOutputData:(id)arg5 conversionOutputFileType:(id)arg6 conversionError:(id)arg7;	// IMP=0x001000000000c3c6
- (id)entriesSortedByExecutionOrderForPendingEntries:(id)arg1;	// IMP=0x001000000000c36d
- (_Bool)cancelForCameraIfPossibleAndRequiredForNextQueueEntry:(id)arg1;	// IMP=0x001000000000bec1
- (id)optimizeQueueAndDequeueNextRequestQueueEntry;	// IMP=0x001000000000bbbd
- (void)processQueue;	// IMP=0x001000000000b9c2
- (void)scheduleQueueProcessing;	// IMP=0x001000000000b977
- (id)anyDestinationURLCollectionForQueueEntry:(id)arg1;	// IMP=0x001000000000b914
- (void)enumerateCurrentlyProcessingAndQueuedEntries:(CDUnknownBlockType)arg1;	// IMP=0x001000000000b85f
- (_Bool)currentlyProcessingRequestQueueEntryIsPresentAndOptional;	// IMP=0x001000000000b828
- (_Bool)enqueueEntry:(id)arg1 clientRequest:(id)arg2 isDuplicateOfOriginalQueueEntry:(id *)arg3;	// IMP=0x001000000000b178
- (id)queueEntryWithConversionOptions:(id)arg1;	// IMP=0x001000000000b04c
- (unsigned long long)nextRequestNumber;	// IMP=0x001000000000b012
- (id)initWithDelegate:(id)arg1;	// IMP=0x001000000000aecc

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

