//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface PAMediaConversionServiceImageMetadataPolicy : NSObject
{
}

+ (_Bool)supportsSecureCoding;	// IMP=0x0020000000001c29
+ (id)standardPolicy;	// IMP=0x0010000000001b2c
- (id)processMetadata:(id)arg1;	// IMP=0x0040000000001b1f
- (_Bool)metadataNeedsProcessing:(id)arg1;	// IMP=0x0010000000001b17
- (void)encodeWithCoder:(id)arg1;	// IMP=0x0010000000001b11
- (id)initWithCoder:(id)arg1;	// IMP=0x0010000000001b08

@end

