//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSArray;

@interface FRAnalyticsPayload : NSObject
{
    NSArray *_payloadItems;	// 8 = 0x8
    NSArray *_envelopes;	// 16 = 0x10
    unsigned long long _maxPayloadSize;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x002000000002eed3
@property(nonatomic) unsigned long long maxPayloadSize; // @synthesize maxPayloadSize=_maxPayloadSize;
@property(retain, nonatomic) NSArray *envelopes; // @synthesize envelopes=_envelopes;
@property(copy, nonatomic) NSArray *payloadItems; // @synthesize payloadItems=_payloadItems;
- (id)_eventProtobufForEventDictionary:(id)arg1;	// IMP=0x001000000002dbe7
- (id)_generateEnvelopes;	// IMP=0x001000000002c6ad
- (id)initWithPayloadItems:(id)arg1 maxPayloadSize:(unsigned long long)arg2;	// IMP=0x001000000002c590
- (id)init;	// IMP=0x001000000002c44b

@end

