//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class FROnboardingSubscribableItem, NSString, TUAnimationFloatFunction;
@protocol FROnboardingExitAnimatorDelegate;

@interface FROnboardingExitAnimator : NSObject
{
    _Bool _isRunning;	// 8 = 0x8
    FROnboardingSubscribableItem *_item;	// 16 = 0x10
    id <FROnboardingExitAnimatorDelegate> _delegate;	// 24 = 0x18
    double _delay;	// 32 = 0x20
    double _duration;	// 40 = 0x28
    double _currentAlpha;	// 48 = 0x30
    double _localTimeElapsed;	// 56 = 0x38
    double _startingTime;	// 64 = 0x40
    TUAnimationFloatFunction *_floatCurveFunction;	// 72 = 0x48
    struct CGPoint _anchorPoint;	// 80 = 0x50
    struct CGAffineTransform _currentTransform;	// 96 = 0x60
}

- (void).cxx_destruct;	// IMP=0x00200000000ab5db
@property(retain, nonatomic) TUAnimationFloatFunction *floatCurveFunction; // @synthesize floatCurveFunction=_floatCurveFunction;
@property(nonatomic) struct CGAffineTransform currentTransform; // @synthesize currentTransform=_currentTransform;
@property(nonatomic) double startingTime; // @synthesize startingTime=_startingTime;
@property(nonatomic) double localTimeElapsed; // @synthesize localTimeElapsed=_localTimeElapsed;
@property(nonatomic) double currentAlpha; // @synthesize currentAlpha=_currentAlpha;
@property(nonatomic) struct CGPoint anchorPoint; // @synthesize anchorPoint=_anchorPoint;
@property(nonatomic) double duration; // @synthesize duration=_duration;
@property(nonatomic) double delay; // @synthesize delay=_delay;
@property(nonatomic) __weak id <FROnboardingExitAnimatorDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) _Bool isRunning; // @synthesize isRunning=_isRunning;
@property(retain, nonatomic) FROnboardingSubscribableItem *item; // @synthesize item=_item;
- (void)updateTickWithAnimationEngine:(id)arg1 sessionTimeAtLastTick:(double)arg2 currentSessionTime:(double)arg3;	// IMP=0x00100000000aaff9
- (void)updateCellWithCurrentStateOfItem:(id)arg1;	// IMP=0x00100000000aaed0
- (void)addedToAnimationEngine:(id)arg1;	// IMP=0x00100000000aae41
- (id)init;	// IMP=0x00100000000aad6d

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

