//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import "NSObject-Protocol.h"

@class NSDictionary, NSString;

@protocol SNTestRunner <NSObject>
- (_Bool)runTest:(NSString *)arg1 options:(NSDictionary *)arg2 fallingBackWith:(_Bool (^)(void))arg3;
- (_Bool)runTest:(NSString *)arg1 options:(NSDictionary *)arg2;
- (_Bool)runExtendedLaunchTest;
@end

