//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@interface CKKSAESSIVKey
{
}

+ (id)randomKey:(id *)arg1;	// IMP=0x00400000001c2a2d
- (id)keyMaterial;	// IMP=0x00400000001c2a01
- (_Bool)doSIV:(const struct ccmode_siv *)arg1 nonce:(id)arg2 text:(id)arg3 buffer:(char *)arg4 bufferLength:(unsigned long long)arg5 authenticatedData:(id)arg6 error:(id *)arg7;	// IMP=0x00100000001c2354
- (id)decryptData:(id)arg1 authenticatedData:(id)arg2 error:(id *)arg3;	// IMP=0x00100000001c20ab
- (id)encryptData:(id)arg1 authenticatedData:(id)arg2 error:(id *)arg3;	// IMP=0x00100000001c1e56
- (id)unwrapAESKey:(id)arg1 error:(id *)arg2;	// IMP=0x00100000001c1c36
- (id)wrapAESKey:(id)arg1 error:(id *)arg2;	// IMP=0x00100000001c19c5
- (id)initWithBase64:(id)arg1;	// IMP=0x00100000001c18e8
- (id)initWithBytes:(char *)arg1 len:(unsigned long long)arg2;	// IMP=0x00100000001c182d
- (id)init;	// IMP=0x00100000001c17f1

@end

