//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <CoreDuet/_DKEvent.h>

@interface _DKEvent (SensorKit)
- (id)sr_dateIntervalsInBucketsOf:(double)arg1 duringQueryInterval:(id)arg2;	// IMP=0x0010000000007114
@end

