//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface SHAudioTap : NSObject
{
    _Bool _isClosed;	// 8 = 0x8
    CDUnknownBlockType _completion;	// 16 = 0x10
    long long _recordingSource;	// 24 = 0x18
    long long _client;	// 32 = 0x20
}

- (void).cxx_destruct;	// IMP=0x002000000000b124
@property(readonly, nonatomic) _Bool isClosed; // @synthesize isClosed=_isClosed;
@property(readonly, nonatomic) long long client; // @synthesize client=_client;
@property(readonly, nonatomic) long long recordingSource; // @synthesize recordingSource=_recordingSource;
@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
- (void)close;	// IMP=0x001000000000b0e4
- (void)open;	// IMP=0x001000000000b0da
- (id)initWithRecordingSource:(long long)arg1 client:(long long)arg2;	// IMP=0x001000000000b092

@end

