//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSURL;

@interface IXOwnedDataPromiseSeed
{
    NSURL *_stagingBaseDir;	// 8 = 0x8
}

+ (_Bool)supportsSecureCoding;	// IMP=0x0020000000030e32
- (void).cxx_destruct;	// IMP=0x0020000000030ed6
@property(retain, nonatomic) NSURL *stagingBaseDir; // @synthesize stagingBaseDir=_stagingBaseDir;
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x0010000000030e3a
- (void)encodeWithCoder:(id)arg1;	// IMP=0x0010000000030d97
- (id)initWithCoder:(id)arg1;	// IMP=0x0010000000030cfc

@end

