//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class IXApplicationIdentity;
@protocol IXSCoordinatorProgressDelegate;

@interface IXSCoordinatorProgress : NSObject
{
    _Bool _installingCompleted;	// 8 = 0x8
    unsigned long long _totalUnitsCompleted;	// 16 = 0x10
    unsigned long long _totalUnits;	// 24 = 0x18
    unsigned long long _progressPhase;	// 32 = 0x20
    double _currentPhaseProgress;	// 40 = 0x28
    IXApplicationIdentity *_identity;	// 48 = 0x30
    id <IXSCoordinatorProgressDelegate> _delegate;	// 56 = 0x38
}

+ (double)_computeOverallProgressForCurrentProgress:(double)arg1 progressPhase:(unsigned long long)arg2;	// IMP=0x004000000000d4b0
- (void).cxx_destruct;	// IMP=0x002000000000d7f9
@property(nonatomic) __weak id <IXSCoordinatorProgressDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) IXApplicationIdentity *identity; // @synthesize identity=_identity;
@property(nonatomic) _Bool installingCompleted; // @synthesize installingCompleted=_installingCompleted;
@property(nonatomic) double currentPhaseProgress; // @synthesize currentPhaseProgress=_currentPhaseProgress;
@property(nonatomic) unsigned long long progressPhase; // @synthesize progressPhase=_progressPhase;
@property(nonatomic) unsigned long long totalUnits; // @synthesize totalUnits=_totalUnits;
@property(nonatomic) unsigned long long totalUnitsCompleted; // @synthesize totalUnitsCompleted=_totalUnitsCompleted;
- (void)_notifyDelegateAndUpdateProgressWithPhaseCompleted:(_Bool)arg1;	// IMP=0x001000000000d4e7
- (void)finishInstalling;	// IMP=0x001000000000d441
- (void)finishLoading;	// IMP=0x001000000000d3d6
- (id)description;	// IMP=0x001000000000d2f4
- (id)initForCoordinatorWithIdentity:(id)arg1 totalUnits:(unsigned long long)arg2 delegate:(id)arg3;	// IMP=0x001000000000d23f

@end

