//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIView.h>

@class MISSING_TYPE;

@interface _TtC5Files18DOCShareBannerView : UIView
{
    MISSING_TYPE *optionsButtonHandler;	// 8 = 0x8
    MISSING_TYPE *containerView;	// 24 = 0x18
    MISSING_TYPE *labelView;	// 32 = 0x20
    MISSING_TYPE *$__lazy_storage_$_optionsButton;	// 40 = 0x28
    MISSING_TYPE *$__lazy_storage_$_topSeparator;	// 48 = 0x30
    MISSING_TYPE *$__lazy_storage_$_bottomSeparator;	// 56 = 0x38
    MISSING_TYPE *metrics;	// 64 = 0x40
}

- (void).cxx_destruct;	// IMP=0x0040000000331140
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x00100000003310e0
- (id)initWithCoder:(id)arg1;	// IMP=0x00100000003310c0
- (id)init;	// IMP=0x00100000003310a0

@end

