//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC5FilesP33_6559D0809CA5F323BA86F5C57192601423DOCSharedOverlayContent : _TtCs12_SwiftObject
{
    MISSING_TYPE *progressSource;	// 16 = 0x10
    MISSING_TYPE *progressButtonItem;	// 24 = 0x18
}

@end

