//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class MISSING_TYPE;

@interface _TtC5Files16DOCActionContext : NSObject
{
    MISSING_TYPE *appearance;	// 8 = 0x8
    MISSING_TYPE *configuration;	// 16 = 0x10
    MISSING_TYPE *presentingViewController;	// 24 = 0x18
    MISSING_TYPE *transitionProxy;	// 32 = 0x20
    MISSING_TYPE *actionReporting;	// 40 = 0x28
    MISSING_TYPE *userInfo;	// 48 = 0x30
    MISSING_TYPE *popoverPresentationSourceItem;	// 56 = 0x38
}

- (void).cxx_destruct;	// IMP=0x004000000027acc0
- (id)init;	// IMP=0x001000000027ac70

@end

