//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@interface _TtC5Files13DOCWorkaround : NSObject
{
}

- (id)init;	// IMP=0x0040000000081590

@end

