//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC5FilesP33_39E00B7F57686CC7F9EA376E8E1834E735DOCSizeCategoryDependantConstraints : _TtCs12_SwiftObject
{
    MISSING_TYPE *constraintsBySizeClass;	// 16 = 0x10
    MISSING_TYPE *activeSizeClass;	// 24 = 0x18
}

@end

