//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <UIKit/UIStackView.h>

@class MISSING_TYPE, NSArray, NSDictionary, UITextPosition, UITextRange;
@protocol UITextInputDelegate, UITextInputTokenizer;

@interface _TtC5FilesP33_D8D362724F0696B48319604C3F2D1F0417DOCTokenChainView : UIStackView
{
    MISSING_TYPE *delegate;	// 8 = 0x8
    MISSING_TYPE *coTextfield;	// 24 = 0x18
    MISSING_TYPE *selection;	// 32 = 0x20
    MISSING_TYPE *font;	// 40 = 0x28
    MISSING_TYPE *tokens;	// 48 = 0x30
    MISSING_TYPE *showTrailingChevron;	// 56 = 0x38
    MISSING_TYPE *isCoalescingRebuildsCount;	// 64 = 0x40
}

- (MISSING_TYPE *).cxx_destruct;	// IMP=0x00400000002651d0
- (void)directionKeyCommand:(id)arg1;	// IMP=0x0010000000264620
- (void)tap:(id)arg1;	// IMP=0x0010000000264600
- (void)deleteBackward;	// IMP=0x00100000002645d0
- (void)insertText:(id)arg1;	// IMP=0x0010000000264550
@property(nonatomic, readonly) _Bool hasText;
- (void)selectAll:(id)arg1;	// IMP=0x00100000002642c0
@property(nonatomic, readonly) NSArray *keyCommands;
- (_Bool)resignFirstResponder;	// IMP=0x0010000000263f70
- (_Bool)becomeFirstResponder;	// IMP=0x0010000000263e00
@property(nonatomic, readonly) _Bool canBecomeFirstResponder;
- (id)initWithCoder:(id)arg1;	// IMP=0x0010000000263b50
- (id)initWithFrame:(struct CGRect)arg1;	// IMP=0x0010000000263b20
- (id)characterRangeAtPoint:(struct CGPoint)arg1;	// IMP=0x0010000000267170
- (id)closestPositionToPoint:(struct CGPoint)arg1 withinRange:(id)arg2;	// IMP=0x0010000000267160
- (id)closestPositionToPoint:(struct CGPoint)arg1;	// IMP=0x0010000000267cf0
- (id)selectionRectsForRange:(id)arg1;	// IMP=0x0010000000267120
- (struct CGRect)caretRectForPosition:(id)arg1;	// IMP=0x0010000000267100
- (struct CGRect)firstRectForRange:(id)arg1;	// IMP=0x0010000000267ca0
- (void)setBaseWritingDirection:(long long)arg1 forRange:(id)arg2;	// IMP=0x00100000002670f0
- (long long)baseWritingDirectionForPosition:(id)arg1 inDirection:(long long)arg2;	// IMP=0x00100000002670d0
- (id)characterRangeByExtendingPosition:(id)arg1 inDirection:(long long)arg2;	// IMP=0x00100000002670c0
- (id)positionWithinRange:(id)arg1 farthestInDirection:(long long)arg2;	// IMP=0x0010000000267cd0
- (long long)offsetFromPosition:(id)arg1 toPosition:(id)arg2;	// IMP=0x00100000002670b0
- (long long)comparePosition:(id)arg1 toPosition:(id)arg2;	// IMP=0x00100000002670a0
- (id)positionFromPosition:(id)arg1 inDirection:(long long)arg2 offset:(long long)arg3;	// IMP=0x0010000000267c90
- (id)positionFromPosition:(id)arg1 offset:(long long)arg2;	// IMP=0x0010000000267ce0
- (id)textRangeFromPosition:(id)arg1 toPosition:(id)arg2;	// IMP=0x0010000000267cc0
@property(nonatomic, retain) UITextPosition *endOfDocument;
@property(nonatomic, retain) UITextPosition *beginningOfDocument;
- (void)unmarkText;	// IMP=0x0010000000267040
- (void)setMarkedText:(id)arg1 selectedRange:(struct _NSRange)arg2;	// IMP=0x0010000000267030
@property(nonatomic, copy) NSDictionary *markedTextStyle;
@property(nonatomic, retain) UITextRange *markedTextRange;
@property(nonatomic, retain) UITextRange *selectedTextRange;
- (void)replaceRange:(id)arg1 withText:(id)arg2;	// IMP=0x0010000000266fe0
- (id)textInRange:(id)arg1;	// IMP=0x0010000000266fd0
@property(nonatomic, retain) id <UITextInputTokenizer> tokenizer;
@property(nonatomic, retain) id <UITextInputDelegate> inputDelegate;
- (_Bool)isPosition:(id)arg1 withinTextUnit:(long long)arg2 inDirection:(long long)arg3;	// IMP=0x0010000000266f70
- (id)positionFromPosition:(id)arg1 toBoundary:(long long)arg2 inDirection:(long long)arg3;	// IMP=0x0010000000267c80
- (_Bool)isPosition:(id)arg1 atBoundary:(long long)arg2 inDirection:(long long)arg3;	// IMP=0x0010000000266f60
- (id)rangeEnclosingPosition:(id)arg1 withGranularity:(long long)arg2 inDirection:(long long)arg3;	// IMP=0x0010000000266f50

@end

