//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSMutableArray;
@protocol OS_dispatch_queue, OS_dispatch_source;

@interface EventMonitor : NSObject
{
    NSObject<OS_dispatch_queue> *_dispatchQueue;	// 8 = 0x8
    NSMutableArray *_events;	// 16 = 0x10
    double _lastPollTime;	// 24 = 0x18
    NSObject<OS_dispatch_source> *_pollTimer;	// 32 = 0x20
}

+ (id)sharedEventMonitor;	// IMP=0x004000000012feed
- (void)_willRemoveEvent:(id)arg1;	// IMP=0x0020000000130a19
- (void)_reloadPollTimer;	// IMP=0x001000000013047e
- (void)_fireEventsAfterPollTimer;	// IMP=0x001000000013018e
- (void)_cancelPollTimer;	// IMP=0x001000000013015f
- (void)removeEvent:(id)arg1;	// IMP=0x0010000000130085
- (id)monitorEvent:(id)arg1;	// IMP=0x001000000012ff6a
- (void)dealloc;	// IMP=0x001000000012fe9c
- (id)init;	// IMP=0x001000000012fe4e

@end

