//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSData, NSDictionary, NSString, SKPaymentDiscount;

@interface SKPayment : NSObject
{
    id _internal;	// 8 = 0x8
}

+ (id)paymentWithProductIdentifier:(id)arg1;	// IMP=0x002000000010cb3a
+ (id)paymentFromPurchaseIntentWithProduct:(id)arg1;	// IMP=0x001000000010ca3f
+ (id)paymentWithProduct:(id)arg1;	// IMP=0x001000000010c955
- (void).cxx_destruct;	// IMP=0x002000000010cd8a
@property(readonly, copy, nonatomic) NSDictionary *requestParameters;
@property(readonly, copy, nonatomic) NSString *partnerTransactionIdentifier;
@property(readonly, copy, nonatomic) NSString *partnerIdentifier;
@property(readonly, nonatomic) _Bool isStoreOriginated;
@property(readonly, copy, nonatomic) SKPaymentDiscount *paymentDiscount;
@property(readonly, nonatomic) _Bool simulatesAskToBuyInSandbox;
@property(readonly, copy, nonatomic) NSData *requestData;
@property(readonly, nonatomic) long long quantity;
@property(readonly, copy, nonatomic) NSString *productIdentifier;
- (_Bool)isEqual:(id)arg1;	// IMP=0x001000000010cc36
- (unsigned long long)hash;	// IMP=0x001000000010cbca
@property(readonly, copy, nonatomic) NSString *applicationUsername;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;	// IMP=0x001000000010c8f1
- (id)copyWithZone:(struct _NSZone *)arg1;	// IMP=0x001000000010c88d
- (id)init;	// IMP=0x001000000010c837

@end

