//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <swiftCore/_TtCs12_SwiftObject.h>

@class MISSING_TYPE;

@interface _TtC8coreidvd12GlobalConfig : _TtCs12_SwiftObject
{
    MISSING_TYPE *SupportedRegions;	// 16 = 0x10
    MISSING_TYPE *SupportedAttributeConfigs;	// 24 = 0x18
    MISSING_TYPE *DefaultRegion;	// 32 = 0x20
}

@end

