//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class CloudArtistHeroImageImporter;

@interface ArtistImageRequestHandler
{
    CloudArtistHeroImageImporter *_importer;	// 8 = 0x8
}

+ (id)accountlessHandler;	// IMP=0x0040000000103a42
+ (_Bool)supportsAccountlessHandling;	// IMP=0x001000000010394d
+ (id)handlers;	// IMP=0x001000000010391d
- (void).cxx_destruct;	// IMP=0x002000000010390a
@property(readonly, nonatomic) CloudArtistHeroImageImporter *importer; // @synthesize importer=_importer;
- (void)deprioritizeAlbumArtistHeroImageForPersistentID:(long long)arg1;	// IMP=0x00100000001038dc
- (void)deprioritizeArtistHeroImageForPersistentID:(long long)arg1;	// IMP=0x00100000001038bf
- (void)importAlbumArtistHeroImageForPersistentID:(long long)arg1 clientIdentity:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x00100000001038a2
- (void)importArtistHeroImageForPersistentID:(long long)arg1 clientIdentity:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;	// IMP=0x0010000000103885
- (void)cancelAllOperationsAndWaitForOperationsToFinish:(_Bool)arg1;	// IMP=0x0010000000103868
- (void)cancelAllOperations;	// IMP=0x0010000000103854
- (void)updateArtistHeroImagesForArtistsAddedSinceLastUpdateUsingClientIdentity:(id)arg1;	// IMP=0x001000000010376d
- (void)updateArtistHeroImagesWithClientIdentity:(id)arg1;	// IMP=0x0010000000103750
- (id)initWithConfiguration:(id)arg1;	// IMP=0x00100000001035aa

@end

