//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

#import <objc/NSObject.h>

@class NSString;

@interface UpdateResponseParserDelegate : NSObject
{
    _Bool _hasAddToPlaylistBehavior;	// 8 = 0x8
    unsigned char _addToPlaylistBehavior;	// 9 = 0x9
    unsigned int _serverRevision;	// 12 = 0xc
}

@property(nonatomic) unsigned char addToPlaylistBehavior; // @synthesize addToPlaylistBehavior=_addToPlaylistBehavior;
@property(nonatomic) _Bool hasAddToPlaylistBehavior; // @synthesize hasAddToPlaylistBehavior=_hasAddToPlaylistBehavior;
@property(nonatomic) unsigned int serverRevision; // @synthesize serverRevision=_serverRevision;
- (void)parser:(id)arg1 didParseDataCode:(unsigned int)arg2 bytes:(char *)arg3 contentLength:(unsigned int)arg4;	// IMP=0x001000000001a33b
- (_Bool)parser:(id)arg1 shouldParseCodeAsContainer:(unsigned int)arg2;	// IMP=0x001000000001a32c
- (_Bool)parser:(id)arg1 shouldParseCode:(unsigned int)arg2;	// IMP=0x001000000001a30a

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

