//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class NSArray;

@interface HSPCEnterCodeViewController
{
    unsigned long long _numberOfDigits;	// 8 = 0x8
    NSArray *_digitsAfterDashes;	// 16 = 0x10
    NSArray *_dashLocations;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x002000000002180f
@property(retain, nonatomic) NSArray *dashLocations; // @synthesize dashLocations=_dashLocations;
@property(retain, nonatomic) NSArray *digitsAfterDashes; // @synthesize digitsAfterDashes=_digitsAfterDashes;
@property(nonatomic) unsigned long long numberOfDigits; // @synthesize numberOfDigits=_numberOfDigits;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;	// IMP=0x0010000000020dec
- (void)configureNextViewController:(id)arg1;	// IMP=0x0010000000020d6a
- (id)onCameraButton;	// IMP=0x0010000000020d4a
- (id)commitConfiguration;	// IMP=0x0010000000020d2a
- (void)viewWillAppear:(_Bool)arg1;	// IMP=0x0010000000020cc0
- (void)viewDidLoad;	// IMP=0x0010000000020afd
- (id)initWithCoordinator:(id)arg1 config:(id)arg2;	// IMP=0x0010000000020887

@end

