//
//     Generated by classdumpios 4.2.0 (64 bit).
//
//  Copyright (C) 1997-2019 Steve Nygard. Updated in 2022 by Kevin Bradley.
//

@class HSProxCardCoordinator, HSSetupStateMachineConfiguration, HUIconView, NSString, UIViewController;
@protocol HFIconDescriptor;

@interface HSPCCenterIconViewController
{
    HSSetupStateMachineConfiguration *_config;	// 8 = 0x8
    HSProxCardCoordinator *_coordinator;	// 16 = 0x10
    HUIconView *_iconView;	// 24 = 0x18
}

- (void).cxx_destruct;	// IMP=0x002000000000205c
@property(retain, nonatomic) HUIconView *iconView; // @synthesize iconView=_iconView;
@property(retain) HSProxCardCoordinator *coordinator; // @synthesize coordinator=_coordinator;
@property(retain) HSSetupStateMachineConfiguration *config; // @synthesize config=_config;
- (id)commitConfiguration;	// IMP=0x0010000000001fc9
@property(readonly, nonatomic) id <HFIconDescriptor> iconDescriptor;
- (void)viewDidLoad;	// IMP=0x0010000000001eae
- (id)initWithCoordinator:(id)arg1 config:(id)arg2;	// IMP=0x0010000000001da0

// Remaining properties
@property(retain, nonatomic) UIViewController *contentVC;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

